import React from "react";
import { EnvironmentBanner } from "../../components/super-admin/EnvironmentBanner";
import { superAdminAuthService } from "../../services/superAdminAuthService";
import { TenantListPage } from "./tenants/TenantListPage";

export default function SuperAdminShell() {
  const [stage, setStage] = React.useState<"password"|"enroll"|"totp"|"recovery"|"authenticated">(localStorage.getItem("accessToken") ? "authenticated" : "password");
  const [challenge, setChallenge] = React.useState(""); const [email, setEmail] = React.useState(""); const [password, setPassword] = React.useState(""); const [code, setCode] = React.useState(""); const [qr, setQr] = React.useState(""); const [recoveryCodes, setRecoveryCodes] = React.useState<string[]>([]); const [environment, setEnvironment] = React.useState<"staging"|"production">("staging"); const [error, setError] = React.useState("");
  React.useEffect(() => { if (stage === "authenticated") superAdminAuthService.environment().then((v) => setEnvironment(v.environment)).catch(() => { localStorage.removeItem("accessToken"); setStage("password"); }); }, [stage]);
  const submitPassword = async (e: React.FormEvent) => { e.preventDefault(); setError(""); try { const r = await superAdminAuthService.login(email, password); if (r.status !== "challenge_required") throw new Error("Tài khoản không yêu cầu xác thực Super Admin"); setChallenge(r.challengeId); if (r.enrollmentRequired) { const enrollment = await superAdminAuthService.startEnrollment(r.challengeId); setQr(enrollment.qrDataUrl); setStage("enroll"); } else setStage("totp"); } catch (e) { setError((e as Error).message); } };
  const submitCode = async (e: React.FormEvent) => { e.preventDefault(); setError(""); try { const r = stage === "enroll" ? await superAdminAuthService.confirmEnrollment(challenge, code) : stage === "recovery" ? await superAdminAuthService.verifyRecovery(challenge, code) : await superAdminAuthService.verifyTotp(challenge, code); if (r.recoveryCodes) { setRecoveryCodes(r.recoveryCodes); return; } setQr(""); setCode(""); setStage("authenticated"); } catch (e) { setError((e as Error).message); } };
  if (stage === "authenticated") return <div className="min-h-screen bg-slate-950 text-slate-100"><EnvironmentBanner environment={environment}/><div className="flex"><aside className="min-h-[calc(100vh-32px)] w-64 border-r border-white/10 p-6"><h1 className="text-xl font-black">IGEN CONTROL</h1><p className="mt-1 text-xs text-slate-500">SUPER ADMIN</p>{["Overview","Security","Audit"].map(x=><div key={x} className="mt-6 text-sm text-slate-400">{x} <span className="text-[10px]">Sắp có</span></div>)}</aside><main className="p-10"><section className="mb-10"><h2 className="text-3xl font-bold">Tenant management</h2><TenantListPage onSelect={() => undefined}/></section><h2 className="text-3xl font-bold">Control Plane</h2><p className="mt-3 text-slate-400">Nền tảng bảo mật Phase 1 đã sẵn sàng. Các module vận hành sẽ được mở theo từng phase.</p></main></div></div>;
  return <main className="min-h-screen bg-slate-950 text-white grid place-items-center p-6"><section className="w-full max-w-md rounded-3xl border border-white/10 bg-slate-900 p-8 shadow-2xl"><p className="text-xs font-bold tracking-[.3em] text-cyan-400">IGEN SUPER ADMIN</p><h1 className="mt-3 text-2xl font-black">Đăng nhập đặc quyền</h1>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}{stage==="password"?<form onSubmit={submitPassword} className="mt-8 space-y-4"><input className="w-full rounded-xl bg-slate-800 p-3" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" className="w-full rounded-xl bg-slate-800 p-3" placeholder="Mật khẩu" value={password} onChange={e=>setPassword(e.target.value)}/><button className="w-full rounded-xl bg-cyan-500 p-3 font-bold text-slate-950">Tiếp tục</button></form>:recoveryCodes.length?<div className="mt-6"><p className="text-amber-300">Lưu các mã khôi phục này ngay. Chúng chỉ hiển thị một lần.</p><pre className="mt-4 rounded-xl bg-black/30 p-4">{recoveryCodes.join("\n")}</pre><button onClick={()=>{setRecoveryCodes([]);setQr("");setStage("authenticated")}} className="mt-4 w-full rounded-xl bg-cyan-500 p-3 font-bold text-slate-950">Tôi đã lưu mã</button></div>:<form onSubmit={submitCode} className="mt-6 space-y-4">{qr&&<img src={qr} alt="QR Google Authenticator" className="mx-auto rounded-xl bg-white p-3"/>}<input className="w-full rounded-xl bg-slate-800 p-3 text-center font-mono tracking-widest" placeholder={stage==="recovery"?"XXXXX-XXXXX":"000000"} value={code} onChange={e=>setCode(e.target.value)}/><button className="w-full rounded-xl bg-cyan-500 p-3 font-bold text-slate-950">Xác minh</button>{stage!=="enroll"&&<button type="button" onClick={()=>setStage(stage==="recovery"?"totp":"recovery")} className="w-full text-sm text-slate-400">{stage==="recovery"?"Dùng mã Authenticator":"Dùng mã khôi phục"}</button>}</form>}</section></main>;
}
