import { PayrollAuditModel } from "../model/payroll-audit.model";
import { PayrollPeriodInputModel } from "../model/payroll-period-input.model";
import { PayrollRunModel } from "../model/payroll-run.model";
import { PayrollCustomVariableModel } from "../model/payroll-custom-variable.model";
const failure=(code:string,message:string,status=400):never=>{throw Object.assign(new Error(message),{code,status});};
const finiteNonNegative=(value:any)=>value===undefined||(Number.isFinite(value)&&value>=0);
const periodInputFields=["agreedSalary","reconciledDays","reconciledHours","allowance","bonus","deduction"] as const;
function buildPeriodInputChanges(input:any){const{reason,expectedVersion,clearFields:raw,...rawValues}=input;const clearFields=Array.isArray(raw)?[...new Set<string>(raw.map(String))]:[];for(const field of clearFields)if(!periodInputFields.includes(field as any)&&!/^custom\.[A-Za-z][A-Za-z0-9_]*$/.test(field))failure("PAYROLL_PERIOD_INPUT_CLEAR_FIELD_INVALID",`${field} không thể hoàn tác`);const values:any={...rawValues};for(const field of clearFields)if(periodInputFields.includes(field as any))delete values[field];if(values.customValues){values.customValues={...values.customValues};for(const field of clearFields)if(field.startsWith("custom."))delete values.customValues[field.slice(7)];if(!Object.keys(values.customValues).length)delete values.customValues;}const unset=Object.fromEntries(clearFields.map(field=>[field.startsWith("custom.")?`customValues.${field.slice(7)}`:field,1]));return{reason,expectedVersion,clearFields,values,unset};}
export async function assertPeriodInputEditable(scope:{companyCode:string;branchId:string},periodKey:string){const run:any=await PayrollRunModel.findOne({...scope,periodKey,type:"regular"}).sort({createdAt:-1}).lean();if(run&&run.status!=="draft")failure("PAYROLL_PERIOD_INPUT_LOCKED","Dữ liệu đầu vào đã bị khóa",409);return run;}
export async function listPayrollPeriodInputs(scope:{companyCode:string;branchId:string},periodKey:string){const [items,variables,run]=await Promise.all([(PayrollPeriodInputModel as any).find({...scope,periodKey}).lean(),PayrollCustomVariableModel.find({companyCode:scope.companyCode,status:"active"}).sort({code:1}).lean(),PayrollRunModel.findOne({...scope,periodKey,type:"regular"}).sort({createdAt:-1}).lean()]);return{items,variables,editable:!run||run.status==="draft",needsRefresh:Boolean(run?.needsInputRefresh)};}
export async function savePayrollPeriodInput(scope:{companyCode:string;branchId:string},periodKey:string,employeeId:string,actorId:string,input:any){
if(!input.reason?.trim())failure("PAYROLL_PERIOD_INPUT_REASON_REQUIRED","Cần nhập lý do đối soát");
await assertPeriodInputEditable(scope,periodKey);
for(const key of periodInputFields)if(!finiteNonNegative(input[key]))failure("PAYROLL_PERIOD_INPUT_VALUE_INVALID",`${key} không hợp lệ`);
for(const value of Object.values(input.customValues??{}))if(!finiteNonNegative(value))failure("PAYROLL_PERIOD_INPUT_VALUE_INVALID","Giá trị tùy chỉnh không hợp lệ");
const {reason,expectedVersion,clearFields,values,unset}=buildPeriodInputChanges(input);
const filter:any={...scope,periodKey,employeeId,version:Number(expectedVersion??0)};
const before:any=await PayrollPeriodInputModel.findOne({...scope,periodKey,employeeId}).lean();
const update:any={$set:{...values,reason:reason.trim(),updatedBy:actorId},$setOnInsert:{companyCode:scope.companyCode,branchId:scope.branchId,periodKey,employeeId},$inc:{version:1}};
if(Object.keys(unset).length)update.$unset=unset;
const updated:any=await PayrollPeriodInputModel.findOneAndUpdate(filter,update,{new:true,upsert:Number(expectedVersion??0)===0,runValidators:true}).lean();
if(!updated)failure("PAYROLL_PERIOD_INPUT_VERSION_CONFLICT","Dữ liệu đã được người khác thay đổi",409);
await PayrollRunModel.updateOne({...scope,periodKey,type:"regular",status:"draft"},{$set:{needsInputRefresh:true}});
await PayrollAuditModel.create({...scope,periodKey,action:"adjustment",actorId,metadata:{operation:"period_input",employeeId,reason:reason.trim(),values,clearFields,before,after:updated}});
return updated;
}
export async function bulkSavePayrollPeriodInputs(scope:{companyCode:string;branchId:string},periodKey:string,actorId:string,rows:any[]){const results=[];for(const row of rows){try{results.push({employeeId:row.employeeId,status:"success",data:await savePayrollPeriodInput(scope,periodKey,row.employeeId,actorId,row)});}catch(error:any){results.push({employeeId:row.employeeId,status:"error",code:error.code,message:error.message});}}return results;}
export async function listPayrollCustomVariables(companyCode:string){return PayrollCustomVariableModel.find({companyCode}).sort({code:1}).lean();}
export async function createPayrollCustomVariable(companyCode:string,actorId:string,input:any){if(!input.code?.trim()||!input.name?.trim())failure("PAYROLL_CUSTOM_VARIABLE_REQUIRED","Mã và tên biến là bắt buộc");if(input.unit==="percent"&&input.defaultValue!==undefined&&(input.defaultValue<0||input.defaultValue>100))failure("PAYROLL_CUSTOM_VARIABLE_VALUE_INVALID","Phần trăm phải từ 0 đến 100");return PayrollCustomVariableModel.create({...input,code:input.code.trim(),companyCode,status:"draft",createdBy:actorId});}
export async function updatePayrollCustomVariable(companyCode:string,id:string,expectedVersion:number,input:any){const current:any=await PayrollCustomVariableModel.findOne({_id:id,companyCode}).lean();if(!current)failure("PAYROLL_CUSTOM_VARIABLE_NOT_FOUND","Không tìm thấy biến",404);if(current.status!=="draft"&&input.code&&input.code!==current.code)failure("PAYROLL_CUSTOM_VARIABLE_CODE_IMMUTABLE","Không thể đổi mã biến đang dùng",409);const updated:any=await PayrollCustomVariableModel.findOneAndUpdate({_id:id,companyCode,version:expectedVersion,status:{$in:["draft","active"]}},{$set:input,$inc:{version:1}},{new:true,runValidators:true}).lean();if(!updated)failure("PAYROLL_CUSTOM_VARIABLE_VERSION_CONFLICT","Biến đã thay đổi",409);return updated;}
export async function activatePayrollCustomVariable(companyCode:string,id:string,actorId:string){const value:any=await PayrollCustomVariableModel.findOneAndUpdate({_id:id,companyCode,status:{$in:["draft","retired"]}},{$set:{status:"active",activatedBy:actorId},$unset:{retiredBy:1}},{new:true}).lean();if(!value)failure("PAYROLL_CUSTOM_VARIABLE_INVALID_STATE","Không thể áp dụng biến",409);return value;}
export async function retirePayrollCustomVariable(companyCode:string,id:string,actorId:string){const value:any=await PayrollCustomVariableModel.findOneAndUpdate({_id:id,companyCode,status:"active"},{$set:{status:"retired",retiredBy:actorId}},{new:true}).lean();if(!value)failure("PAYROLL_CUSTOM_VARIABLE_INVALID_STATE","Không thể ngưng biến",409);return value;}
