import { PayrollFormulaModel } from "../model/payroll-formula.model";
import { validatePayrollFormulaDefinition } from "./payroll-formula-engine.service";
import { DEFAULT_PAYROLL_FORMULA_TEMPLATES } from "../config/payroll-formula-templates";

function reject(failure: any): never { throw Object.assign(new Error(failure.message), { code: failure.code, status: failure.status ?? 400 }); }
function validated(input: any) { const invalid = validatePayrollFormulaDefinition(input); if (invalid) reject(invalid); return input; }
export async function listPayrollFormulas(companyCode: string) { let items: any[] = await PayrollFormulaModel.find({ companyCode }).sort({ priority: 1, code: 1 }).lean(); if (!items.length) { await Promise.all(DEFAULT_PAYROLL_FORMULA_TEMPLATES.map((template) => createPayrollFormula(companyCode, "system", template).catch((error: any) => { if (error?.code !== "PAYROLL_FORMULA_DUPLICATE") throw error; }))); items = await PayrollFormulaModel.find({ companyCode }).sort({ priority: 1, code: 1 }).lean(); } return items; }
export async function createPayrollFormula(companyCode: string, actorId: string, input: any) { try { return await PayrollFormulaModel.create({ ...validated(input), companyCode, status: "draft", createdBy: actorId }); } catch (error: any) { if (error?.code === 11000) reject({ code: "PAYROLL_FORMULA_DUPLICATE", message: "Mã công thức đã tồn tại", status: 409 }); throw error; } }
export async function updatePayrollFormula(companyCode: string, id: string, expectedVersion: number, input: any) { const updated: any = await PayrollFormulaModel.findOneAndUpdate({ _id: id, companyCode, status: { $in: ["draft", "active"] }, version: expectedVersion }, { $set: validated(input), $inc: { version: 1 } }, { new: true, runValidators: true }).lean(); if (!updated) reject({ code: "PAYROLL_FORMULA_VERSION_CONFLICT", message: "Công thức đã thay đổi hoặc không thể sửa", status: 409 }); return updated; }
export async function activatePayrollFormula(companyCode: string, id: string, actorId: string) { const value: any = await PayrollFormulaModel.findOneAndUpdate({ _id: id, companyCode, status: { $in: ["draft", "retired"] } }, { $set: { status: "active", activatedBy: actorId, activatedAt: new Date() }, $unset: { retiredBy: 1 } }, { new: true }).lean(); if (!value) reject({ code: "PAYROLL_FORMULA_INVALID_STATE", message: "Không thể áp dụng công thức", status: 409 }); return value; }
export async function retirePayrollFormula(companyCode: string, id: string, actorId: string) { const value: any = await PayrollFormulaModel.findOneAndUpdate({ _id: id, companyCode, status: "active" }, { $set: { status: "retired", retiredBy: actorId } }, { new: true }).lean(); if (!value) reject({ code: "PAYROLL_FORMULA_INVALID_STATE", message: "Chỉ có thể ngưng công thức đang áp dụng", status: 409 }); return value; }
export async function clonePayrollFormula(companyCode: string, id: string, actorId: string, code: string) { const source: any = await PayrollFormulaModel.findOne({ _id: id, companyCode }).lean(); if (!source) reject({ code: "PAYROLL_FORMULA_NOT_FOUND", message: "Không tìm thấy công thức", status: 404 }); const { _id, status, version, activatedAt, activatedBy, retiredBy, createdAt, updatedAt, ...definition } = source; return createPayrollFormula(companyCode, actorId, { ...definition, code, name: `${source.name} - Bản sao` }); }
