version: '3.8'

services:
  igen-erp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: igen-erp
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    networks:
      - default_network
networks:
  default_network:
    external: true
