import { useState, type Dispatch, type FormEvent, type SetStateAction } from "react";
import { Pencil, Plus, Save, Trash2, X } from "lucide-react";
import type { WorkerScope } from "../../types";
import { laborPartnersApi } from "../api/laborPartners.api";
import type { CommissionPolicy } from "../types";
import { formatWorkerDate } from "../../utils/date";
import { toIsoDate } from "../../utils/contractDate";

type Rule = "contract_active" | "manual_confirmation" | "attendance_threshold";
type Form = { name: string; effectiveFrom: string; cycle: "calendar_month" | "cutoff_day"; cutoffDay: string; officialEnabled: boolean; maxMonths: 1 | 2 | 3; milestones: Array<{ amount: string; rule: Rule; days: string; hours: string }>; seasonalEnabled: boolean; scope: "partner_period" | "partner_project_period"; tierMode: "flat" | "progressive"; minHours: string; maxHours: string; roundingMinutes: "1" | "5" | "15" | "30" | "60"; roundingMode: "floor" | "nearest" | "ceil"; moneyUnit: string; moneyMode: "floor" | "nearest" | "ceil"; tiers: Array<{ min: string; max: string; rate: string }> };
const today = () => new Date().toISOString().slice(0, 10);
const empty = (): Form => ({ name: "", effectiveFrom: today(), cycle: "calendar_month", cutoffDay: "", officialEnabled: false, maxMonths: 1, milestones: [{ amount: "", rule: "contract_active", days: "", hours: "" }, { amount: "", rule: "contract_active", days: "", hours: "" }, { amount: "", rule: "contract_active", days: "", hours: "" }], seasonalEnabled: false, scope: "partner_period", tierMode: "flat", minHours: "", maxHours: "", roundingMinutes: "1", roundingMode: "nearest", moneyUnit: "1", moneyMode: "nearest", tiers: [{ min: "0", max: "", rate: "" }] });
const fromPolicy = (policy: CommissionPolicy): Form => ({ name: policy.name, effectiveFrom: policy.effectiveFrom, cycle: policy.settlementCycle.type, cutoffDay: policy.settlementCycle.cutoffDay ? String(policy.settlementCycle.cutoffDay) : "", officialEnabled: policy.official.enabled, maxMonths: policy.official.maxMonths || 1, milestones: [0, 1, 2].map((index) => { const item = policy.official.milestones[index]; return { amount: item ? String(item.amount) : "", rule: item?.eligibilityRule || "contract_active", days: item?.minWorkedDays == null ? "" : String(item.minWorkedDays), hours: item?.minWorkedHours == null ? "" : String(item.minWorkedHours) }; }), seasonalEnabled: policy.seasonal.enabled, scope: "partner_period", tierMode: policy.seasonal.tierMode || "flat", minHours: policy.seasonal.minHoursPerWorker == null ? "" : String(policy.seasonal.minHoursPerWorker), maxHours: policy.seasonal.maxEligibleHoursPerWorker == null ? "" : String(policy.seasonal.maxEligibleHoursPerWorker), roundingMinutes: String(policy.seasonal.hourRounding.unitMinutes) as Form["roundingMinutes"], roundingMode: policy.seasonal.hourRounding.mode, moneyUnit: String(policy.seasonal.moneyRounding.unitVnd), moneyMode: policy.seasonal.moneyRounding.mode, tiers: policy.seasonal.tiers.map((tier) => ({ min: String(tier.minHours), max: tier.maxHours == null ? "" : String(tier.maxHours), rate: String(tier.hourlyRate) })) });
const input = (value: string) => value === "" ? null : Number(value);
const tierModeHelp = (mode: Form["tierMode"]) => mode === "progressive"
  ? "Tổng giờ của toàn bộ lao động được chia thành từng đoạn và cộng theo đơn giá của từng đoạn."
  : "Khi tổng giờ của toàn bộ lao động rơi vào một bậc, toàn bộ giờ áp dụng đơn giá của bậc đó.";
const tierMinLabel = (mode: Form["tierMode"]) => mode === "progressive" ? "Bắt đầu đoạn tổng giờ *" : "Từ tổng giờ *";
const tierMaxLabel = (mode: Form["tierMode"], isLast: boolean) => isLast ? "Đến tổng giờ (không giới hạn)" : mode === "progressive" ? "Kết thúc đoạn tổng giờ *" : "Đến tổng giờ *";
const tierRateLabel = (mode: Form["tierMode"]) => mode === "progressive" ? "Đơn giá đoạn tổng giờ (VND/giờ) *" : "Đơn giá áp cho toàn bộ tổng giờ (VND/giờ) *";

export function LaborPartnerPoliciesPanel({ scope, policies, error, canManage, reload }: { scope: WorkerScope; policies: CommissionPolicy[]; error: string; canManage: boolean; reload: () => Promise<void> }) {
  const [form, setFormState] = useState<Form>(empty());
  const setForm: Dispatch<SetStateAction<Form>> = (update) => setFormState((current) => {
    const next = typeof update === "function" ? update(current) : update;
    if (next.officialEnabled && next.seasonalEnabled) {
      return current.officialEnabled ? { ...next, officialEnabled: false } : { ...next, seasonalEnabled: false };
    }
    return next;
  });
  const [editingId, setEditingId] = useState<string | null>(null); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const openNew = () => { setForm(empty()); setEditingId(null); setShow(true); setMessage(""); };
  const openEdit = (policy: CommissionPolicy) => { setForm(fromPolicy(policy)); setEditingId(policy._id); setShow(true); setMessage(""); };
  const payload = (): Omit<CommissionPolicy, "_id" | "version" | "status"> => ({ name: form.name, effectiveFrom: form.effectiveFrom, settlementCycle: { type: form.cycle, cutoffDay: form.cycle === "cutoff_day" ? Number(form.cutoffDay) : null }, official: { enabled: form.officialEnabled, maxMonths: form.officialEnabled ? form.maxMonths : null, milestones: form.officialEnabled ? form.milestones.slice(0, form.maxMonths).map((item, index) => ({ month: (index + 1) as 1 | 2 | 3, amount: Number(item.amount), eligibilityRule: item.rule, minWorkedDays: item.rule === "attendance_threshold" ? input(item.days) : null, minWorkedHours: item.rule === "attendance_threshold" ? input(item.hours) : null })) : [] }, seasonal: { enabled: form.seasonalEnabled, aggregationScope: form.seasonalEnabled ? form.scope : null, tierMode: form.seasonalEnabled ? form.tierMode : null, minHoursPerWorker: form.seasonalEnabled ? input(form.minHours) : null, maxEligibleHoursPerWorker: form.seasonalEnabled ? input(form.maxHours) : null, hourRounding: { unitMinutes: Number(form.roundingMinutes) as 1 | 5 | 15 | 30 | 60, mode: form.roundingMode }, moneyRounding: { unitVnd: Number(form.moneyUnit), mode: form.moneyMode }, tiers: form.seasonalEnabled ? form.tiers.map((tier, index) => ({ minHours: Number(tier.min), maxHours: index === form.tiers.length - 1 ? null : Number(tier.max), hourlyRate: Number(tier.rate) })) : [] } });
const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(""); try { if (editingId) await laborPartnersApi.updatePolicy(scope, editingId, payload()); else await laborPartnersApi.createPolicy(scope, payload()); setShow(false); await reload(); setMessage(editingId ? "Đã cập nhật chính sách." : "Đã tạo chính sách mới."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Không thể lưu chính sách."); } finally { setBusy(false); } };
const action = async (run: () => Promise<unknown>, success: string) => { setBusy(true); setMessage(""); try { await run(); await reload(); setMessage(success); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Không thể cập nhật chính sách."); } finally { setBusy(false); } };
const remove = async (policy: CommissionPolicy) => { if (!window.confirm(`Xóa chính sách ${policy.name}?`)) return; await action(() => laborPartnersApi.removePolicy(scope, policy._id), "Đã xóa chính sách."); };
return <section className={`rounded-2xl border border-slate-200 bg-white p-4 sm:p-5 ${form.officialEnabled ? "[&_[data-toggle=seasonal]]:hidden" : form.seasonalEnabled ? "[&_[data-toggle=official]]:hidden" : ""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black text-slate-800">Chính sách hoa hồng</h2><p className="mt-1 text-xs text-slate-500">Thêm, sửa hoặc xóa chính sách hoa hồng. Thời vụ tính trên tổng giờ của toàn bộ lao động trong tháng.</p></div>{canManage && <button type="button" onClick={openNew} className="inline-flex h-9 items-center gap-2 rounded-lg bg-cyan-600 px-3 text-xs font-bold text-white"><Plus className="h-4 w-4" /> Tạo chính sách</button>}</div>{message && !show && <p role="status" className="mt-3 text-sm font-medium text-cyan-700">{message}</p>}
{show && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4" role="dialog" aria-modal="true" aria-labelledby="labor-policy-form-title"><div className="max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><form onSubmit={(event) => void submit(event)} className="grid gap-4 p-5 sm:p-6"><div className="flex items-center justify-between"><h3 id="labor-policy-form-title" className="text-sm font-black text-slate-800">{editingId ? "Sửa chính sách" : "Chính sách mới"}</h3><button type="button" onClick={() => setShow(false)} className="text-slate-500"><X className="h-4 w-4" /></button></div>{message && <p role="status" className="text-sm font-medium text-red-600">{message}</p>}<div className="grid gap-3 sm:grid-cols-3"><Field label="Tên chính sách *" value={form.name} onChange={(name) => setForm((v) => ({ ...v, name }))} /><Field label="Hiệu lực từ *" type="date" value={form.effectiveFrom} onChange={(effectiveFrom) => setForm((v) => ({ ...v, effectiveFrom }))} /><Select label="Chu kỳ" value={form.cycle} onChange={(cycle) => setForm((v) => ({ ...v, cycle: cycle as Form["cycle"] }))} options={[['calendar_month','Theo tháng'],['cutoff_day','Theo ngày chốt']]} /></div>{form.cycle === "cutoff_day" && <Field label="Ngày chốt (1–28) *" type="number" value={form.cutoffDay} onChange={(cutoffDay) => setForm((v) => ({ ...v, cutoffDay }))} />}
<Toggle label="Hoa hồng chính thức" checked={form.officialEnabled} onChange={(officialEnabled) => setForm((v) => ({ ...v, officialEnabled }))} />{form.officialEnabled && <div className="grid gap-3 rounded-lg bg-white p-3"><Select label="Số mốc tháng (tối đa 3)" value={String(form.maxMonths)} onChange={(value) => setForm((v) => ({ ...v, maxMonths: Number(value) as 1 | 2 | 3 }))} options={[["1","1 tháng"],["2","2 tháng"],["3","3 tháng"]]} />{form.milestones.slice(0, form.maxMonths).map((milestone, index) => <div key={index} className="grid gap-2 border-t border-slate-100 pt-3 sm:grid-cols-4"><Field label={`Mốc ${index + 1}: tiền VND *`} type="number" value={milestone.amount} onChange={(amount) => setForm((v) => ({ ...v, milestones: v.milestones.map((item, i) => i === index ? { ...item, amount } : item) }))} /><Select label="Điều kiện" value={milestone.rule} onChange={(rule) => setForm((v) => ({ ...v, milestones: v.milestones.map((item, i) => i === index ? { ...item, rule: rule as Rule } : item) }))} options={[["contract_active","Hợp đồng đang hiệu lực"],["manual_confirmation","Xác nhận tay"],["attendance_threshold","Theo chấm công"]]} />{milestone.rule === "attendance_threshold" && <><Field label="Tối thiểu ngày" type="number" value={milestone.days} onChange={(days) => setForm((v) => ({ ...v, milestones: v.milestones.map((item, i) => i === index ? { ...item, days } : item) }))} /><Field label="Tối thiểu giờ" type="number" value={milestone.hours} onChange={(hours) => setForm((v) => ({ ...v, milestones: v.milestones.map((item, i) => i === index ? { ...item, hours } : item) }))} /></>}</div>)}</div>}
<Toggle label="Hoa hồng thời vụ" checked={form.seasonalEnabled} onChange={(seasonalEnabled) => setForm((v) => ({ ...v, seasonalEnabled }))} />{form.seasonalEnabled && <div className="grid gap-3 rounded-lg bg-white p-3"><p className="rounded-lg border border-cyan-100 bg-cyan-50 px-3 py-2 text-xs leading-5 text-cyan-800">{tierModeHelp(form.tierMode)}</p><div className="grid gap-3 sm:grid-cols-3"><Select label="Phạm vi tính" value={form.scope} onChange={(scope) => setForm((v) => ({ ...v, scope: scope as Form["scope"] }))} options={[["partner_period","Tổng giờ của đối tác trong tháng"]]} /><Select label="Kiểu tính" value={form.tierMode} onChange={(tierMode) => setForm((v) => ({ ...v, tierMode: tierMode as Form["tierMode"] }))} options={[["flat","Áp toàn bộ giờ"],["progressive","Lũy tiến"]]} /><Field label="Tổng giờ tối thiểu trong tháng" type="number" value={form.minHours} onChange={(minHours) => setForm((v) => ({ ...v, minHours }))} /><Field label="Tổng giờ tối đa được tính trong tháng" type="number" value={form.maxHours} onChange={(maxHours) => setForm((v) => ({ ...v, maxHours }))} /><Select label="Làm tròn giờ" value={form.roundingMinutes} onChange={(roundingMinutes) => setForm((v) => ({ ...v, roundingMinutes: roundingMinutes as Form["roundingMinutes"] }))} options={[["1","1 phút"],["5","5 phút"],["15","15 phút"],["30","30 phút"],["60","60 phút"]]} /><Field label="Làm tròn tiền (VND)" type="number" value={form.moneyUnit} onChange={(moneyUnit) => setForm((v) => ({ ...v, moneyUnit }))} /></div>{form.tiers.map((tier, index) => <div key={index} className="grid gap-2 sm:grid-cols-4"><Field label={tierMinLabel(form.tierMode)} type="number" value={tier.min} onChange={(min) => setForm((v) => ({ ...v, tiers: v.tiers.map((item, i) => i === index ? { ...item, min } : item) }))} /><Field label={tierMaxLabel(form.tierMode, index === form.tiers.length - 1)} type="number" value={tier.max} onChange={(max) => setForm((v) => ({ ...v, tiers: v.tiers.map((item, i) => i === index ? { ...item, max } : item) }))} /><Field label={tierRateLabel(form.tierMode)} type="number" value={tier.rate} onChange={(rate) => setForm((v) => ({ ...v, tiers: v.tiers.map((item, i) => i === index ? { ...item, rate } : item) }))} />{index === form.tiers.length - 1 && <button type="button" onClick={() => setForm((v) => ({ ...v, tiers: [...v.tiers, { min: "", max: "", rate: "" }] }))} className="h-9 self-end rounded-lg border border-cyan-200 text-xs font-bold text-cyan-700">+ Bậc</button>}</div>)}</div>}<button disabled={busy || (!form.officialEnabled && !form.seasonalEnabled)} className="inline-flex h-9 w-fit items-center gap-2 rounded-lg bg-cyan-600 px-4 text-xs font-bold text-white disabled:opacity-50"><Save className="h-4 w-4" /> Lưu chính sách</button></form></div></div>}
{error ? <p role="alert" className="mt-4 text-sm text-rose-600">{error}</p> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[940px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase text-slate-500"><tr><th className="px-3 py-2">Tên chính sách</th><th className="px-3 py-2">Hiệu lực</th><th className="px-3 py-2">Chính thức</th><th className="px-3 py-2">Thời vụ</th><th className="px-3 py-2">Trạng thái</th><th className="px-3 py-2" /></tr></thead><tbody>{policies.map((policy) => <tr key={policy._id} className="border-b border-slate-100"><td className="px-3 py-3"><p className="font-bold text-slate-800">{policy.name}</p><p className="text-xs text-slate-400">v{policy.version}</p></td><td className="px-3 py-3 text-slate-600">{policy.effectiveFrom}</td><td className="px-3 py-3 text-slate-600">{policy.official.enabled ? <>{policy.official.maxMonths} tháng</> : "Tắt"}</td><td className="px-3 py-3 text-slate-600">{policy.seasonal.enabled ? (policy.seasonal.tierMode === "flat" ? "Áp toàn bộ giờ" : "Lũy tiến") : "Tắt"}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${policy.status === "active" ? "bg-emerald-50 text-emerald-700" : policy.status === "draft" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{policy.status === "active" ? "Đang dùng" : policy.status === "draft" ? "Bản nháp" : "Đã ngừng"}</span></td><td className="px-3 py-3 text-right"><div className="inline-flex items-center gap-2">{canManage && <><button type="button" disabled={busy} onClick={() => openEdit(policy)} aria-label="Sửa chính sách" className="rounded-lg border border-slate-200 p-1.5 text-slate-600"><Pencil className="h-3.5 w-3.5" /></button>{policy.status === "active" ? <button type="button" disabled={busy} onClick={() => { if (window.confirm(`Ngừng áp dụng chính sách ${policy.name}?`)) void action(() => laborPartnersApi.retirePolicy(scope, policy._id), "Đã ngừng áp dụng chính sách."); }} aria-label="Ngừng áp dụng chính sách" className="rounded-lg border border-amber-200 px-2 py-1 text-[11px] font-bold text-amber-700">Ngừng</button> : <button type="button" disabled={busy} onClick={() => void action(() => laborPartnersApi.activatePolicy(scope, policy._id), policy.status === "retired" ? "Đã kích hoạt lại chính sách." : "Đã kích hoạt chính sách.")} aria-label={policy.status === "retired" ? "Kích hoạt lại chính sách" : "Kích hoạt chính sách"} className="rounded-lg border border-emerald-200 px-2 py-1 text-[11px] font-bold text-emerald-700">{policy.status === "retired" ? "Dùng lại" : "Kích hoạt"}</button>}<button type="button" disabled={busy} onClick={() => void remove(policy)} aria-label="Xóa chính sách" className="rounded-lg border border-rose-200 p-1.5 text-rose-600"><Trash2 className="h-3.5 w-3.5" /></button></>}</div></td></tr>)}</tbody></table></div>}</section>;
}
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) {
  const placeholder = `Nhập ${label.replace(/\s*\*$/, "").toLowerCase()}`;
  const numeric = type === "number";
  const date = type === "date";
  const displayValue = numeric ? formatGroupedNumber(value) : date ? formatWorkerDate(value) : value;
  return <label className="grid gap-1 text-xs font-bold text-slate-600"><span>{label}</span><input required={label.includes("*")} type={numeric || date ? "text" : type} inputMode={numeric || date ? "numeric" : undefined} value={displayValue} placeholder={date ? "DD/MM/YYYY" : placeholder} onChange={(event) => onChange(numeric ? event.target.value.replace(/\./g, "").replace(/[^\d-]/g, "") : date ? toIsoDate(event.target.value) : event.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-sm placeholder:text-slate-300" /></label>;
}
function formatGroupedNumber(value: string) { const normalized = String(value || "").replace(/\./g, "").replace(/[^\d-]/g, ""); const sign = normalized.startsWith("-") ? "-" : ""; const digits = normalized.replace(/-/g, ""); return `${sign}${digits.replace(/\B(?=(\d{3})+(?!\d))/g, ".")}`; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <label className="grid gap-1 text-xs font-bold text-slate-600"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-sm">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { const mode = label.includes("chính thức") ? "official" : label.includes("thời vụ") ? "seasonal" : undefined; return <label data-toggle={mode} className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /> {label}</label>; }
