import React from "react";
import { Eye, Loader2, Save } from "lucide-react";
import { companyEmailApi } from "../../services/companyEmailService";
import { toast } from "../../pages/Toast";

const defaults = { birthdayEnabled: false, holidayEnabled: false, sendTime: "08:00", birthdayTemplate: { subject: "Chúc mừng sinh nhật {{employeeName}}", html: "<p>Chúc mừng sinh nhật {{employeeName}}!</p>" }, holidayTemplate: { subject: "Chúc mừng {{holidayName}}", html: "<p>{{companyName}} kính chúc bạn một kỳ nghỉ vui vẻ.</p>" }, holidayOverrides: [] };
export default function CelebrationEmailTab() {
  const [config, setConfig] = React.useState<any>(defaults); const [history, setHistory] = React.useState<any[]>([]); const [busy, setBusy] = React.useState(false); const [preview, setPreview] = React.useState<any>(null);
  const load = React.useCallback(() => Promise.all([companyEmailApi.getCelebration(), companyEmailApi.history()]).then(([c, h]) => { setConfig({ ...defaults, ...(c || {}) }); setHistory(h); }).catch((e) => toast.error(e.message)), []);
  React.useEffect(() => { void load(); }, [load]);
  const template = (key: "birthdayTemplate" | "holidayTemplate", field: "subject" | "html", value: string) => setConfig((c: any) => ({ ...c, [key]: { ...c[key], [field]: value } }));
  const save = async () => { setBusy(true); try { await companyEmailApi.saveCelebration(config); toast.success("Đã lưu cấu hình email chúc mừng."); } catch (e: any) { toast.error(e.message); } finally { setBusy(false); } };
  const showPreview = async (value: any) => { try { setPreview(await companyEmailApi.preview(value)); } catch (e: any) { toast.error(e.message); } };
  return <div className="min-h-0 flex-1 overflow-y-auto p-5 space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-800">Email chúc mừng</h2><p className="text-xs text-slate-500">Tự động gửi theo giờ Việt Nam.</p></div><button onClick={save} disabled={busy} className="inline-flex items-center gap-2 bg-cyan-600 text-white rounded-lg px-3 py-2 text-xs font-bold">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Lưu</button></div>
    <div className="flex flex-wrap gap-5 border-y border-slate-200 py-4"><Toggle label="Tự động sinh nhật" checked={config.birthdayEnabled} onChange={(v: boolean) => setConfig({ ...config, birthdayEnabled: v })} /><Toggle label="Tự động lễ/Tết" checked={config.holidayEnabled} onChange={(v: boolean) => setConfig({ ...config, holidayEnabled: v })} /><label className="text-xs font-semibold text-slate-600">Giờ gửi <input type="time" value={config.sendTime} onChange={(e) => setConfig({ ...config, sendTime: e.target.value })} className="ml-2 border rounded-lg px-2 py-1.5" /></label></div>
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><Template title="Mẫu sinh nhật" value={config.birthdayTemplate} onChange={(f: any, v: string) => template("birthdayTemplate", f, v)} onPreview={() => showPreview(config.birthdayTemplate)} /><Template title="Mẫu lễ/Tết mặc định" value={config.holidayTemplate} onChange={(f: any, v: string) => template("holidayTemplate", f, v)} onPreview={() => showPreview({ ...config.holidayTemplate, holidayName: "Ngày lễ" })} /></div>
    {preview && <div className="border border-cyan-200 bg-cyan-50 p-4 rounded-lg"><p className="font-bold text-sm">{preview.subject}</p><div className="prose prose-sm mt-2" dangerouslySetInnerHTML={{ __html: preview.html }} /></div>}
    <div><h3 className="font-bold text-sm text-slate-800 mb-3">Lịch sử gửi</h3><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b text-left text-slate-500"><th className="py-2">Người nhận</th><th>Loại</th><th>Ngày</th><th>Trạng thái</th></tr></thead><tbody>{history.map((row) => <tr key={row._id} className="border-b"><td className="py-2">{row.recipientEmail}</td><td>{row.eventType}</td><td>{row.eventDate}</td><td>{row.status}</td></tr>)}</tbody></table></div></div>
  </div>;
}
function Toggle({ label, checked, onChange }: any) { return <label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} />{label}</label>; }
function Template({ title, value, onChange, onPreview }: any) { return <section className="border border-slate-200 rounded-lg p-4 space-y-3"><h3 className="font-bold text-sm">{title}</h3><input value={value.subject} onChange={(e) => onChange("subject", e.target.value)} className="w-full border rounded-lg px-3 py-2 text-xs" placeholder="Tiêu đề" /><textarea value={value.html} onChange={(e) => onChange("html", e.target.value)} rows={7} className="w-full border rounded-lg px-3 py-2 text-xs font-mono" /><button type="button" onClick={onPreview} className="inline-flex items-center gap-2 border rounded-lg px-3 py-2 text-xs"><Eye className="h-4 w-4" />Xem trước</button></section>; }
