import React, { useEffect, useMemo, useState } from "react";
import { FileSignature, Pencil, Plus, RefreshCw, Search } from "lucide-react";
import { getAccessToken } from "../../services/authService";
import { toast } from "../../pages/Toast";
import { getApiErrorMessage } from "../../utils/errorMessage";

type ContractStatus = "draft" | "active" | "expired" | "terminated";
type Contract = { _id: string; contractType: string; employeeId: string; employeeName: string; startDate: string; endDate: string; status: ContractStatus; contractFileUrl?: string; signedImageUrl?: string; note?: string };
type Employee = { _id: string; displayName?: string; email: string; department?: string };
type Extension = { _id: string; contractId: string; employeeName: string; previousEndDate: string; newEndDate: string; extensionDate: string; reason?: string; extensionFileUrl?: string; signedImageUrl?: string };
const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${getAccessToken()}` });
const date = (value?: string) => value ? new Intl.DateTimeFormat("vi-VN").format(new Date(value)) : "—";
const isoDate = (value?: string) => value ? new Date(value).toISOString().slice(0, 10) : "";
const emptyContract = { contractType: "Hợp đồng xác định thời hạn", employeeId: "", startDate: "", endDate: "", status: "active" as ContractStatus, contractFileUrl: "", signedImageUrl: "", note: "" };
const emptyExtension = { contractId: "", newEndDate: "", extensionDate: new Date().toISOString().slice(0, 10), reason: "", extensionFileUrl: "", signedImageUrl: "" };
const input = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-500/15";
const statusLabel: Record<ContractStatus, string> = { draft: "Bản nháp", active: "Còn hiệu lực", expired: "Hết hạn", terminated: "Đã chấm dứt" };
const statusStyle: Record<ContractStatus, string> = { draft: "bg-slate-100 text-slate-600", active: "bg-emerald-50 text-emerald-700", expired: "bg-amber-50 text-amber-700", terminated: "bg-rose-50 text-rose-700" };

export default function ContractsTab({ canManage, companyCode }: { canManage: boolean; companyCode: string }) {
  const [tab, setTab] = useState<"contracts" | "extensions">("contracts");
  const [contracts, setContracts] = useState<Contract[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [extensions, setExtensions] = useState<Extension[]>([]);
  const [loading, setLoading] = useState(true); const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<Contract | "new" | null>(null); const [contractForm, setContractForm] = useState(emptyContract);
  const [extOpen, setExtOpen] = useState(false); const [extensionForm, setExtensionForm] = useState(emptyExtension); const [saving, setSaving] = useState(false);
  const suffix = `?companyCode=${encodeURIComponent(companyCode)}`;
  const load = async () => { setLoading(true); try { const [a, b] = await Promise.all([fetch(`/api/v1/hr-contracts${suffix}`, { headers: headers() }), fetch(`/api/v1/hr-contracts/extensions/list${suffix}`, { headers: headers() })]); const ar = await a.json(); const br = await b.json(); if (!a.ok || !b.ok) throw new Error(ar.message || br.message); setContracts(ar.data?.contracts || []); setEmployees(ar.data?.employees || []); setExtensions(br.data || []); } catch (e) { toast.error(getApiErrorMessage(e, "Không thể tải dữ liệu hợp đồng.")); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [companyCode]);
  const contractsByEmployee = useMemo(() => new Map(employees.map((e) => [e._id, contracts.filter((c) => c.employeeId === e._id)])), [employees, contracts]);
  const visibleEmployees = employees.filter((e) => `${e.displayName || ""} ${e.email} ${e.department || ""}`.toLowerCase().includes(search.toLowerCase()));
  const openContract = (contract?: Contract) => { setEditing(contract || "new"); setContractForm(contract ? { contractType: contract.contractType, employeeId: contract.employeeId, startDate: isoDate(contract.startDate), endDate: isoDate(contract.endDate), status: contract.status, contractFileUrl: contract.contractFileUrl || "", signedImageUrl: contract.signedImageUrl || "", note: contract.note || "" } : emptyContract); };
  const saveContract = async () => { setSaving(true); try { const url = editing === "new" ? `/api/v1/hr-contracts${suffix}` : `/api/v1/hr-contracts/${(editing as Contract)._id}${suffix}`; const res = await fetch(url, { method: editing === "new" ? "POST" : "PATCH", headers: headers(), body: JSON.stringify(contractForm) }); const data = await res.json(); if (!res.ok) throw new Error(data.message); toast.success("Đã lưu hợp đồng."); setEditing(null); await load(); } catch (e) { toast.error(getApiErrorMessage(e, "Không thể lưu hợp đồng.")); } finally { setSaving(false); } };
  const openExtension = (contract?: Contract) => { setExtensionForm({ ...emptyExtension, contractId: contract?._id || "", newEndDate: contract ? isoDate(contract.endDate) : "" }); setExtOpen(true); setTab("extensions"); };
  const saveExtension = async () => { setSaving(true); try { const { contractId, ...body } = extensionForm; const res = await fetch(`/api/v1/hr-contracts/${contractId}/extensions${suffix}`, { method: "POST", headers: headers(), body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) throw new Error(data.message); toast.success("Đã gia hạn hợp đồng."); setExtOpen(false); await load(); } catch (e) { toast.error(getApiErrorMessage(e, "Không thể gia hạn hợp đồng.")); } finally { setSaving(false); } };
  return <div className="min-h-0 flex-1 overflow-auto bg-slate-50 p-5 text-left">
    <div className="mx-auto max-w-7xl space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold text-slate-900"><FileSignature className="text-cyan-600"/>Quản lý hợp đồng</h2><p className="text-xs text-slate-500">Theo dõi hợp đồng và lịch sử gia hạn của từng nhân viên.</p></div>{canManage && tab === "contracts" && <button onClick={() => openContract()} className="flex items-center gap-1.5 rounded-xl bg-cyan-600 px-4 py-2 text-xs font-bold text-white"><Plus size={15}/>Tạo hợp đồng</button>}</div>
      <div className="flex gap-1 rounded-xl border bg-white p-1 w-fit"><button onClick={()=>setTab("contracts")} className={`px-4 py-2 rounded-lg text-xs font-bold ${tab==="contracts"?"bg-cyan-600 text-white":"text-slate-600"}`}>Danh sách hợp đồng</button><button onClick={()=>setTab("extensions")} className={`px-4 py-2 rounded-lg text-xs font-bold ${tab==="extensions"?"bg-cyan-600 text-white":"text-slate-600"}`}>Gia hạn hợp đồng</button></div>
      {loading ? <div className="p-12 text-center text-xs text-slate-500">Đang tải hợp đồng...</div> : tab === "contracts" ? <>
        <div className="relative max-w-sm"><Search className="absolute left-3 top-2.5 text-slate-400" size={15}/><input className={input+" pl-9"} placeholder="Tìm nhân viên, email, phòng ban..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3 text-left">Nhân viên</th><th className="p-3 text-left">Loại hợp đồng</th><th className="p-3">Bắt đầu</th><th className="p-3">Hết hạn</th><th className="p-3">Trạng thái</th><th className="p-3">Tài liệu</th><th className="p-3"></th></tr></thead><tbody className="divide-y">{visibleEmployees.flatMap(emp => { const rows=contractsByEmployee.get(emp._id)||[]; if(!rows.length) return [<tr key={emp._id}><td className="p-3"><b>{emp.displayName||emp.email}</b><div className="text-[10px] text-slate-400">{emp.department}</div></td><td colSpan={5} className="p-3 text-amber-600">Nhân viên chưa có hợp đồng</td><td className="p-3">{canManage&&<button onClick={()=>{openContract();setContractForm({...emptyContract,employeeId:emp._id})}} className="text-cyan-700 font-bold">Tạo ngay</button>}</td></tr>]; return rows.map((c,i)=><tr key={c._id}><td className="p-3"><b>{emp.displayName||emp.email}</b>{i===0&&<div className="text-[10px] text-slate-400">{emp.department}</div>}</td><td className="p-3">{c.contractType}</td><td className="p-3 text-center">{date(c.startDate)}</td><td className="p-3 text-center">{date(c.endDate)}</td><td className="p-3 text-center"><span className={`rounded-full px-2 py-1 font-bold ${statusStyle[c.status]}`}>{statusLabel[c.status]}</span></td><td className="p-3 text-center space-x-2">{c.contractFileUrl&&<a className="text-cyan-700" href={c.contractFileUrl} target="_blank" rel="noreferrer">File</a>}{c.signedImageUrl&&<a className="text-cyan-700" href={c.signedImageUrl} target="_blank" rel="noreferrer">Ảnh ký</a>}</td><td className="p-3"><div className="flex gap-2">{canManage&&<><button title="Sửa" onClick={()=>openContract(c)}><Pencil size={14}/></button><button title="Gia hạn" onClick={()=>openExtension(c)}><RefreshCw size={14}/></button></>}</div></td></tr>);})}</tbody></table></div>
      </> : <div className="space-y-3">{canManage&&<button onClick={()=>openExtension()} className="flex items-center gap-1.5 rounded-xl bg-cyan-600 px-4 py-2 text-xs font-bold text-white"><Plus size={15}/>Tạo gia hạn</button>}<div className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3 text-left">Nhân viên</th><th className="p-3">Ngày gia hạn</th><th className="p-3">Hạn cũ</th><th className="p-3">Hạn mới</th><th className="p-3 text-left">Lý do</th><th className="p-3">Tài liệu</th></tr></thead><tbody className="divide-y">{extensions.map(x=><tr key={x._id}><td className="p-3 font-bold">{x.employeeName}</td><td className="p-3 text-center">{date(x.extensionDate)}</td><td className="p-3 text-center">{date(x.previousEndDate)}</td><td className="p-3 text-center font-bold text-emerald-700">{date(x.newEndDate)}</td><td className="p-3">{x.reason||"—"}</td><td className="p-3 text-center space-x-2">{x.extensionFileUrl&&<a href={x.extensionFileUrl} target="_blank" rel="noreferrer" className="text-cyan-700">File</a>}{x.signedImageUrl&&<a href={x.signedImageUrl} target="_blank" rel="noreferrer" className="text-cyan-700">Ảnh ký</a>}</td></tr>)}{!extensions.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-400">Chưa có lịch sử gia hạn hợp đồng.</td></tr>}</tbody></table></div></div>}
    </div>
    {editing&&<Modal title={editing==="new"?"Tạo hợp đồng":"Cập nhật hợp đồng"} close={()=>setEditing(null)} save={saveContract} saving={saving} valid={Boolean(contractForm.employeeId&&contractForm.contractType&&contractForm.startDate&&contractForm.endDate)}><div className="grid grid-cols-2 gap-3"><label className="col-span-2 text-xs">Nhân viên<select className={input} value={contractForm.employeeId} onChange={e=>setContractForm({...contractForm,employeeId:e.target.value})}><option value="">Chọn nhân viên</option>{employees.map(e=><option key={e._id} value={e._id}>{e.displayName||e.email}</option>)}</select></label><label className="col-span-2 text-xs">Loại hợp đồng<input className={input} value={contractForm.contractType} onChange={e=>setContractForm({...contractForm,contractType:e.target.value})}/></label><label className="text-xs">Ngày bắt đầu<input type="date" className={input} value={contractForm.startDate} onChange={e=>setContractForm({...contractForm,startDate:e.target.value})}/></label><label className="text-xs">Ngày hết hạn<input type="date" className={input} value={contractForm.endDate} onChange={e=>setContractForm({...contractForm,endDate:e.target.value})}/></label><label className="text-xs">Trạng thái<select className={input} value={contractForm.status} onChange={e=>setContractForm({...contractForm,status:e.target.value as ContractStatus})}>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-xs">Link file hợp đồng<input className={input} value={contractForm.contractFileUrl} onChange={e=>setContractForm({...contractForm,contractFileUrl:e.target.value})}/></label><label className="col-span-2 text-xs">Link ảnh đã ký<input className={input} value={contractForm.signedImageUrl} onChange={e=>setContractForm({...contractForm,signedImageUrl:e.target.value})}/></label><label className="col-span-2 text-xs">Ghi chú<textarea className={input} value={contractForm.note} onChange={e=>setContractForm({...contractForm,note:e.target.value})}/></label></div></Modal>}
    {extOpen&&<Modal title="Gia hạn hợp đồng" close={()=>setExtOpen(false)} save={saveExtension} saving={saving} valid={Boolean(extensionForm.contractId&&extensionForm.newEndDate&&extensionForm.extensionDate)}><div className="space-y-3"><label className="text-xs">Hợp đồng<select className={input} value={extensionForm.contractId} onChange={e=>setExtensionForm({...extensionForm,contractId:e.target.value})}><option value="">Chọn hợp đồng</option>{contracts.filter(c=>c.status!=="terminated").map(c=><option key={c._id} value={c._id}>{c.employeeName} — {c.contractType} — hạn {date(c.endDate)}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-xs">Ngày gia hạn<input type="date" className={input} value={extensionForm.extensionDate} onChange={e=>setExtensionForm({...extensionForm,extensionDate:e.target.value})}/></label><label className="text-xs">Ngày hết hạn mới<input type="date" className={input} value={extensionForm.newEndDate} onChange={e=>setExtensionForm({...extensionForm,newEndDate:e.target.value})}/></label></div><label className="text-xs">Lý do<textarea className={input} value={extensionForm.reason} onChange={e=>setExtensionForm({...extensionForm,reason:e.target.value})}/></label><label className="text-xs">Link file gia hạn<input className={input} value={extensionForm.extensionFileUrl} onChange={e=>setExtensionForm({...extensionForm,extensionFileUrl:e.target.value})}/></label><label className="text-xs">Link ảnh đã ký<input className={input} value={extensionForm.signedImageUrl} onChange={e=>setExtensionForm({...extensionForm,signedImageUrl:e.target.value})}/></label></div></Modal>}
  </div>;
}

function Modal({title,children,close,save,saving,valid}:{title:string;children:React.ReactNode;close:()=>void;save:()=>void;saving:boolean;valid:boolean}) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-2xl"><h3 className="mb-4 font-bold text-slate-900">{title}</h3>{children}<div className="mt-5 flex justify-end gap-2"><button onClick={close} className="px-4 py-2 text-xs">Hủy</button><button disabled={!valid||saving} onClick={save} className="rounded-xl bg-cyan-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{saving?"Đang lưu...":"Lưu"}</button></div></div></div>; }
