import { useEffect, useState } from "react";
import { CheckCircle2, Lock, Play, RefreshCw } from "lucide-react";
import { payrollService } from "../../services/payrollService";

export default function PayrollTab({ canManage }: { canManage: boolean }) {
  const [period, setPeriod] = useState(() => new Date().toISOString().slice(0, 7));
  const [run, setRun] = useState<any>(null);
  const [results, setResults] = useState<any[]>([]);
  const [message, setMessage] = useState("");
  const reload = async () => { try { setRun(await payrollService.getRun(period)); } catch { setRun(null); } try { setResults(await payrollService.getResults(period)); } catch { setResults([]); } };
  useEffect(() => { void reload(); }, [period]);
  const exportCsv = () => { const rows = run?.lines || results; const csv = ["employeeId,adjustedBase,overtime,net", ...rows.map((line: any) => [line.employeeId, line.calculation?.adjustedBase || "", line.calculation?.overtime || "", line.calculation?.net || ""].join(","))].join("\\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `payroll-${period}.csv`; anchor.click(); URL.revokeObjectURL(url); };
  const action = async (fn: () => Promise<unknown>, success: string) => { try { await fn(); setMessage(success); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể thực hiện thao tác"); } };
  return <section className="flex-1 overflow-auto p-5 space-y-4 bg-slate-50">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-800">Bảng lương</h2><p className="text-xs text-slate-500">Kỳ lương và kết quả công đã khóa</p></div><div className="flex items-center gap-2"><input type="month" value={period} onChange={e => setPeriod(e.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm" /><button title="Tải lại" onClick={() => void reload()} className="rounded-lg border bg-white p-2"><RefreshCw size={16} /></button><button title="Xu?t CSV" onClick={exportCsv} className="rounded-lg border bg-white px-3 py-2 text-sm">CSV</button></div></div>
    {message && <div className="rounded-lg border border-cyan-200 bg-cyan-50 px-3 py-2 text-sm text-cyan-800">{message}</div>}
    <div className="flex flex-wrap gap-2">{canManage && <><button onClick={() => void action(() => payrollService.lock(period), "Đã khóa kết quả công")} className="inline-flex items-center gap-2 rounded-lg bg-slate-700 px-3 py-2 text-sm text-white"><Lock size={15} /> Khóa công</button><button onClick={() => void action(() => payrollService.createRun(period), "Đã tạo bảng lương")} className="inline-flex items-center gap-2 rounded-lg bg-cyan-600 px-3 py-2 text-sm text-white"><Play size={15} /> Tính lương</button><button onClick={() => void action(() => payrollService.approve(period), "Đã duyệt bảng lương")} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-sm text-white"><CheckCircle2 size={15} /> Duyệt</button><button onClick={() => void action(() => payrollService.close(period), "Đã chốt kỳ lương")} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white">Chốt kỳ</button></>}</div>
    <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-3 flex justify-between text-sm"><span>Trạng thái</span><strong>{run?.status || "Chưa tạo"}</strong></div><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="p-2">Nhân viên</th><th className="p-2">Lương điều chỉnh</th><th className="p-2">Tăng ca</th><th className="p-2">Thực nhận</th></tr></thead><tbody>{(run?.lines || results).map((line: any) => <tr key={line.employeeId} className="border-b last:border-0"><td className="p-2">{line.employeeId}</td><td className="p-2">{line.calculation?.adjustedBase ?? "-"}</td><td className="p-2">{line.calculation?.overtime ?? "-"}</td><td className="p-2 font-semibold">{line.calculation?.net ?? "-"}</td></tr>)}</tbody></table></div></div>
  </section>;
}
