import { model, Schema } from "mongoose";
const scope = { companyCode: { type: String, required: true }, branchId: { type: String, required: true } };
const payment = new Schema({ key: { type: String, required: true }, amount: { type: Number, required: true }, at: { type: Date, required: true }, reference: String, actorId: String }, { _id: false });
const debt = new Schema({ ...scope, direction: { type: String, enum: ["receivable", "payable"], required: true }, partyKind: { type: String, enum: ["customer", "dealer", "collaborator", "supplier"], required: true }, partyId: String, partyName: { type: String, required: true }, reference: { type: String, required: true }, sourceReceiptId: String, amount: { type: Number, required: true }, balance: { type: Number, required: true }, occurredOn: { type: String, required: true }, dueOn: { type: String, required: true }, payments: { type: [payment], default: [] }, version: { type: Number, default: 0 }, createdBy: String }, { timestamps: true });
debt.index({ companyCode: 1, branchId: 1, direction: 1, reference: 1 }, { unique: true });
debt.index({ companyCode: 1, sourceReceiptId: 1 }, { unique: true, partialFilterExpression: { sourceReceiptId: { $type: "string" } } });
debt.index({ companyCode: 1, branchId: 1, balance: 1, dueOn: 1 });
export const FinanceDebtModel = model("FinanceTradeDebt", debt);
const invoice = new Schema({ ...scope, direction: { type: String, enum: ["input", "output"], required: true }, invoiceNumber: { type: String, required: true }, series: { type: String, required: true }, partyName: { type: String, required: true }, taxId: { type: String, default: "" }, issuedOn: { type: String, required: true }, taxableAmount: { type: Number, required: true }, vatAmount: { type: Number, required: true }, deductibleVat: { type: Number, default: 0 }, adjustmentOf: String, note: String, createdBy: String }, { timestamps: true });
invoice.index({ companyCode: 1, direction: 1, taxId: 1, series: 1, invoiceNumber: 1 }, { unique: true });
invoice.index({ companyCode: 1, branchId: 1, issuedOn: 1 });
invoice.index({ companyCode: 1, series: 1, invoiceNumber: 1 }, { unique: true, partialFilterExpression: { direction: "output" } });
export const FinanceVatInvoiceModel = model("FinanceVatInvoice", invoice);
const plan = new Schema({ ...scope, salesMix: { type: [{ segment: { type: String, enum: ["phone", "accessory", "repair"], required: true }, weight: Number, price: Number, cost: Number, variable: Number, commission: Number }], default: [] }, month: { type: String, required: true }, rent: { type: Number, default: 0 }, payroll: { type: Number, default: 0 }, otherFixed: { type: Number, default: 0 }, expectedUnitPrice: { type: Number, default: 0 }, expectedUnitCost: { type: Number, default: 0 }, variableCostPerUnit: { type: Number, default: 0 }, expectedCommissionPerUnit: { type: Number, default: 0 }, version: { type: Number, default: 0 }, updatedBy: String }, { timestamps: true });
plan.index({ companyCode: 1, branchId: 1, month: 1 }, { unique: true });
export const FinanceMonthlyPlanModel = model("FinanceMonthlyPlan", plan);
const vatPeriod = new Schema({ ...scope, period: { type: String, required: true }, openingCredit: { type: Number, default: 0 }, version: { type: Number, default: 0 }, updatedBy: String }, { timestamps: true });
vatPeriod.index({ companyCode: 1, branchId: 1, period: 1 }, { unique: true });
export const FinanceVatPeriodModel = model("FinanceVatPeriod", vatPeriod);
