import { model, Schema } from "mongoose";
const scope = { companyCode: { type: String, required: true }, branchId: { type: String, required: true } };
const account = new Schema({ ...scope, name: { type: String, required: true }, kind: { type: String, enum: ["cash", "bank"], required: true }, openingOn: { type: String, required: true }, openingBalance: { type: Number, required: true }, balance: { type: Number, required: true }, version: { type: Number, default: 0 }, createdBy: String }, { timestamps: true });
account.index({ companyCode: 1, branchId: 1, name: 1 }, { unique: true });
export const FinanceCashAccountModel = model("FinanceCashAccount", account);
const voucher = new Schema({ ...scope, key: { type: String, required: true }, kind: { type: String, enum: ["receipt", "payment", "transfer"], required: true }, accountId: { type: String, required: true }, destinationAccountId: String, amount: { type: Number, required: true }, occurredOn: { type: String, required: true }, description: { type: String, required: true }, reference: String, status: { type: String, enum: ["pending", "posted", "rejected"], default: "pending" }, sourceKey: String, sourceType: String, sourceId: String, debtId: String, createdBy: String, approvedBy: String, approvedAt: Date, rejectionReason: String, version: { type: Number, default: 0 } }, { timestamps: true });
voucher.index({ companyCode: 1, branchId: 1, key: 1 }, { unique: true });
voucher.index({ companyCode: 1, branchId: 1, sourceKey: 1 }, { unique: true, partialFilterExpression: { sourceKey: { $type: "string" } } });
voucher.index({ companyCode: 1, branchId: 1, occurredOn: 1, status: 1 });
export const FinanceCashVoucherModel = model("FinanceCashVoucher", voucher);
const reconciliation = new Schema({ ...scope, accountId: { type: String, required: true }, key: { type: String, required: true }, expected: { type: Number, required: true }, actual: { type: Number, required: true }, difference: { type: Number, required: true }, note: { type: String, required: true }, accountVersion: Number, createdBy: String }, { timestamps: true });
reconciliation.index({ companyCode: 1, branchId: 1, key: 1 }, { unique: true });
export const FinanceCashReconciliationModel = model("FinanceCashReconciliation", reconciliation);
const bankLine = new Schema({ ...scope, accountId: { type: String, required: true }, bankKey: { type: String, required: true }, occurredOn: { type: String, required: true }, amount: { type: Number, required: true }, description: String, voucherId: String, matchedBy: String, matchedAt: Date, createdBy: String }, { timestamps: true });
bankLine.index({ companyCode: 1, branchId: 1, accountId: 1, bankKey: 1 }, { unique: true });
bankLine.index({ companyCode: 1, branchId: 1, accountId: 1, voucherId: 1 }, { unique: true, partialFilterExpression: { voucherId: { $type: "string" } } });
export const FinanceBankLineModel = model("FinanceBankLine", bankLine);
const guard = new Schema({ ...scope, revision: { type: Number, default: 0 } });
guard.index({ companyCode: 1, branchId: 1 }, { unique: true });
export const FinancePostingGuardModel = model("FinancePostingGuard", guard);
const period = new Schema({ ...scope, month: { type: String, required: true }, status: { type: String, enum: ["closed", "open"], required: true }, snapshot: Schema.Types.Mixed, fingerprint: String, version: { type: Number, default: 0 }, history: [{ action: String, reason: String, by: String, at: Date, snapshot: Schema.Types.Mixed }], closedAt: Date, closedBy: String }, { timestamps: true });
period.index({ companyCode: 1, branchId: 1, month: 1 }, { unique: true });
export const FinanceClosedPeriodModel = model("FinanceClosedPeriod", period);
