import { Schema, model } from "mongoose";
const scope = { companyCode: { type: String, required: true }, branchId: { type: String, required: true } };
const money = { type: Number, min: 0, required: true, validate: Number.isSafeInteger };
const voucher = new Schema({ reversalOf: String, reversedBy: String, reversalReason: String, ...scope, code: { type: String, required: true }, kind: { type: String, enum: ["receipt", "payment"], required: true }, category: { type: String, required: true }, expenseClass: { type: String, enum: ["fixed", "variable", "none"], default: "none" }, amount: money, date: { type: String, required: true }, counterparty: String, method: { type: String, enum: ["cash", "transfer", "card", "other"], required: true }, note: String, attachment: String, payableId: String, createdBy: String, createdByName: String, idempotencyKey: { type: String, required: true }, fingerprint: { type: String, required: true } }, { timestamps: true });
voucher.index({ companyCode: 1, branchId: 1, idempotencyKey: 1 }, { unique: true });
voucher.index({ companyCode: 1, branchId: 1, date: -1 });
voucher.index({ companyCode: 1, branchId: 1, reversalOf: 1 }, { unique: true, partialFilterExpression: { reversalOf: { $type: "string" } } });
export const FinanceVoucherModel = model("FinanceVoucher", voucher);
const payable = new Schema({ ...scope, payableCode: String, receiptId: { type: String, required: true }, receiptCode: String, supplierId: { type: String, required: true }, supplierName: String, originalAmount: money, openingPaid: money, paidAmount: money, balance: money, dueDate: { type: String, required: true }, note: String, createdBy: String }, { timestamps: true });
payable.index({ companyCode: 1, branchId: 1, receiptId: 1 }, { unique: true });
payable.index({ companyCode: 1, branchId: 1, dueDate: 1 });
payable.index({ companyCode: 1, payableCode: 1 }, { unique: true, partialFilterExpression: { payableCode: { $type: "string" } } });
export const FinancePayableModel = model("FinancePayable", payable);
const followup = new Schema({ ...scope, targetType: { type: String, enum: ["receivable", "payable"], required: true }, targetId: { type: String, required: true }, status: { type: String, enum: ["new", "contacted", "promised", "partial", "done"], required: true }, promiseDate: String, promiseAmount: Number, assignee: String, note: String, updatedBy: String }, { timestamps: true });
followup.index({ companyCode: 1, branchId: 1, targetType: 1, targetId: 1 }, { unique: true });
export const FinanceFollowupModel = model("FinanceFollowup", followup);
const tax = new Schema({ ...scope, direction: { type: String, enum: ["input", "output"], required: true }, invoiceNumber: { type: String, required: true }, taxId: { type: String, required: true }, counterparty: String, date: { type: String, required: true }, base: money, rate: { type: Number, required: true, min: 0, max: 100 }, vat: money, deductible: { type: Boolean, default: false }, sourceOrderId: String, sourceInvoiceId: String, note: String, createdBy: String }, { timestamps: true });
tax.index({ companyCode: 1, branchId: 1, direction: 1, taxId: 1, invoiceNumber: 1 }, { unique: true });
tax.index({ companyCode: 1, branchId: 1, date: 1 });
tax.index({ companyCode: 1, branchId: 1, sourceInvoiceId: 1 }, { unique: true, partialFilterExpression: { sourceInvoiceId: { $type: "string" } } });
export const FinanceTaxModel = model("FinanceTax", tax);
const settings = new Schema({ ...scope, period: { type: String, required: true }, fixedCostBudget: money, vatCarryforward: money, note: String, updatedBy: String }, { timestamps: true });
settings.index({ companyCode: 1, branchId: 1, period: 1 }, { unique: true });
export const FinanceManagementSettingsModel = model("FinanceManagementSettings", settings);
