import React from "react";
import { customerApi } from "../customerApi";
import type { BillingProfileInput } from "../types";
const empty: BillingProfileInput = { legalName: "", taxId: "", address: "", invoiceEmail: "", contactName: "" };
export default function BillingProfilesPanel({ customerId, companyCode, canManage }: { customerId: string; companyCode: string; canManage: boolean }) {
  const [items, setItems] = React.useState<any[]>([]); const [adding, setAdding] = React.useState(false); const [form, setForm] = React.useState(empty); const [message, setMessage] = React.useState("");
  const load = React.useCallback(() => customerApi.billingProfiles(customerId, companyCode).then(setItems), [customerId, companyCode]); React.useEffect(() => { void load(); }, [load]);
  return <section className="mt-6 border-t pt-5"><div className="flex justify-between"><h3 className="font-bold">Thông tin xuất VAT</h3>{canManage && <button type="button" onClick={() => setAdding(!adding)} className="text-sm font-bold text-cyan-700">Thêm hồ sơ VAT</button>}</div>
  <div className="mt-3 space-y-2">{items.map((item) => <div key={item._id} className="rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">{item.legalName}{item.isDefault ? " · Mặc định" : ""}</p><p>MST: {item.taxId}</p><p>{item.address}</p><p>{item.invoiceEmail}</p></div>)}{!items.length && <p className="text-sm text-slate-500">Chưa có hồ sơ xuất VAT.</p>}</div>
  {adding && <form className="mt-3 space-y-2" onSubmit={(event) => { event.preventDefault(); setMessage(""); void customerApi.createBillingProfile(customerId, form, companyCode).then((result) => { setMessage(result.warnings[0]?.message || "Đã thêm hồ sơ VAT."); setForm(empty); setAdding(false); return load(); }).catch((error) => setMessage(error instanceof Error ? error.message : "Không thêm được hồ sơ VAT.")); }}>{(["legalName", "taxId", "address", "invoiceEmail", "contactName"] as const).map((key) => <input key={key} aria-label={key} required={key !== "contactName"} value={form[key] || ""} onChange={(event) => setForm((value) => ({ ...value, [key]: event.target.value }))} placeholder={({ legalName: "Tên pháp nhân", taxId: "Mã số thuế", address: "Địa chỉ hóa đơn", invoiceEmail: "Email nhận hóa đơn", contactName: "Người liên hệ" } as const)[key]} className="w-full rounded-lg border px-3 py-2 text-sm" />)}<button className="rounded-lg bg-cyan-600 px-3 py-2 text-sm font-bold text-white">Lưu hồ sơ VAT</button></form>}{message && <p className="mt-2 text-sm text-amber-700">{message}</p>}</section>;
}
