import { X } from "lucide-react";
import type { Customer } from "../types";

const spend = new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 });
import BillingProfilesPanel from "./BillingProfilesPanel";
import CustomerPurchaseHistoryPanel from "./CustomerPurchaseHistoryPanel";

export default function CustomerDetailDrawer({ customer, branchId, canManage, onClose, onEdit, onToggleStatus }: { customer: Customer; branchId?: string; canManage: boolean; onClose: () => void; onEdit: () => void; onToggleStatus: () => void }) {
  const rows = [["Mã khách", customer.customerCode], ["Điện thoại", customer.phone], ["Email", customer.email || "—"], ["Ngày sinh", customer.dateOfBirth ? new Date(customer.dateOfBirth).toLocaleDateString("vi-VN") : "—"], ["Địa chỉ", customer.address || "—"], ["Hạng", customer.tier ? `${customer.tier.name}${typeof customer.tierTotalSales === "number" ? ` · đã chi tiêu ${spend.format(customer.tierTotalSales)}` : ""}` : "Chưa xếp hạng"], ["Loại khách", customer.type === "vat" ? "Xuất VAT" : "Khách thường"], ["Trạng thái", customer.status === "active" ? "Đang hoạt động" : "Ngừng hoạt động"]];
  return <aside className="fixed inset-y-0 right-0 z-50 w-full max-w-lg overflow-y-auto border-l bg-white p-6 shadow-2xl"><button type="button" aria-label="Đóng chi tiết" onClick={onClose} className="float-right"><X /></button><h2 className="pr-10 text-xl font-bold">{customer.name}</h2><p className="mt-1 text-sm text-slate-500">Hồ sơ dùng chung toàn công ty</p><dl className="mt-6 space-y-3">{rows.map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words font-semibold">{value}</dd></div>)}</dl>{customer.notes && <div className="mt-4 rounded-xl border p-3 text-sm"><p className="font-semibold">Ghi chú</p><p className="mt-1 text-slate-600">{customer.notes}</p></div>}<BillingProfilesPanel customerId={customer._id} companyCode={customer.companyCode} canManage={canManage} /><CustomerPurchaseHistoryPanel customerId={customer._id} companyCode={customer.companyCode} branchId={branchId} />{canManage && <div className="mt-6 flex gap-3"><button type="button" onClick={onEdit} className="rounded-xl bg-cyan-600 px-4 py-2 font-bold text-white">Sửa hồ sơ</button><button type="button" onClick={onToggleStatus} className="rounded-xl border px-4 py-2 font-bold text-slate-700">{customer.status === "active" ? "Ngừng hoạt động" : "Kích hoạt lại"}</button></div>}</aside>;
}
