import { useEffect, useState } from "react";
import { useAuth } from "../../../context/AuthContext";
import { useBranchOptional } from "../../../context/BranchContext";
import { financialReportRequest as request } from "../api/financialReporting.api";
import { Cards, Table, EntryDialog, exportCsv } from "./FinancialReportsPage";
const money = (n: number) => n.toLocaleString("vi-VN") + " ₫";
const today = () => new Date(Date.now() + 7 * 3600000).toISOString().slice(0, 10);
const btn = "rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold hover:bg-slate-50 disabled:opacity-40";
const labels: Record<string, string> = { receipt: "Thu", payment: "Chi", transfer: "Chuyển quỹ", pending: "Chờ duyệt", posted: "Đã ghi sổ", rejected: "Từ chối" };
export default function TreasuryPage({ permissions }: { permissions: readonly string[] }) {
  const { userProfile } = useAuth(); const branch = useBranchOptional();
  const scope = { companyCode: userProfile?.companyCode || "", ...(branch?.activeBranchId ? { branchId: branch.activeBranchId } : {}) };
  const scopeKey = JSON.stringify(scope), manage = permissions.includes("*") || permissions.includes("finance-wallet:manage");
  const [days, setDays] = useState(30), [refresh, setRefresh] = useState(0), [result, setResult] = useState<any>(null), [error, setError] = useState("");
  const [dialog, setDialog] = useState<any>(null), [section, setSection] = useState("accounts");
  useEffect(() => { setDialog(null); }, [scopeKey]);
  useEffect(() => { const controller = new AbortController(); setResult(null); setError(""); request("/treasury", { ...scope, days: String(days) }, "GET", undefined, controller.signal).then(data => { if (!controller.signal.aborted) setResult({ scopeKey, days, data }); }).catch(e => { if (!controller.signal.aborted) setError(e.message); }); return () => controller.abort(); }, [scopeKey, days, refresh]);
  const data = result?.scopeKey === scopeKey && result.days === days ? result.data : null;
  const open = (title: string, path: string, fields: any[], initial: any = {}, note?: string) => setDialog({ title, path, fields, initial, note, scopeKey });
  const options = (rows: any[]) => [{ value: "", label: "Chọn quỹ" }, ...rows.map(a => ({ value: a._id, label: a.name }))];
  const accountField = { key: "accountId", label: "Quỹ / tài khoản", options: options(data?.accounts || []) };
  const voucher = (kind: string, source?: any, debt?: any) => open(source ? "Gán giao dịch vào quỹ" : debt ? "Thanh toán công nợ qua quỹ" : `Lập phiếu ${labels[kind].toLowerCase()}`, "/treasury/vouchers", [accountField, ...(kind === "transfer" ? [{ ...accountField, key: "destinationAccountId", label: "Quỹ nhận" }] : []), ...(!source ? [{ key: "amount", label: "Số tiền (VND)", type: "number", min: 1, max: debt?.balance }, { key: "occurredOn", label: "Ngày ghi sổ", type: "date" }, { key: "description", label: "Nội dung" }] : []), { key: "reference", label: "Tham chiếu", optional: true }], { key: crypto.randomUUID(), kind, amount: source ? Math.abs(source.amount) : debt?.balance || "", occurredOn: source?.occurredOn || today(), description: source?.description || debt?.reference || "", sourceKey: source?.key, debtId: debt?.id }, source ? `${source.description} · ${source.occurredOn} · ${money(source.amount)}. Giao dịch đã phát sinh ở chứng từ nguồn; chỉ ghi thêm vào sổ quỹ, không thu/chi lần nữa.` : "Phiếu chỉ ảnh hưởng số dư và công nợ khi được duyệt. Ghi nhận chi phí tại Báo cáo tài chính riêng để tính lãi lỗ.");
  return <div className="space-y-5 p-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Sổ quỹ & dòng tiền</h2><p className="text-sm text-slate-500">{branch?.activeBranch?.name || "Chi nhánh hiện tại"} · VND · Tiền mặt và ngân hàng</p></div><button className={btn} onClick={() => setRefresh(r => r + 1)}>Tải lại</button></div>
    {error && <p role="alert" className="rounded-2xl bg-rose-50 p-4 text-rose-700">{error}</p>}
    {!data && !error && <p>Đang tải sổ quỹ…</p>}
    {data && <>
      <Cards rows={[["Tổng số dư đã ghi sổ", data.balance], ["Thu dự kiến", data.forecast.reduce((s: number, r: any) => s + r.incoming, 0)], ["Chi công nợ dự kiến", data.forecast.reduce((s: number, r: any) => s + r.outgoing, 0)], ["Dư cuối dự kiến", data.forecast.at(-1)?.projected || 0]]} />
      <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{data.forecastNote}<p className="mt-2">Cần kiểm tra: {data.unassigned.length} giao dịch chưa gán quỹ; {data.unscheduledDebt.length} khoản nợ chưa có hạn; {data.unrecordedReceipts.length} phiếu nhập chưa xác nhận công nợ. Số dư chỉ gồm các quỹ và phiếu đã ghi sổ.</p></div>
      {!!data.sourceChanges?.length && <div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">Chứng từ nguồn đã thay đổi sau khi ghi sổ; cần đối soát và lập phiếu điều chỉnh: {data.sourceChanges.map((r: any) => r.description).join(", ")}. Sổ quỹ không tự xóa giao dịch đã duyệt.</div>}
      <div className="flex flex-wrap gap-2">{[["accounts", "Quỹ & tài khoản"], ["vouchers", "Phiếu thu / chi"], ["sources", "Giao dịch nguồn"], ["forecast", "Dự báo"], ["reconcile", "Đối soát"], ["periods", "Chốt sổ quỹ"]].map(([id, label]) => <button key={id} className={btn + (section === id ? " bg-cyan-50 text-cyan-700" : "")} onClick={() => setSection(id)}>{label}</button>)}</div>
      {section === "accounts" && <><div className="flex flex-wrap gap-2">{manage && <><button className={btn} onClick={() => open("Tạo quỹ / tài khoản", "/treasury/accounts", [{ key: "name", label: "Tên quỹ" }, { key: "kind", label: "Loại", options: [{ value: "cash", label: "Tiền mặt" }, { value: "bank", label: "Ngân hàng" }] }, { key: "openingOn", label: "Ngày số dư đầu kỳ", type: "date" }, { key: "openingBalance", label: "Số dư đầu kỳ (VND)", type: "number", min: 0 }], { kind: "cash", openingOn: today(), openingBalance: 0 }, "Số dư đầu kỳ là số tiền trước các giao dịch của ngày bắt đầu. Chỉ gán các giao dịch từ ngày này để tránh cộng tiền hai lần.")}>Tạo quỹ</button>{["receipt", "payment", "transfer"].map(k => <button key={k} className={btn} onClick={() => voucher(k)}>Lập phiếu {labels[k].toLowerCase()}</button>)}</>}</div><Table headers={["Quỹ", "Loại", "Ngày đầu kỳ", "Số dư đầu kỳ", "Số dư hiện tại"]} rows={data.accounts.map((a: any) => [a.name, a.kind === "cash" ? "Tiền mặt" : "Ngân hàng", a.openingOn, money(a.openingBalance), money(a.balance)])} /></>}
      {section === "vouchers" && <><button className={btn} onClick={() => exportCsv("so-quy", [["Ngày", "Loại", "Nội dung", "Số tiền", "Trạng thái", "Người lập", "Người duyệt"], ...data.vouchers.map((v: any) => [v.occurredOn, labels[v.kind], v.description, v.amount, labels[v.status], v.createdBy, v.approvedBy])])}>Xuất CSV</button><Table headers={["Ngày / tham chiếu", "Nội dung / quỹ", "Số tiền", "Trạng thái", "Thao tác"]} rows={data.vouchers.map((v: any) => [<>{v.occurredOn}<p>{v.reference}</p></>, <>{labels[v.kind]}: {v.description}<p className="text-xs text-slate-500">{data.accounts.find((a: any) => a._id === v.accountId)?.name}{v.destinationAccountId && " → " + data.accounts.find((a: any) => a._id === v.destinationAccountId)?.name}</p><details><summary>Lịch sử & nguồn</summary><p>Người lập: {v.createdBy} · Người duyệt: {v.approvedBy || "—"}</p><p>{v.approvedAt} {v.sourceType} {v.sourceId} {v.rejectionReason}</p></details></>, money(v.amount), labels[v.status], manage && v.status === "pending" && <div className="flex gap-2"><button className={btn} onClick={() => open("Duyệt ghi sổ", `/treasury/vouchers/${v._id}/decision`, [], { action: "approve", version: v.version }, `${v.description} · ${money(v.amount)}. Duyệt sẽ cập nhật số dư quỹ và công nợ liên quan.`)}>Duyệt</button><button className={btn} onClick={() => open("Từ chối phiếu", `/treasury/vouchers/${v._id}/decision`, [{ key: "reason", label: "Lý do" }], { action: "reject", version: v.version })}>Từ chối</button></div>])} /><h3 className="font-bold">Công nợ có thể thanh toán qua quỹ</h3><Table headers={["Chứng từ", "Đối tượng", "Dư nợ", "Thao tác"]} rows={data.debts.filter((d: any) => d.source === "manual").map((d: any) => [d.reference, d.partyName, money(d.balance), manage && <button className={btn} onClick={() => voucher(d.direction === "payable" ? "payment" : "receipt", undefined, d)}>Lập phiếu thanh toán</button>])} /></>}
      {section === "sources" && <Table headers={["Ngày", "Nguồn", "Phương thức", "Tiền vào / ra", "Thao tác"]} rows={data.unassigned.map((s: any) => [s.occurredOn, s.description, s.method || "Chưa xác định", money(s.amount), manage && (data.accounts.some((a: any) => a.openingOn <= s.occurredOn) ? <button className={btn} onClick={() => voucher(s.amount > 0 ? "receipt" : "payment", s)}>Gán quỹ</button> : "Trước ngày mở quỹ hoặc chưa có quỹ; kiểm tra số dư đầu kỳ")])} />}
      {section === "forecast" && <><label>Số ngày dự báo <select className={btn} value={days} onChange={e => setDays(Number(e.target.value))}>{[7, 14, 30].map(n => <option key={n} value={n}>{n} ngày</option>)}</select></label><Table headers={["Ngày", "Thu theo hạn nợ", "Chi theo hạn nợ", "Dư dự kiến", "Dư nếu chưa thu được nợ", "Chứng từ"]} rows={data.forecast.map((r: any) => [r.date, money(r.incoming), money(r.outgoing), <span className={r.projected < 0 ? "font-bold text-rose-600" : ""}>{money(r.projected)}</span>, money(r.conservative), r.references.join(", ")])} /></>}
      {section === "reconcile" && <>{manage && <div className="flex flex-wrap gap-2">{data.accounts.map((a: any) => <button key={a._id} className={btn} onClick={() => open(`Đối soát ${a.name}`, "/treasury/reconciliations", [{ key: "actual", label: "Số tiền thực tế (VND)", type: "number", min: 0 }, { key: "note", label: "Căn cứ / ghi chú" }], { key: crypto.randomUUID(), accountId: a._id, version: a.version, actual: a.balance }, "Chênh lệch được lưu lại để xử lý; không tự sửa số dư sổ quỹ.")}>Kiểm kê {a.name}</button>)}<button className={btn} onClick={() => open("Ghi dòng sao kê ngân hàng", "/treasury/bank-lines", [{ ...accountField, options: options(data.accounts.filter((a: any) => a.kind === "bank")) }, { key: "bankKey", label: "Mã giao dịch ngân hàng" }, { key: "occurredOn", label: "Ngày ngân hàng", type: "date" }, { key: "amount", label: "Số tiền có dấu (+ thu / − chi)", type: "number" }, { key: "description", label: "Diễn giải" }], { occurredOn: today() })}>Thêm dòng sao kê</button></div>}<Table headers={["Ngày", "Quỹ", "Sổ sách", "Thực tế", "Chênh lệch", "Căn cứ / người ghi"]} rows={data.reconciliations.map((r: any) => [new Date(r.createdAt).toLocaleString("vi-VN"), data.accounts.find((a: any) => a._id === r.accountId)?.name, money(r.expected), money(r.actual), money(r.difference), `${r.note} · ${r.createdBy}`])} /><h3 className="font-bold">Đối chiếu sao kê</h3><Table headers={["Ngày / mã", "Diễn giải", "Số tiền", "Kết quả"]} rows={data.bankLines.map((l: any) => [l.occurredOn + " · " + l.bankKey, l.description, money(l.amount), l.voucherId ? "Đã khớp · " + l.voucherId : manage && <button className={btn} onClick={() => open("Ghép sao kê với phiếu", `/treasury/bank-lines/${l._id}/match`, [{ key: "voucherId", label: "Phiếu đã ghi sổ", options: [{ value: "", label: "Chọn phiếu" }, ...data.vouchers.filter((v: any) => v.status === "posted" && (v.accountId === l.accountId ? (v.kind === "receipt" ? v.amount : -v.amount) === l.amount : v.kind === "transfer" && v.destinationAccountId === l.accountId && v.amount === l.amount)).map((v: any) => ({ value: v._id, label: `${v.occurredOn} · ${v.description} · ${money(v.amount)}` }))] }], {}, "Chọn đúng giao dịch theo mã tham chiếu và ngày; hệ thống kiểm tra số tiền và tài khoản.")}>Ghép phiếu</button>])} /></>}
      {section === "periods" && <><p className="text-sm text-slate-600">Chốt khóa ghi sổ thu/chi từ đầu kỳ trở về trước để giữ nguyên số dư đã chốt. Không khóa bán hàng, kho hoặc báo cáo lãi lỗ. Mở lại kỳ cần lưu lý do.</p>{manage && <button className={btn} onClick={() => open("Chốt sổ quỹ tháng", "/treasury/periods", [{ key: "month", label: "Tháng", type: "month" }, { key: "reason", label: "Căn cứ chốt sổ" }], { month: today().slice(0, 7), version: 0, action: "close" }, "Các phiếu trong kỳ phải được xử lý trước khi chốt. Số dư chốt được lưu cùng lịch sử.")}>Chốt tháng mới</button>}<Table headers={["Tháng", "Trạng thái", "Lịch sử", "Thao tác"]} rows={data.periods.map((p: any) => [p.month, p.status === "closed" ? "Đã chốt" : "Đã mở lại", <details><summary>Xem lịch sử & số dư</summary>{p.history.map((h: any, i: number) => <div key={i}>{h.at} · {h.by} · {h.action === "close" ? "Chốt" : "Mở lại"}: {h.reason}{h.snapshot?.map((a: any) => <p key={a.accountId}>{a.name}: {money(a.balance)}</p>)}</div>)}</details>, manage && <button className={btn} onClick={() => open(p.status === "closed" ? "Mở lại kỳ" : "Chốt lại kỳ", "/treasury/periods", [{ key: "reason", label: "Lý do" }], { month: p.month, version: p.version, action: p.status === "closed" ? "reopen" : "close" })}>{p.status === "closed" ? "Mở lại" : "Chốt lại"}</button>])} /></>}
    </>}
    {dialog?.scopeKey === scopeKey && <EntryDialog {...dialog} onClose={() => setDialog(null)} onSave={async value => { await request(dialog.path, scope, "POST", value); setDialog(null); setRefresh(r => r + 1); }} />}
  </div>;
}
