import React from "react";
import { inventoryCountService, type InventoryCount } from "../../services/inventoryCountService";
import { toast } from "../../pages/Toast";
import { BarcodeInput } from "./BarcodeInput";
import BarcodeScannerDialog from "../../modules/retail/components/pos/BarcodeScannerDialog";
export function InventoryCountingSection({ warehouseId }: { warehouseId: string }) {
  const [count, setCount] = React.useState<InventoryCount | null>(null);
  const [camera, setCamera] = React.useState(false);
  const create = async () => { try { setCount(await inventoryCountService.create(warehouseId)); } catch (error: any) { toast.error(error?.message || "Không thể tạo phiếu kiểm kê."); } };
  const scan = async (barcode: string) => { if (!count) return; const item = count.items.find((entry) => entry.barcode === barcode); if (!item) { toast.error("Không tìm thấy SKU tương ứng với mã vạch."); return; } try { setCount(await inventoryCountService.updateItem(count._id, item._id, item.countedQuantity + 1)); } catch (error: any) { toast.error(error?.message || "Không thể cập nhật số đếm."); } };
  const update = async (action: "start" | "submit" | "approve") => { if (!count) return; try { setCount(await inventoryCountService[action](count._id)); } catch (error: any) { toast.error(error?.message || "Không thể cập nhật phiếu kiểm kê."); } };
  return <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4" aria-label="Kiểm kê kho"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Kiểm kê bằng mã vạch</h3><p className="text-sm text-slate-500">Dùng camera điện thoại hoặc đầu đọc USB/Bluetooth.</p></div><button type="button" disabled={!warehouseId} onClick={() => void create()} className="rounded-md bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Tạo phiếu</button></div>{count && <><p className="text-sm">Phiếu <strong>{count.countCode}</strong> · {count.status}</p><BarcodeInput onScan={(value) => void scan(value)} onCameraRequest={() => setCamera(true)} disabled={count.status !== "draft" && count.status !== "counting"} /><div className="flex gap-2">{count.status === "draft" && <button type="button" onClick={() => void update("start")} className="rounded border px-3 py-1 text-sm">Bắt đầu đếm</button>}{count.status === "counting" && <button type="button" onClick={() => void update("submit")} className="rounded bg-amber-600 px-3 py-1 text-sm text-white">Gửi duyệt</button>}{count.status === "pending_approval" && <button type="button" onClick={() => void update("approve")} className="rounded bg-blue-600 px-3 py-1 text-sm text-white">Duyệt điều chỉnh</button>}</div><div className="max-h-80 overflow-auto rounded-md border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-2">SKU</th><th className="p-2">Mã vạch</th><th className="p-2 text-right">Hệ thống</th><th className="p-2 text-right">Đã đếm</th></tr></thead><tbody>{count.items.map((item) => <tr key={item._id} className="border-t"><td className="p-2 font-mono">{item.sku}</td><td className="p-2">{item.barcode || "—"}</td><td className="p-2 text-right">{item.systemQuantity}</td><td className="p-2 text-right font-semibold">{item.countedQuantity}</td></tr>)}</tbody></table></div></>}{camera && <BarcodeScannerDialog onScan={(value) => { setCamera(false); void scan(value); }} onClose={() => setCamera(false)} />}</section>;
}
