import React, { useEffect, useMemo, useState } from "react";
import { Boxes, ChevronDown, ChevronRight, ImageIcon, RefreshCw, ArrowUpRight } from "lucide-react";
import { inventoryReceivingService, type InventoryBalance, type Warehouse } from "../../services/inventoryReceivingService";
import { toast } from "../../pages/Toast";
import { StockAlertPanel } from "./StockAlertPanel";
import { InventoryCountingSection } from "./InventoryCountingSection";
import { WarehouseSerialDetailModal } from "./WarehouseSerialDetailModal";

const number = (value: number) => Number(value || 0).toLocaleString("vi-VN");
type ProductBalanceGroup = { productId: string; productName: string; productMediaUrl?: string; items: InventoryBalance[]; quantity: number; value: number };

export function WarehouseSection({ onCreateOutbound }: { onCreateOutbound?: (warehouseId: string, sku: string) => void }) {
  const [warehouses, setWarehouses] = useState<Warehouse[]>([]);
  const [balances, setBalances] = useState<InventoryBalance[]>([]);
  const [warehouseId, setWarehouseId] = useState("");
  const [loading, setLoading] = useState(true);
  const [expandedProductIds, setExpandedProductIds] = useState<string[]>([]);
  const [page, setPage] = useState(1);
  const pageSize = 10;
  const load = async () => {
    setLoading(true);
    try {
      const nextWarehouses = await inventoryReceivingService.listWarehouses();
      setWarehouses(nextWarehouses);
      const selected = warehouseId && nextWarehouses.some((item) => item._id === warehouseId) ? warehouseId : nextWarehouses[0]?._id || "";
      setWarehouseId(selected); setBalances(await inventoryReceivingService.listBalances(selected));
    } catch (error: any) { toast.error(error?.message || "KhÃƒÆ’Ã‚Â´ng thÃƒÂ¡Ã‚Â»Ã†â€™ tÃƒÂ¡Ã‚ÂºÃ‚Â£i sÃƒÂ¡Ã‚Â»Ã¢â‚¬Ëœ dÃƒâ€ Ã‚Â° kho."); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (warehouseId) void inventoryReceivingService.listBalances(warehouseId).then(setBalances).catch(() => undefined); }, [warehouseId]);
  const groups = useMemo<ProductBalanceGroup[]>(() => Object.values(balances.reduce<Record<string, ProductBalanceGroup>>((all, item) => {
    const group = all[item.productId] || { productId: item.productId, productName: item.productName || "SÃƒÂ¡Ã‚ÂºÃ‚Â£n phÃƒÂ¡Ã‚ÂºÃ‚Â©m khÃƒÆ’Ã‚Â´ng xÃƒÆ’Ã‚Â¡c Ãƒâ€žÃ¢â‚¬ËœÃƒÂ¡Ã‚Â»Ã¢â‚¬Â¹nh", productMediaUrl: item.productMediaUrl, items: [], quantity: 0, value: 0 };
    group.items.push(item); group.quantity += item.quantity; group.value += item.quantity * item.averageCost; all[item.productId] = group; return all;
  }, {})), [balances]);
  const totalPages = Math.max(1, Math.ceil(groups.length / pageSize));
  const currentPage = Math.min(page, totalPages);
  const pageGroups = groups.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const toggle = (id: string) => setExpandedProductIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const warehouseName = (id: string) => warehouses.find((warehouse) => warehouse._id === id)?.name || id;

  return <section className="space-y-5" aria-label="Kho hÃƒÆ’Ã‚Â ng vÃƒÆ’Ã‚Â  sÃƒÂ¡Ã‚Â»Ã¢â‚¬Ëœ dÃƒâ€ Ã‚Â°">
    <div className="flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="text-base font-semibold text-slate-900">Kho hÃƒÆ’Ã‚Â ng vÃƒÆ’Ã‚Â  sÃƒÂ¡Ã‚Â»Ã¢â‚¬Ëœ dÃƒâ€ Ã‚Â°</h3><p className="mt-1 text-sm text-slate-500">Xem tÃƒÂ¡Ã‚Â»Ã¢â‚¬Å“n theo sÃƒÂ¡Ã‚ÂºÃ‚Â£n phÃƒÂ¡Ã‚ÂºÃ‚Â©m, mÃƒÂ¡Ã‚Â»Ã…Â¸ rÃƒÂ¡Ã‚Â»Ã¢â€žÂ¢ng tÃƒÂ¡Ã‚Â»Ã‚Â«ng dÃƒÆ’Ã‚Â²ng Ãƒâ€žÃ¢â‚¬ËœÃƒÂ¡Ã‚Â»Ã†â€™ xem cÃƒÆ’Ã‚Â¡c SKU/biÃƒÂ¡Ã‚ÂºÃ‚Â¿n thÃƒÂ¡Ã‚Â»Ã†â€™.</p></div><div className="flex gap-2"><select value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)} className="rounded-md border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">ChÃƒÂ¡Ã‚Â»Ã‚Ân kho</option>{warehouses.map((item) => <option key={item._id} value={item._id}>{item.name}{item.isDefault ? " (mÃƒÂ¡Ã‚ÂºÃ‚Â·c Ãƒâ€žÃ¢â‚¬ËœÃƒÂ¡Ã‚Â»Ã¢â‚¬Â¹nh)" : ""}</option>)}</select><button type="button" onClick={() => void load()} className="inline-flex h-9 w-9 items-center justify-center rounded-md border border-slate-200 text-slate-600 hover:bg-slate-50" title="LÃƒÆ’Ã‚Â m mÃƒÂ¡Ã‚Â»Ã¢â‚¬Âºi"><RefreshCw className="h-4 w-4" /></button></div></div>
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="SÃƒÂ¡Ã‚Â»Ã¢â‚¬Ëœ kho" value={warehouses.length} /><Stat label="SÃƒÂ¡Ã‚ÂºÃ‚Â£n phÃƒÂ¡Ã‚ÂºÃ‚Â©m trong kho" value={groups.length} /><Stat label="TÃƒÂ¡Ã‚Â»Ã¢â‚¬Â¢ng sÃƒÂ¡Ã‚Â»Ã¢â‚¬Ëœ lÃƒâ€ Ã‚Â°ÃƒÂ¡Ã‚Â»Ã‚Â£ng" value={number(balances.reduce((sum, item) => sum + item.quantity, 0))} /></div>
    <StockAlertPanel balances={balances} onSave={async (balance, minStock, maxStock) => { try { await inventoryReceivingService.updateBalanceThresholds(balance._id, { minStock, maxStock }); setBalances((current) => current.map((item) => item._id === balance._id ? { ...item, minStock, ...(maxStock === undefined ? { maxStock: undefined } : { maxStock }) } : item)); toast.success("Ãƒâ€žÃ‚ÂÃƒÆ’Ã‚Â£ cÃƒÂ¡Ã‚ÂºÃ‚Â­p nhÃƒÂ¡Ã‚ÂºÃ‚Â­t ngÃƒâ€ Ã‚Â°ÃƒÂ¡Ã‚Â»Ã‚Â¡ng tÃƒÂ¡Ã‚Â»Ã¢â‚¬Å“n kho."); } catch (error: any) { toast.error(error?.message || "KhÃƒÆ’Ã‚Â´ng thÃƒÂ¡Ã‚Â»Ã†â€™ cÃƒÂ¡Ã‚ÂºÃ‚Â­p nhÃƒÂ¡Ã‚ÂºÃ‚Â­t ngÃƒâ€ Ã‚Â°ÃƒÂ¡Ã‚Â»Ã‚Â¡ng tÃƒÂ¡Ã‚Â»Ã¢â‚¬Å“n kho."); throw error; } }} />
    <InventoryCountingSection warehouseId={warehouseId} />
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="w-[40%] px-4 py-3.5 font-medium">SÃƒÂ¡Ã‚ÂºÃ‚Â£n phÃƒÂ¡Ã‚ÂºÃ‚Â©m</th><th className="px-4 py-3.5 font-medium">Kho</th><th className="px-4 py-3.5 text-right font-medium">SÃƒÂ¡Ã‚Â»Ã¢â‚¬Ëœ lÃƒâ€ Ã‚Â°ÃƒÂ¡Ã‚Â»Ã‚Â£ng tÃƒÂ¡Ã‚Â»Ã¢â‚¬Å“n</th><th className="px-4 py-3.5 text-right font-medium">GiÃƒÆ’Ã‚Â¡ vÃƒÂ¡Ã‚Â»Ã¢â‚¬Ëœn bÃƒÆ’Ã‚Â¬nh quÃƒÆ’Ã‚Â¢n</th><th className="px-4 py-3.5 text-right font-medium">TÃƒÂ¡Ã‚Â»Ã¢â‚¬Â¢ng giÃƒÆ’Ã‚Â¡ trÃƒÂ¡Ã‚Â»Ã¢â‚¬Â¹</th><th className="px-4 py-3.5 text-right font-medium">Thao tÃƒÆ’Ã‚Â¡c</th></tr></thead><tbody className="divide-y divide-slate-200">{loading ? <tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">Ãƒâ€žÃ‚Âang tÃƒÂ¡Ã‚ÂºÃ‚Â£i sÃƒÂ¡Ã‚Â»Ã¢â‚¬Ëœ dÃƒâ€ Ã‚Â°...</td></tr> : groups.length === 0 ? <tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500"><Boxes className="mx-auto mb-2 h-7 w-7 text-slate-300" />ChÃƒâ€ Ã‚Â°a cÃƒÆ’Ã‚Â³ sÃƒÂ¡Ã‚Â»Ã¢â‚¬Ëœ dÃƒâ€ Ã‚Â° Ãƒâ€žÃ¢â‚¬ËœÃƒâ€ Ã‚Â°ÃƒÂ¡Ã‚Â»Ã‚Â£c chuyÃƒÂ¡Ã‚Â»Ã†â€™n Ãƒâ€žÃ¢â‚¬ËœÃƒÂ¡Ã‚Â»Ã¢â‚¬Â¢i hoÃƒÂ¡Ã‚ÂºÃ‚Â·c phÃƒÆ’Ã‚Â¡t sinh.</td></tr> : pageGroups.map((group) => <ProductRows key={group.productId} group={group} expanded={expandedProductIds.includes(group.productId)} onToggle={toggle} warehouseName={warehouseName} onCreateOutbound={onCreateOutbound} />)}</tbody></table></div>{groups.length > pageSize && <div className="flex items-center justify-between border-t border-slate-200 px-4 py-3"><span className="text-xs text-slate-500">HiÃƒÂ¡Ã‚Â»Ã†â€™n thÃƒÂ¡Ã‚Â»Ã¢â‚¬Â¹ {(currentPage - 1) * pageSize + 1}-{Math.min(currentPage * pageSize, groups.length)} / {groups.length} sÃƒÂ¡Ã‚ÂºÃ‚Â£n phÃƒÂ¡Ã‚ÂºÃ‚Â©m</span><div className="flex items-center gap-2"><button type="button" onClick={() => setPage((current) => Math.max(1, current - 1))} disabled={currentPage === 1} className="rounded-md border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40">TrÃƒâ€ Ã‚Â°ÃƒÂ¡Ã‚Â»Ã¢â‚¬Âºc</button><span className="text-xs text-slate-600">Trang {currentPage}/{totalPages}</span><button type="button" onClick={() => setPage((current) => Math.min(totalPages, current + 1))} disabled={currentPage === totalPages} className="rounded-md border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40">Sau</button></div></div>}</div>
  </section>;
}

function Stat({ label, value }: { label: string; value: React.ReactNode }) { return <div className="border border-slate-200 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold text-slate-900">{value}</p></div>; }
function ProductRows({ group, expanded, onToggle, warehouseName, onCreateOutbound }: { group: ProductBalanceGroup; expanded: boolean; onToggle: (id: string) => void; warehouseName: (id: string) => string; onCreateOutbound?: (warehouseId: string, sku: string) => void }) {
  const averageCost = group.quantity ? group.value / group.quantity : 0;
  const [detailBalance, setDetailBalance] = useState<InventoryBalance | null>(null);
  return <React.Fragment><tr className="hover:bg-slate-50"><td className="px-4 py-3.5"><button type="button" onClick={() => onToggle(group.productId)} className="flex w-full items-center gap-3 text-left"><span className="text-slate-500">{expanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}</span><Thumbnail url={group.productMediaUrl} label={group.productName} large /><span><span className="block font-semibold text-slate-900">{group.productName}</span><span className="mt-0.5 block text-xs text-slate-500">{group.items.length} SKU / biÃƒÂ¡Ã‚ÂºÃ‚Â¿n thÃƒÂ¡Ã‚Â»Ã†â€™</span></span></button></td><td className="px-4 py-3.5 text-slate-600">{warehouseName(group.items[0].warehouseId)}</td><td className="px-4 py-3.5 text-right font-semibold tabular-nums text-emerald-700">{number(group.quantity)}</td><td className="px-4 py-3.5 text-right tabular-nums text-slate-600">{number(averageCost)}</td><td className="px-4 py-3.5 text-right font-semibold tabular-nums text-slate-900">{number(group.value)}</td><td /></tr>{expanded && group.items.map((item) => <tr key={item._id} className="bg-slate-50/60"><td className="py-2.5 pl-12 pr-4"><div className="flex items-center gap-3"><Thumbnail url={item.variantMediaUrl} label={item.sku} /><span><span className="block font-mono text-xs font-semibold text-slate-700">{item.sku}</span><span className="block text-xs text-slate-500">{item.variantName || "BiÃƒÂ¡Ã‚ÂºÃ‚Â¿n thÃƒÂ¡Ã‚Â»Ã†â€™ mÃƒÂ¡Ã‚ÂºÃ‚Â·c Ãƒâ€žÃ¢â‚¬ËœÃƒÂ¡Ã‚Â»Ã¢â‚¬Â¹nh"}</span></span></div></td><td className="px-4 py-2.5 text-xs text-slate-500">SKU / biÃƒÂ¡Ã‚ÂºÃ‚Â¿n thÃƒÂ¡Ã‚Â»Ã†â€™</td><td className="px-4 py-2.5 text-right font-medium tabular-nums text-emerald-700">{number(item.quantity)}</td><td className="px-4 py-2.5 text-right tabular-nums text-slate-600">{number(item.averageCost)}</td><td className="px-4 py-2.5 text-right font-medium tabular-nums text-slate-800">{number(item.quantity * item.averageCost)}</td><td className="px-4 py-2.5 text-right"><button type="button" onClick={() => setDetailBalance(item)} className="mr-2 rounded-md border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-100">Xem IMEI/serial</button>{item.quantity > item.reservedQuantity && <button type="button" onClick={() => onCreateOutbound?.(item.warehouseId, item.sku)} className="inline-flex items-center gap-1 rounded-md border border-rose-200 bg-white px-2.5 py-1.5 text-xs font-semibold text-rose-700 hover:bg-rose-50"><ArrowUpRight className="h-3.5 w-3.5" />XuÃƒÂ¡Ã‚ÂºÃ‚Â¥t hÃƒÆ’Ã‚Â ng</button>}</td></tr>)}{detailBalance && <WarehouseSerialDetailModal balance={detailBalance} onClose={() => setDetailBalance(null)} />}</React.Fragment>;
}
function Thumbnail({ url, label, large = false }: { url?: string; label: string; large?: boolean }) { return <span className={`flex shrink-0 items-center justify-center overflow-hidden rounded-md border border-slate-200 bg-slate-50 ${large ? "h-11 w-11" : "h-9 w-9"}`}>{url ? <img src={url} alt={label} className="h-full w-full object-cover" /> : <ImageIcon className="h-4 w-4 text-slate-300" />}</span>; }
