import React from "react";
import { Plus, Trash2, X } from "lucide-react";
import { buildPaymentSummary } from "../../hooks/retailPayment";
import type { RetailPaymentInput } from "../../types";
import ClearPaymentDialog from "./ClearPaymentDialog";
import { getApiErrorMessage } from "../../../../utils/errorMessage";
const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value) + " ₫";
type Props = { total: number; busy: boolean; customerId?: string; onClose: () => void; onSubmit: (payments: RetailPaymentInput[], dueDate?: string) => Promise<void> };
function LegacyPaymentDialog({ total, busy, customerId, onClose, onSubmit }: Props) {
  const [payments, setPayments] = React.useState<RetailPaymentInput[]>([{ method: "cash", amount: total, tenderedAmount: total }]); const [dueDate, setDueDate] = React.useState(""); const [error, setError] = React.useState("");
  const summary = React.useMemo(() => { try { return buildPaymentSummary(total, payments.filter((x) => x.amount > 0), { mode: "full", customerId, dueDate }); } catch { return null; } }, [total, payments, customerId, dueDate]);
  const update = (index: number, patch: Partial<RetailPaymentInput>) => setPayments((rows) => rows.map((row, i) => i === index ? { ...row, ...patch } : row));
  const add = () => setPayments((rows) => [...rows, { method: "transfer", amount: Math.max(0, total - rows.reduce((sum, row) => sum + row.amount, 0)) }]);
  const submit = async () => { try { buildPaymentSummary(total, payments.filter((x) => x.amount > 0), { mode: "full", customerId, dueDate }); setError(""); await onSubmit(payments.filter((x) => x.amount > 0), dueDate || undefined); } catch (e) { setError(getApiErrorMessage(e, "Thanh toán không hợp lệ.")); } };
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 sm:items-center sm:p-4"><div role="dialog" aria-label="Thanh toán" className="max-h-[95vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-5 sm:rounded-3xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Thanh toán</h2><p className="text-sm text-slate-500">Cần thu {money(total)}</p></div><button onClick={onClose}><X /></button></div><div className="mt-4 space-y-3">{payments.map((payment, index) => <div key={index} className="grid gap-2 rounded-2xl border p-3 sm:grid-cols-[150px_1fr_1fr_auto]"><select aria-label={`Phương thức ${index + 1}`} className="rounded-xl border px-3 py-2" value={payment.method} onChange={(e) => { const method = e.target.value as RetailPaymentInput["method"]; update(index, { method, tenderedAmount: method === "cash" ? payment.amount : undefined }); }}><option value="cash">Tiền mặt</option><option value="card">Thẻ</option><option value="transfer">Chuyển khoản</option><option value="ewallet">Ví điện tử</option></select><input aria-label={`Số tiền ${index + 1}`} type="number" min="0" className="rounded-xl border px-3 py-2" value={payment.amount} onChange={(e) => update(index, { amount: Number(e.target.value) })} />{payment.method === "cash" ? <input aria-label={`Tiền khách đưa ${index + 1}`} type="number" min="0" className="rounded-xl border px-3 py-2" value={payment.tenderedAmount ?? payment.amount} onChange={(e) => update(index, { tenderedAmount: Number(e.target.value) })} /> : <input aria-label={`Mã tham chiếu ${index + 1}`} className="rounded-xl border px-3 py-2" placeholder="Mã tham chiếu" value={payment.reference || ""} onChange={(e) => update(index, { reference: e.target.value })} />}<button aria-label={`Xóa phương thức ${index + 1}`} disabled={payments.length === 1} onClick={() => setPayments((rows) => rows.filter((_, i) => i !== index))}><Trash2 className="h-4 w-4" /></button></div>)}</div><button className="mt-3 flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold" onClick={add}><Plus className="h-4 w-4" />Thêm phương thức</button><div className="mt-4 grid grid-cols-3 gap-2 text-sm"><Metric label="Đã nhập" value={summary?.collected} /><Metric label="Còn nợ" value={summary?.due} /><Metric label="Tiền thừa" value={summary?.change} /></div>{summary && summary.due > 0 && <div className="mt-4">{!customerId && <p className="mb-2 text-sm text-amber-700">Hãy chọn khách hàng trên giỏ hàng để bán nợ.</p>}<input aria-label="Hạn thanh toán" type="date" className="w-full rounded-xl border px-3 py-2" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></div>}{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={busy} className="mt-5 w-full rounded-xl bg-cyan-600 py-3 font-bold text-white disabled:opacity-50" onClick={() => void submit()}>Xác nhận thanh toán</button></div></div>;
}
function Metric({ label, value = 0 }: { label: string; value?: number }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-slate-500">{label}</p><p className="font-bold">{money(value)}</p></div>; }
export default ClearPaymentDialog;
