import React from "react";
import type { RetailInvoice } from "../../types";
import { invoicePaymentRows } from "./invoicePaymentDisplay";

const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value) + " ₫";
export default function ReceiptPrintView({ invoice }: { invoice: RetailInvoice }) {
  const snapshot = invoice.snapshot;
  return <article id="retail-receipt" className="mx-auto w-full max-w-sm bg-white p-4 text-sm text-slate-900"><style>{`@media print { body * { visibility: hidden !important; } #retail-receipt, #retail-receipt * { visibility: visible !important; } #retail-receipt { position: absolute; left: 0; top: 0; width: 80mm; padding: 4mm; } }`}</style><header className="border-b border-dashed pb-3 text-center">{snapshot.store && <><p className="text-base font-bold">{snapshot.store.storeName}</p><p>{snapshot.store.legalName}</p><p>{snapshot.store.branchName} · {snapshot.store.branchCode}</p></>}<h2 className="mt-2 text-lg font-bold">HÓA ĐƠN BÁN HÀNG</h2><p className="font-semibold">{invoice.invoiceNo}</p><p>{new Date(invoice.issuedAt).toLocaleString("vi-VN")}</p></header><p className="my-3">Khách hàng: {snapshot.customerName}</p><table className="w-full border-y border-dashed text-left"><thead><tr><th className="py-2">Sản phẩm</th><th>SL</th><th className="text-right">Thành tiền</th></tr></thead><tbody>{snapshot.items.map((item, index) => <tr key={`${item.productId}-${index}`}><td className="py-1"><p>{item.productName}</p>{item.serialNumbers?.length ? <p className="text-xs font-semibold text-slate-600">IMEI: {item.serialNumbers.join(", ")}</p> : null}<p className="text-xs text-slate-500">{money(item.unitPrice)}</p></td><td>{item.quantity}</td><td className="text-right">{money(item.lineTotal)}</td></tr>)}</tbody></table><div className="space-y-1 py-3"><Row label="Tạm tính" value={snapshot.subtotal} /><Row label="Giảm giá" value={-snapshot.orderDiscount} /><Row label={`Thuế (${snapshot.taxRate}%)`} value={snapshot.taxAmount} /><Row label="Tổng cộng" value={snapshot.grandTotal} strong /></div><div className="border-t border-dashed pt-2">{invoicePaymentRows(snapshot).map((row, index) => <Row key={`${row.label}-${index}`} label={row.label} value={row.amount} />)}</div></article>;
}
function Row({ label, value, strong = false }: { label: string; value: number; strong?: boolean }) { return <div className={`flex justify-between ${strong ? "font-bold" : ""}`}><span>{label}</span><span>{money(value)}</span></div>; }
