import type { Response } from "express";import type { AuthenticatedRequest } from "../middleware/auth";import { activatePayrollCustomVariable, bulkSavePayrollPeriodInputs, createPayrollCustomVariable, listPayrollCustomVariables, listPayrollPeriodInputs, retirePayrollCustomVariable, savePayrollPeriodInput, updatePayrollCustomVariable } from "../service/payroll-period-input-operations.service";
const scope=(req:AuthenticatedRequest)=>({companyCode:req.user!.companyCode!,branchId:req.user!.branchId!});const fail=(res:Response,e:any)=>res.status(e?.status??500).json({status:"error",code:e?.code??"PAYROLL_PERIOD_INPUT_ERROR",message:e instanceof Error?e.message:"Không thể xử lý dữ liệu kỳ"});
export const payrollPeriodInputController={
async list(req:AuthenticatedRequest,res:Response){try{return res.json({status:"success",data:await listPayrollPeriodInputs(scope(req),req.params.periodKey)});}catch(e){return fail(res,e);}},
async save(req:AuthenticatedRequest,res:Response){try{return res.json({status:"success",data:await savePayrollPeriodInput(scope(req),req.params.periodKey,req.params.employeeId,req.user!.id,req.body)});}catch(e){return fail(res,e);}},
async bulk(req:AuthenticatedRequest,res:Response){try{return res.json({status:"success",data:await bulkSavePayrollPeriodInputs(scope(req),req.params.periodKey,req.user!.id,req.body.rows??[])});}catch(e){return fail(res,e);}},
async variables(req:AuthenticatedRequest,res:Response){try{return res.json({status:"success",data:await listPayrollCustomVariables(req.user!.companyCode!)});}catch(e){return fail(res,e);}},
async createVariable(req:AuthenticatedRequest,res:Response){try{return res.status(201).json({status:"success",data:await createPayrollCustomVariable(req.user!.companyCode!,req.user!.id,req.body)});}catch(e){return fail(res,e);}},
async updateVariable(req:AuthenticatedRequest,res:Response){const{expectedVersion,...value}=req.body;try{return res.json({status:"success",data:await updatePayrollCustomVariable(req.user!.companyCode!,req.params.id,Number(expectedVersion),value)});}catch(e){return fail(res,e);}},
async activateVariable(req:AuthenticatedRequest,res:Response){try{return res.json({status:"success",data:await activatePayrollCustomVariable(req.user!.companyCode!,req.params.id,req.user!.id)});}catch(e){return fail(res,e);}},
async retireVariable(req:AuthenticatedRequest,res:Response){try{return res.json({status:"success",data:await retirePayrollCustomVariable(req.user!.companyCode!,req.params.id,req.user!.id)});}catch(e){return fail(res,e);}},};
