import React from "react";
import { Save, X } from "lucide-react";
import { toast } from "../../../pages/Toast";
import type { Worker, WorkerInput } from "../types";

type Props = { isOpen: boolean; onClose: () => void; onSubmit: (input: WorkerInput) => Promise<Worker>; onSuccess: (worker: Worker) => void; };
const initialForm: WorkerInput = { fullName: "", phone: "", email: "", status: "active", note: "", address: "", birthday: "", idCard: "", registrationDate: new Date().toLocaleDateString("vi-VN") };
export function AddWorkerModal({ isOpen, onClose, onSubmit, onSuccess }: Props) {
  const [form, setForm] = React.useState<WorkerInput>(initialForm);
  const [submitting, setSubmitting] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  if (!isOpen) return null;
  const update = (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!form.fullName?.trim()) { const message = "Vui lòng nhập họ và tên lao động."; setError(message); toast.error(message); return; }
    setSubmitting(true); setError(null);
    try { const worker = await onSubmit(form); toast.success("Đã lưu hồ sơ Lao động thành công!"); setForm(initialForm); onClose(); onSuccess(worker); }
    catch (reason) { const message = reason instanceof Error ? reason.message : "Lỗi lưu hồ sơ Lao động."; setError(message); toast.error(message); }
    finally { setSubmitting(false); }
  };
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button aria-label="Đóng" type="button" onClick={onClose} className="absolute inset-0 bg-slate-900/50 backdrop-blur-[2px]" /><div className="relative flex max-h-[95vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex shrink-0 items-center justify-between border-b border-slate-100 px-6 py-4"><h2 className="text-base font-bold text-slate-800">Thêm lao động mới</h2><button type="button" onClick={onClose} disabled={submitting} className="rounded-full p-1.5 transition-colors hover:bg-slate-100 disabled:opacity-50"><X className="h-4 w-4 text-slate-400" /></button></div><form className="space-y-4 overflow-y-auto p-6" onSubmit={submit}>{error && <div className="rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm font-bold text-rose-600">{error}</div>}<div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Field label="Họ và tên *" name="fullName" value={form.fullName} onChange={update} required /><Field label="Số điện thoại" name="phone" value={form.phone || ""} onChange={update} /><Field label="Email" name="email" type="email" value={form.email || ""} onChange={update} /><Field label="CCCD / CMND" name="idCard" value={form.idCard || ""} onChange={update} /><Field label="Ngày sinh" name="birthday" type="date" value={form.birthday || ""} onChange={update} /><Field label="Ngày tiếp nhận" name="registrationDate" value={form.registrationDate || ""} onChange={update} /><div className="space-y-1"><label className="text-[10px] font-bold uppercase tracking-wider text-slate-800">Trạng thái</label><select name="status" value={form.status} onChange={update} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm transition-all focus:border-cyan-600 focus:outline-none"><option value="active">Đang tuyển</option><option value="placed">Đã trúng tuyển</option><option value="inactive">Ngừng xử lý</option></select></div><Field label="Địa chỉ" name="address" value={form.address || ""} onChange={update} /></div><div className="space-y-1"><label className="text-[10px] font-bold uppercase tracking-wider text-slate-800">Ghi chú</label><textarea name="note" value={form.note || ""} onChange={update} rows={3} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm transition-all focus:border-cyan-600 focus:outline-none" /></div><div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" onClick={onClose} disabled={submitting} className="rounded-xl px-4 py-2 text-xs font-bold text-slate-500 hover:bg-slate-100">Hủy</button><button type="submit" disabled={submitting} className="flex items-center gap-1.5 rounded-xl bg-cyan-600 px-4 py-2 text-xs font-bold text-white shadow-md shadow-cyan-100 hover:bg-cyan-700 disabled:opacity-50"><Save className="h-3.5 w-3.5" />{submitting ? "Đang lưu..." : "Lưu hồ sơ"}</button></div></form></div></div>;
}
function Field({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <div className="space-y-1"><label htmlFor={props.name} className="text-[10px] font-bold uppercase tracking-wider text-slate-800">{label}</label><input id={props.name} {...props} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm transition-all focus:border-cyan-600 focus:outline-none" /></div>; }