import React from "react";
import { retailCustomersApi } from "../../api/retailCustomers.api";
import type { RetailCustomerTierHistory, RetailScope } from "../../types";
export default function RetailCustomerTierPanel({ scope, customerId, canManage }: { scope: RetailScope; customerId: string; canManage: boolean }) {
  const [history, setHistory] = React.useState<RetailCustomerTierHistory[]>([]); const [tierCode, setTierCode] = React.useState("vip"); const [reason, setReason] = React.useState(""); const [effectiveFrom, setEffectiveFrom] = React.useState(""); const [effectiveTo, setEffectiveTo] = React.useState(""); const [error, setError] = React.useState("");
  const load = React.useCallback(() => retailCustomersApi.tierHistory(customerId, scope).then(setHistory).catch((cause) => setError(cause instanceof Error ? cause.message : "Không tải được lịch sử hạng.")), [customerId, scope.companyCode, scope.branchId]);
  React.useEffect(() => { void load(); }, [load]);
  const submit = async () => { try { await retailCustomersApi.overrideTier(customerId, { tierCode, reason, effectiveFrom, effectiveTo }, scope); setReason(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không override được hạng."); } };
  return <section className="mt-6 space-y-3 border-t pt-5"><h3 className="font-bold">Lịch sử phân hạng</h3>{error && <p className="text-sm text-red-600">{error}</p>}<div className="space-y-2">{history.map((entry) => <div key={entry._id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{entry.toTierName}</b><p className="text-xs text-slate-500">{entry.source === "manual" ? `Override: ${entry.reason || ""}` : "Tự động theo doanh số"}</p></div>)}</div>{canManage && <div className="grid gap-2 rounded-xl border p-3 sm:grid-cols-2"><label className="text-sm">Hạng áp dụng<select aria-label="Hạng áp dụng" value={tierCode} onChange={(event) => setTierCode(event.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value="standard">Thành viên</option><option value="silver">Bạc</option><option value="gold">Vàng</option><option value="vip">VIP</option></select></label><label className="text-sm">Lý do<input aria-label="Lý do override" value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Từ ngày<input aria-label="Hiệu lực từ" type="date" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Đến ngày<input aria-label="Hiệu lực đến" type="date" value={effectiveTo} onChange={(event) => setEffectiveTo(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><button type="button" onClick={() => void submit()} className="rounded-lg bg-cyan-600 px-3 py-2 font-bold text-white sm:col-span-2">Áp dụng hạng</button></div>}</section>;
}
