import { model, Schema } from "mongoose";
import type { IRetailOrder } from "../interfaces/retail-order.interface";
export const RETAIL_PAYMENT_METHODS = ["cash", "card", "transfer", "ewallet"] as const;
const ItemSchema = new Schema({ productId: { type: String, required: true }, sku: { type: String, required: true }, productName: { type: String, required: true }, unit: { type: String, required: true }, category: String, brand: String, quantity: { type: Number, required: true, min: 1 }, unitPrice: { type: Number, required: true, min: 0 }, unitCost: { type: Number, required: true, min: 0 }, discountAmount: { type: Number, required: true, min: 0 }, lineTotal: { type: Number, required: true, min: 0 }, note: String }, { _id: false });
const PaymentSchema = new Schema({ method: { type: String, enum: RETAIL_PAYMENT_METHODS, required: true }, amount: { type: Number, required: true, min: 1 }, tenderedAmount: { type: Number, min: 0 }, changeAmount: { type: Number, min: 0 }, reference: String, paidAt: { type: Date, required: true }, receivedBy: { type: String, required: true }, receivedByName: { type: String, required: true }, shiftId: { type: String, required: true }, businessDate: { type: String, required: true } }, { _id: false });
const RefundSchema = new Schema({ method: { type: String, enum: RETAIL_PAYMENT_METHODS, required: true }, amount: { type: Number, required: true, min: 1 }, reference: String, refundedAt: { type: Date, required: true }, refundedBy: { type: String, required: true }, refundedByName: { type: String, required: true }, shiftId: { type: String, required: true }, businessDate: { type: String, required: true }, reason: { type: String, required: true } }, { _id: false });
const RetailOrderSchema = new Schema<IRetailOrder>({ orderCode: String, companyCode: { type: String, required: true, index: true }, branchId: { type: String, required: true, index: true }, shiftId: { type: String, index: true }, customerId: { type: String, index: true }, customerName: String, customerPhone: String, items: { type: [ItemSchema], required: true, default: [] }, subtotal: { type: Number, required: true, min: 0 }, orderDiscount: { type: Number, required: true, min: 0 }, taxRate: { type: Number, required: true, min: 0, max: 100 }, taxAmount: { type: Number, required: true, min: 0 }, shippingFee: { type: Number, required: true, min: 0 }, grandTotal: { type: Number, required: true, min: 0 }, totalCost: { type: Number, required: true, min: 0 }, payments: { type: [PaymentSchema], default: [] }, refunds: { type: [RefundSchema], default: [] }, paidAmount: { type: Number, default: 0, min: 0 }, refundedAmount: { type: Number, default: 0, min: 0 }, dueAmount: { type: Number, default: 0, min: 0 }, paymentStatus: { type: String, enum: ["unpaid", "partial", "paid", "refunded"], default: "unpaid", index: true }, dueDate: Date, status: { type: String, enum: ["draft", "confirmed", "completed", "cancelled"], default: "draft", index: true }, businessDate: { type: String, index: true }, heldAt: Date, heldSlot: { type: Number, min: 1, max: 5 }, expiredBySystem: { type: Boolean, default: false }, confirmedAt: Date, completedAt: Date, cancelledAt: Date, cancelReason: String, salespersonId: { type: String, required: true }, salespersonName: { type: String, required: true }, createdBy: { type: String, required: true }, createdByName: { type: String, required: true }, stockApplied: { type: Boolean, default: false }, stockRevertedAt: Date, version: { type: Number, default: 0 } }, { timestamps: true });
RetailOrderSchema.index({ companyCode: 1, orderCode: 1 }, { unique: true, partialFilterExpression: { orderCode: { $type: "string" } } });
RetailOrderSchema.index({ companyCode: 1, branchId: 1, businessDate: -1, status: 1 });
RetailOrderSchema.index(
  { companyCode: 1, branchId: 1, createdBy: 1, heldSlot: 1 },
  { unique: true, partialFilterExpression: { status: "draft", heldSlot: { $type: "number" } } },
);
export const RetailOrderModel = model<IRetailOrder>("RetailOrder", RetailOrderSchema);
