import { apiFetch } from "../lib/api";

export type RoadmapPolicy = { matchMode: "all" | "any"; minAttendanceRate?: number | null; minAssignmentRate?: number | null; minMiniTestRate?: number | null; minExamRate?: number | null; };
export type RoadmapStep = { id: string; courseId: string; order: number; minClassSize: number; maxClassSize: number; eligibilityPolicy: RoadmapPolicy; };
export type LearningRoadmap = { id: string; code: string; name: string; description: string; status: "active" | "inactive"; steps: RoadmapStep[]; };
export type ProgressionRow = { studentId: string; studentName: string; studentPhone: string; attendanceRate: number | null; assignmentRate: number | null; miniTestRate: number | null; examRate: number | null; eligible: boolean; eligibilityReasons: string[]; intent: "continue" | "pending" | "stop" | "preserve" | "repeat"; teacherNote: string; };
export type BatchProgression = { batch: { id: string; code: string; courseId: string }; selectedRoadmapId: string; sourceStep?: RoadmapStep; targetStep: RoadmapStep | null; rows: ProgressionRow[]; };
export type WaitlistRow = { id: string; studentId: string; studentName: string; studentPhone: string; roadmapId: string; roadmapName: string; targetStepId: string; targetCourseId: string; sourceBatchCode: string; learningFormat: string; preferredTimeSlot: string; queuedAt: string; waitingDays: number; };

function normalize(item: LearningRoadmap & { _id?: string }): LearningRoadmap { return { ...item, id: item.id || item._id || "" }; }
export async function getRoadmaps() { const response = await apiFetch<{ success: boolean; data: Array<LearningRoadmap & { _id?: string }> }>("/learning-roadmaps"); return response.data.map(normalize); }
export async function createRoadmap(data: Omit<LearningRoadmap, "id">) { const response = await apiFetch<{ success: boolean; data: LearningRoadmap & { _id?: string } }>("/learning-roadmaps", { method: "POST", body: JSON.stringify(data) }); return normalize(response.data); }
export async function updateRoadmap(id: string, data: Partial<Omit<LearningRoadmap, "id">>) { const response = await apiFetch<{ success: boolean; data: LearningRoadmap & { _id?: string } }>(`/learning-roadmaps/${id}`, { method: "PATCH", body: JSON.stringify(data) }); return normalize(response.data); }
export async function getBatchProgression(batchId: string, roadmapId: string) { const response = await apiFetch<{ success: boolean; data: BatchProgression }>(`/learning-roadmaps/batches/${batchId}/progression`, { params: { roadmapId } }); return response.data; }
export async function saveProgression(batchId: string, studentId: string, data: { roadmapId: string; intent: ProgressionRow["intent"]; teacherNote: string; overrideEligible?: boolean | null; overrideReason?: string; }) { return apiFetch(`/learning-roadmaps/batches/${batchId}/students/${studentId}/progression`, { method: "PATCH", body: JSON.stringify({ ...data, overrideEligible: data.overrideEligible ?? null, overrideReason: data.overrideReason || "" }) }); }
export async function getWaitlist(params: { page: number; limit: number; roadmapId?: string; targetStepId?: string; batchId?: string }) { return apiFetch<{ success: boolean; items: WaitlistRow[]; total: number; page: number; totalPages: number }>("/learning-roadmaps/waitlist", { params }); }
export async function placeWaitlist(batchId: string, entryIds: string[]) { return apiFetch<{ success: boolean }>("/learning-roadmaps/waitlist/place", { method: "POST", body: JSON.stringify({ batchId, entryIds }) }); }
