import { Router } from "express";
import { retailSettingsRoutes } from "./routes/retail-settings.routes";
import { cashierShiftRoutes } from "./routes/cashier-shift.routes";
import { retailOrderRoutes } from "./routes/retail-order.routes";
import { retailInvoiceRoutes } from "./routes/retail-invoice.routes";
import { retailReportRoutes } from "./routes/retail-report.routes";
import { retailReceivableRoutes } from "./routes/retail-receivable.routes";
import { retailDebtReminderRoutes } from "./routes/retail-debt-reminder.routes";
import { registerRetailFinanceSettlementConsumer } from "./consumers/finance-settlement.consumer";
import { retailWarrantyRoutes } from "./routes/retail-warranty.routes";

export const retailRouter = Router();
registerRetailFinanceSettlementConsumer();
retailRouter.use("/retail/settings", retailSettingsRoutes);
retailRouter.use("/retail/shifts", cashierShiftRoutes);
retailRouter.use("/retail/orders", retailOrderRoutes);
retailRouter.use("/retail/invoices", retailInvoiceRoutes);
retailRouter.use("/retail/reports", retailReportRoutes);
retailRouter.use("/retail/receivables", retailReceivableRoutes);
retailRouter.use("/retail/debt-reminders", retailDebtReminderRoutes);
retailRouter.use("/retail/warranty", retailWarrantyRoutes);
