import { Router } from "express";
import { requirePermission } from "../../../middleware/auth";
import { cashierShiftController } from "../controllers/cashier-shift.controller";
import { RETAIL_MANAGER_PERMISSION, RETAIL_OPERATE_PERMISSION } from "../permissions";
export const cashierShiftRoutes = Router(); const operate = requirePermission([RETAIL_OPERATE_PERMISSION, RETAIL_MANAGER_PERMISSION]) as any;
const manage = requirePermission(RETAIL_MANAGER_PERMISSION) as any;
cashierShiftRoutes.get("/current", operate, cashierShiftController.current as any);
cashierShiftRoutes.get("/cashiers", manage, cashierShiftController.cashiers as any);
cashierShiftRoutes.get("/drawers", manage, cashierShiftController.drawers as any);
cashierShiftRoutes.post("/drawers", manage, cashierShiftController.createDrawer as any);
cashierShiftRoutes.get("/settlements", manage, cashierShiftController.settlements as any);
cashierShiftRoutes.post("/settlements/review", manage, cashierShiftController.reviewSettlement as any);
cashierShiftRoutes.get("/", manage, cashierShiftController.list as any);
cashierShiftRoutes.get("/:id", manage, cashierShiftController.detail as any);
cashierShiftRoutes.post("/open", manage, cashierShiftController.open as any);
cashierShiftRoutes.post("/:id/resume", operate, cashierShiftController.resume as any);
cashierShiftRoutes.post("/:id/pause", operate, cashierShiftController.pause as any);
cashierShiftRoutes.post("/:id/cash-movements", manage, cashierShiftController.moveCash as any);
cashierShiftRoutes.post("/:id/cash-movements/reconcile", manage, cashierShiftController.reconcileMovement as any);
cashierShiftRoutes.post("/:id/drawer", manage, cashierShiftController.transferDrawer as any);
cashierShiftRoutes.post("/:id/close", operate, cashierShiftController.close as any);
cashierShiftRoutes.post("/:id/reconcile", manage, cashierShiftController.reconcile as any);
