import { Router } from "express";
import { requirePermission } from "../../../middleware/auth";
import { retailInvoiceController } from "../controllers/retail-invoice.controller";
import { RETAIL_MANAGER_PERMISSION, RETAIL_OPERATE_PERMISSION } from "../permissions";
export const retailInvoiceRoutes = Router(); const read = requirePermission(["retail:read", RETAIL_MANAGER_PERMISSION]) as any; const operate = requirePermission([RETAIL_OPERATE_PERMISSION, RETAIL_MANAGER_PERMISSION]) as any; const manage = requirePermission(RETAIL_MANAGER_PERMISSION) as any;
retailInvoiceRoutes.get("/", read, retailInvoiceController.list as any);
retailInvoiceRoutes.post("/:id/pos-print", operate, retailInvoiceController.posPrint as any);
retailInvoiceRoutes.post("/:id/reprint", manage, retailInvoiceController.reprint as any);
retailInvoiceRoutes.get("/:id/pdf", manage, retailInvoiceController.pdf as any);
retailInvoiceRoutes.get("/:id", read, retailInvoiceController.detail as any);
