import { Router } from "express";
import { requireAuth, requirePermission } from "../middleware/auth";
import { payrollController } from "../controller/payroll.controller";
import { payrollFormulaController } from "../controller/payroll-formula.controller";
import { payrollPeriodInputController } from "../controller/payroll-period-input.controller";
import { payrollLineOverrideController } from "../controller/payroll-line-override.controller";
export const payrollRouter = Router();
payrollRouter.use(requireAuth as any);
payrollRouter.get("/period-input-variables", requirePermission("payroll-period:read") as any, payrollPeriodInputController.variables as any);
payrollRouter.post("/period-input-variables", requirePermission("payroll-period:manage") as any, payrollPeriodInputController.createVariable as any);
payrollRouter.patch("/period-input-variables/:id", requirePermission("payroll-period:manage") as any, payrollPeriodInputController.updateVariable as any);
payrollRouter.post("/period-input-variables/:id/activate", requirePermission("payroll-period:manage") as any, payrollPeriodInputController.activateVariable as any);
payrollRouter.post("/period-input-variables/:id/retire", requirePermission("payroll-period:manage") as any, payrollPeriodInputController.retireVariable as any);
payrollRouter.get("/periods/:periodKey/inputs", requirePermission("payroll-period:read") as any, payrollPeriodInputController.list as any);
payrollRouter.put("/periods/:periodKey/inputs/:employeeId", requirePermission("payroll-period:manage") as any, payrollPeriodInputController.save as any);
payrollRouter.put("/periods/:periodKey/inputs", requirePermission("payroll-period:manage") as any, payrollPeriodInputController.bulk as any);
payrollRouter.get("/periods/:periodKey/line-overrides", requirePermission("payroll-period:read") as any, payrollLineOverrideController.list as any);
payrollRouter.put("/periods/:periodKey/line-overrides", requirePermission("payroll-period:manage") as any, payrollLineOverrideController.bulk as any);
payrollRouter.get("/formulas", requirePermission("payroll-policy:read") as any, payrollFormulaController.list as any);
payrollRouter.post("/formulas", requirePermission("payroll-policy:manage") as any, payrollFormulaController.create as any);
payrollRouter.patch("/formulas/:id", requirePermission("payroll-policy:manage") as any, payrollFormulaController.update as any);
payrollRouter.post("/formulas/:id/activate", requirePermission("payroll-policy:manage") as any, payrollFormulaController.activate as any);
payrollRouter.post("/formulas/:id/retire", requirePermission("payroll-policy:manage") as any, payrollFormulaController.retire as any);
payrollRouter.post("/formulas/:id/clone", requirePermission("payroll-policy:manage") as any, payrollFormulaController.clone as any);
payrollRouter.post("/runs", requirePermission("payroll-period:manage") as any, payrollController.createOperationalRun as any);
payrollRouter.post("/runs/:id/sync-attendance", requirePermission("payroll-period:manage") as any, payrollController.syncAttendance as any);
payrollRouter.post("/runs/:id/lock-attendance", requirePermission("payroll-period:manage") as any, payrollController.lockAttendance as any);
payrollRouter.get("/policies", requirePermission("payroll-policy:read") as any, payrollController.listPolicies as any);
payrollRouter.post("/policies", requirePermission("payroll-policy:manage") as any, payrollController.createPolicy as any);
payrollRouter.post("/policies/:id/activate", requirePermission("payroll-policy:manage") as any, payrollController.activatePolicy as any);
payrollRouter.post("/policies/:id/retire", requirePermission("payroll-policy:manage") as any, payrollController.retirePolicy as any);
payrollRouter.patch("/policies/:id", requirePermission("payroll-policy:manage") as any, payrollController.updatePolicy as any);
payrollRouter.post("/policies/:id/clone", requirePermission("payroll-policy:manage") as any, payrollController.clonePolicy as any);
payrollRouter.delete("/policies/:id", requirePermission("payroll-policy:manage") as any, payrollController.deletePolicy as any);
payrollRouter.post("/runs/:id/review", requirePermission("payroll-period:manage") as any, payrollController.reviewOperationalRun as any);
payrollRouter.post("/runs/:id/close", requirePermission("payroll-period:manage") as any, payrollController.closeOperationalRun as any);
payrollRouter.post("/runs/:id/reopen", requirePermission("payroll-period:manage") as any, payrollController.reopenOperationalRun as any);
payrollRouter.post("/runs/:id/mark-paid", requirePermission("payroll-payment:manage") as any, payrollController.markOperationalRunPaid as any);
payrollRouter.get("/runs/:id/audit", requirePermission("payroll-period:read") as any, payrollController.listRunAudit as any);
payrollRouter.post("/runs/:id/calculate", requirePermission("payroll-period:manage") as any, payrollController.calculateRun as any);
payrollRouter.post("/runs/:id/recalculate", requirePermission("payroll-period:manage") as any, payrollController.calculateRun as any);
payrollRouter.get("/runs/:id/issues", requirePermission("payroll-period:read") as any, payrollController.listRunIssues as any);
payrollRouter.get("/runs/:id/lines/:employeeId", payrollController.getLineDetail as any);
payrollRouter.post("/runs/:id/payslips/publish", requirePermission("payroll-payment:manage") as any, payrollController.publishPayslips as any);
payrollRouter.get(
  "/runs/:id/payslips/:employeeId/print",
  payrollController.printPayslip as any,
);
payrollRouter.post("/runs/:id/payslips/:employeeId/withdraw", requirePermission("payroll-payment:manage") as any, payrollController.withdrawPayslip as any);
payrollRouter.get("/employee/me/payslips", payrollController.listEmployeePayslips as any);
payrollRouter.post("/runs/:id/exports", requirePermission("payroll-payment:read") as any, payrollController.exportPayroll as any);
payrollRouter.get("/runs/:id/payments", requirePermission("payroll-payment:read") as any, payrollController.listPayments as any);
payrollRouter.post("/runs/:id/payments", requirePermission("payroll-payment:manage") as any, payrollController.createPayment as any);
payrollRouter.post("/payments/:id/confirm", requirePermission("payroll-payment:manage") as any, payrollController.confirmPayment as any);
payrollRouter.post("/payments/:id/cancel", requirePermission("payroll-payment:manage") as any, payrollController.cancelPayment as any);
payrollRouter.post("/payments/:id/reverse", requirePermission("payroll-payment:manage") as any, payrollController.reversePayment as any);
payrollRouter.get("/periods/:periodKey/audit", requirePermission("payroll-period:read") as any, payrollController.listAudit as any);
payrollRouter.get("/periods/:periodKey/results", requirePermission("payroll-period:read") as any, payrollController.listResults as any);
payrollRouter.post("/periods/:periodKey/snapshot", requirePermission("payroll-period:manage") as any, payrollController.createSnapshot as any);
payrollRouter.post("/periods/:periodKey/lock", requirePermission("payroll-period:manage") as any, payrollController.lockResults as any);
payrollRouter.post("/periods/:periodKey/run", requirePermission("payroll-period:manage") as any, payrollController.createRun as any);
payrollRouter.post("/periods/:periodKey/process", requirePermission("payroll-period:manage") as any, payrollController.processPeriod as any);
payrollRouter.get("/periods/:periodKey/run", requirePermission("payroll-period:read") as any, payrollController.getRun as any);
payrollRouter.delete("/periods/:periodKey", requirePermission("payroll-period:manage") as any, payrollController.resetPeriod as any);
payrollRouter.post("/periods/:periodKey/adjustments/:adjustmentId/approve", requirePermission("payroll-period:manage") as any, payrollController.approveAdjustment as any);
payrollRouter.post("/periods/:periodKey/adjustments/:adjustmentId/reject", requirePermission("payroll-period:manage") as any, payrollController.rejectAdjustment as any);
payrollRouter.post("/periods/:periodKey/approve", requirePermission("payroll-period:manage") as any, payrollController.approveRun as any);
payrollRouter.post("/periods/:periodKey/close", requirePermission("payroll-period:manage") as any, payrollController.closeRun as any);
payrollRouter.get("/periods/:periodKey/adjustments", requirePermission("payroll-period:read") as any, payrollController.listAdjustments as any);
payrollRouter.post("/periods/:periodKey/adjustments", requirePermission("payroll-period:manage") as any, payrollController.createAdjustment as any);
