import { Router } from "express";
import { requireAuth, requirePermission } from "../middleware/auth";
import { payrollController } from "../controller/payroll.controller";
export const payrollRouter = Router();
payrollRouter.use(requireAuth as any);
payrollRouter.post("/runs", requirePermission("payroll:prepare") as any, payrollController.createOperationalRun as any);
payrollRouter.post("/runs/:id/sync-attendance", requirePermission("payroll:prepare") as any, payrollController.syncAttendance as any);
payrollRouter.post("/runs/:id/lock-attendance", requirePermission("payroll:prepare") as any, payrollController.lockAttendance as any);
payrollRouter.get("/policies", requirePermission("payroll:read") as any, payrollController.listPolicies as any);
payrollRouter.post("/policies", requirePermission("payroll:manage") as any, payrollController.createPolicy as any);
payrollRouter.post("/policies/:id/activate", requirePermission("payroll:manage") as any, payrollController.activatePolicy as any);
payrollRouter.post("/policies/:id/retire", requirePermission("payroll:manage") as any, payrollController.retirePolicy as any);
payrollRouter.post("/runs/:id/review", requirePermission("payroll:manage") as any, payrollController.reviewOperationalRun as any);
payrollRouter.post("/runs/:id/approve", requirePermission("payroll:manage") as any, payrollController.approveOperationalRun as any);
payrollRouter.post("/runs/:id/reject", requirePermission("payroll:manage") as any, payrollController.rejectOperationalRun as any);
payrollRouter.post("/runs/:id/close", requirePermission("payroll:manage") as any, payrollController.closeOperationalRun as any);
payrollRouter.get("/runs/:id/audit", requirePermission("payroll:read") as any, payrollController.listRunAudit as any);
payrollRouter.post("/runs/:id/calculate", requirePermission("payroll:manage") as any, payrollController.calculateRun as any);
payrollRouter.post("/runs/:id/recalculate", requirePermission("payroll:manage") as any, payrollController.calculateRun as any);
payrollRouter.get("/runs/:id/issues", requirePermission("payroll:read") as any, payrollController.listRunIssues as any);
payrollRouter.get("/runs/:id/lines/:employeeId", requirePermission("payroll:read") as any, payrollController.getLineDetail as any);payrollRouter.post("/runs/:id/payslips/publish", requirePermission("payroll:manage") as any, payrollController.publishPayslips as any);
payrollRouter.get("/runs/:id/payslips/:employeeId/print", requirePermission("payroll:read") as any, payrollController.printPayslip as any);
payrollRouter.post("/runs/:id/payslips/:employeeId/withdraw", requirePermission("payroll:manage") as any, payrollController.withdrawPayslip as any);
payrollRouter.get("/employee/me/payslips", payrollController.listEmployeePayslips as any);
payrollRouter.post("/runs/:id/exports", requirePermission("payroll:read") as any, payrollController.exportPayroll as any);
payrollRouter.get("/runs/:id/payments", requirePermission("payroll:read") as any, payrollController.listPayments as any);
payrollRouter.post("/runs/:id/payments", requirePermission("payroll:pay") as any, payrollController.createPayment as any);
payrollRouter.post("/payments/:id/confirm", requirePermission("payroll:pay") as any, payrollController.confirmPayment as any);
payrollRouter.post("/payments/:id/cancel", requirePermission("payroll:pay") as any, payrollController.cancelPayment as any);
payrollRouter.post("/payments/:id/reverse", requirePermission("payroll:pay") as any, payrollController.reversePayment as any);
payrollRouter.get("/periods/:periodKey/audit", requirePermission("payroll:read") as any, payrollController.listAudit as any);
payrollRouter.get("/periods/:periodKey/results", requirePermission("payroll:read") as any, payrollController.listResults as any);
payrollRouter.post("/periods/:periodKey/snapshot", requirePermission("payroll:manage") as any, payrollController.createSnapshot as any);
payrollRouter.post("/periods/:periodKey/lock", requirePermission("payroll:manage") as any, payrollController.lockResults as any);
payrollRouter.post("/periods/:periodKey/run", requirePermission("payroll:manage") as any, payrollController.createRun as any);
payrollRouter.get("/periods/:periodKey/run", requirePermission("payroll:read") as any, payrollController.getRun as any);
payrollRouter.delete("/periods/:periodKey", requirePermission("payroll:manage") as any, payrollController.resetPeriod as any);
payrollRouter.post("/periods/:periodKey/adjustments/:adjustmentId/approve", requirePermission("payroll:manage") as any, payrollController.approveAdjustment as any);
payrollRouter.post("/periods/:periodKey/adjustments/:adjustmentId/reject", requirePermission("payroll:manage") as any, payrollController.rejectAdjustment as any);
payrollRouter.post("/periods/:periodKey/approve", requirePermission("payroll:manage") as any, payrollController.approveRun as any);
payrollRouter.post("/periods/:periodKey/close", requirePermission("payroll:manage") as any, payrollController.closeRun as any);
payrollRouter.get("/periods/:periodKey/adjustments", requirePermission("payroll:read") as any, payrollController.listAdjustments as any);
payrollRouter.post("/periods/:periodKey/adjustments", requirePermission("payroll:manage") as any, payrollController.createAdjustment as any);
