import { apiFetch } from "../../shared/lib/apiFetch";
import type { RetailScope, RetailShift, RetailShiftDetail } from "../types";
export const retailShiftsApi = {
  async cashiers(scope: RetailScope) { const response = await apiFetch<{ data: Array<{ id: string; name: string }> }>("/retail/shifts/cashiers", { params: scope }); return response.data; },
  async resume(scope: RetailScope, id: string, expectedTerminalId?: string) { const response = await apiFetch<{ data: RetailShift }>(`/retail/shifts/${id}/resume`, { method: "POST", params: scope, body: JSON.stringify({ terminalId: scope.terminalId, expectedTerminalId }) }); return response.data; },
  async pause(scope: RetailScope, id: string) { await apiFetch(`/retail/shifts/${id}/pause`, { method: "POST", params: scope }); },
  async reconcileMovement(scope: RetailScope, id: string, input: { reversesKey?: string; type: "in" | "out"; amount: number; reason: string; idempotencyKey: string }, revoke = false) { const response = await apiFetch<{ data: { status: "completed" | "revoked" | "not_found"; message: string } }>(`/retail/shifts/${id}/cash-movements/reconcile`, { method: "POST", params: scope, body: JSON.stringify({ ...input, revoke }) }); return response.data; },
  async moveCash(scope: RetailScope, id: string, input: { reversesKey?: string; type: "in" | "out"; amount: number; reason: string; idempotencyKey: string }) { const response = await apiFetch<{ data: RetailShift }>(`/retail/shifts/${id}/cash-movements`, { method: "POST", params: scope, body: JSON.stringify(input) }); return response.data; },
  async settlements(scope: RetailScope, page = 1) { const response = await apiFetch<{ data: { items: Array<{ _id: string; orderCode: string; shiftId?: string; paymentIndex: number; payment: { amount: number; reference?: string; paidAt: string; receivedByName?: string } }>; total: number } }>("/retail/shifts/settlements", { params: { ...scope, page } }); return response.data; },
  async reviewSettlement(scope: RetailScope, input: { orderId: string; paymentIndex: number; reason: string }) { await apiFetch("/retail/shifts/settlements/review", { method: "POST", params: scope, body: JSON.stringify(input) }); },

  async current(scope: RetailScope) { const response = await apiFetch<{ success: true; data: RetailShift | null }>("/retail/shifts/current", { params: scope }); return response.data; },
  async list(scope: RetailScope, query: Record<string, string | number | undefined> = {}) { const response = await apiFetch<{ success: true; data: { items: RetailShift[]; total: number; page: number; limit: number } }>("/retail/shifts", { params: { ...scope, ...query } }); return response.data; },
  async detail(scope: RetailScope, id: string, query: Record<string, number> = {}) { const response = await apiFetch<{ success: true; data: RetailShiftDetail }>(`/retail/shifts/${id}`, { params: { ...scope, ...query } }); return response.data; },
  async open(scope: RetailScope, input: { openingFloat: number; terminalId?: string; cashierId?: string }) { const response = await apiFetch<{ success: true; data: RetailShift }>("/retail/shifts/open", { method: "POST", params: scope, body: JSON.stringify(input) }); return response.data; },
  async close(scope: RetailScope, id: string, input: { countedCash?: number; varianceReason?: string }) { const response = await apiFetch<{ success: true; data: RetailShift }>(`/retail/shifts/${id}/close`, { method: "POST", params: scope, body: JSON.stringify(input) }); return response.data; },
  async reconcile(scope: RetailScope, id: string, input: { countedCash: number; varianceReason?: string }) { const response = await apiFetch<{ success: true; data: RetailShift }>(`/retail/shifts/${id}/reconcile`, { method: "POST", params: scope, body: JSON.stringify(input) }); return response.data; },
};
