import React from "react";
import { Ban, Banknote, Eye, X } from "lucide-react";
import PaymentDialog from "../components/pos/PaymentDialog";
import { retailOrdersApi } from "../api/retailOrders.api";
import { useRetailScope } from "../hooks/useRetailScope";
import type { RetailOrder, RetailPaymentInput } from "../types";
const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value) + " ₫";
export default function RetailOrdersPage() {
  const { scope, userProfile } = useRetailScope(); const manager = userProfile?.role === "admin" || userProfile?.role === "superadmin" || userProfile?.permissions?.some((p) => p === "*" || p === "retail:manager"); const [q, setQ] = React.useState(""); const [status, setStatus] = React.useState(""); const [items, setItems] = React.useState<RetailOrder[]>([]); const [selected, setSelected] = React.useState<RetailOrder | null>(null); const [collecting, setCollecting] = React.useState(false); const [cancelling, setCancelling] = React.useState(false); const [error, setError] = React.useState("");
  const refresh = React.useCallback(() => { if (!scope) return; void retailOrdersApi.list(scope, { q, status: status || undefined }).then((data) => { setItems(data.items); setError(""); }).catch(show); }, [scope?.companyCode, scope?.branchId, q, status]); React.useEffect(() => { const timer = setTimeout(refresh, 250); return () => clearTimeout(timer); }, [refresh]);
  const show = (cause: unknown) => setError(cause instanceof Error ? cause.message : "Không xử lý được đơn hàng."); if (!scope) return <Notice />;
  const detail = async (id: string) => { try { setSelected(await retailOrdersApi.detail(scope, id)); } catch (e) { show(e); } };
  const openCollection = () => { if (!selected?.customerId) { setError("Vui lòng chọn khách hàng trước khi thanh toán."); return; } setError(""); setCollecting(true); };
  const collect = async (payments: RetailPaymentInput[]) => { if (!selected) return; try { const updated = await retailOrdersApi.collect(scope, selected._id, payments); setSelected(updated); setCollecting(false); refresh(); } catch (e) { show(e); } };
  const cancel = async (reason: string, refundMethod: RetailPaymentInput["method"]) => { if (!selected) return; const remaining = Math.max(0, selected.paidAmount - (selected.refundedAmount || 0)); const refunds = remaining ? [{ method: refundMethod, amount: remaining }] : []; try { const updated = await retailOrdersApi.cancel(scope, selected._id, { reason, refunds }); setSelected(updated); setCancelling(false); refresh(); } catch (e) { show(e); } };
  return <section className="space-y-4"><header><h1 className="text-xl font-bold">Đơn hàng</h1><p className="text-sm text-slate-500">Tra cứu, thu công nợ và hủy/hoàn tiền.</p></header><div className="grid gap-3 sm:grid-cols-[1fr_220px]"><input aria-label="Tìm đơn hàng" className="rounded-xl border px-3 py-2" placeholder="Mã đơn, khách hàng, số điện thoại" value={q} onChange={(e) => setQ(e.target.value)} /><select aria-label="Trạng thái đơn" className="rounded-xl border px-3 py-2" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option value="draft">Đơn treo</option><option value="confirmed">Còn xử lý</option><option value="completed">Hoàn tất</option><option value="cancelled">Đã hủy</option></select></div>{error && <p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="grid gap-3">{items.map((order) => <article key={order._id} className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{order.orderCode || `Đơn treo #${order._id.slice(-6)}`}</p><p className="text-sm text-slate-500">{order.customerName || "Khách lẻ"} · {order.businessDate || "Chưa xác nhận"}</p></div><div className="flex items-center gap-3"><div className="text-right"><p className="font-bold text-cyan-700">{money(order.grandTotal)}</p><p className="text-xs uppercase text-slate-500">{order.status} · {order.paymentStatus}</p></div><button aria-label="Xem chi tiết" className="rounded-xl border p-2" onClick={() => void detail(order._id)}><Eye className="h-4 w-4" /></button></div></div></article>)}</div>{selected && <OrderDialog order={selected} manager={Boolean(manager)} onClose={() => setSelected(null)} onCollect={openCollection} onCancel={() => setCancelling(true)} />}{collecting && selected && <PaymentDialog total={selected.dueAmount} busy={false} customerId={selected.customerId} onClose={() => setCollecting(false)} onSubmit={(payments) => collect(payments)} />}{cancelling && selected && <CancelDialog refundRequired={selected.paidAmount > 0} onClose={() => setCancelling(false)} onSubmit={cancel} />}</section>;
}
function OrderDialog({ order, manager, onClose, onCollect, onCancel }: { order: RetailOrder; manager: boolean; onClose: () => void; onCollect: () => void; onCancel: () => void }) { const canCancel = order.status !== "cancelled" && (order.status !== "completed" || manager); return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 sm:items-center sm:p-4"><div className="max-h-[95vh] w-full max-w-3xl overflow-y-auto rounded-t-3xl bg-white p-5 sm:rounded-3xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{order.orderCode || `Đơn treo #${order._id.slice(-6)}`}</h2><p className="text-sm text-slate-500">{order.customerName || "Khách lẻ"}</p></div><button onClick={onClose}><X /></button></div><div className="mt-5 space-y-2">{order.items.map((item) => <div key={item.productId} className="flex justify-between border-b py-2"><span>{item.productName} × {item.quantity}</span><b>{money(item.lineTotal)}</b></div>)}</div><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Tổng cộng" value={order.grandTotal} /><Metric label="Đã thu" value={order.paidAmount} /><Metric label="Còn nợ" value={order.dueAmount} /></div><div className="mt-5 flex flex-wrap gap-2">{order.status === "confirmed" && order.dueAmount > 0 && <button className="flex items-center gap-2 rounded-xl bg-cyan-600 px-4 py-2 font-bold text-white" onClick={onCollect}><Banknote className="h-4 w-4" />Thu công nợ</button>}{canCancel && <button className="flex items-center gap-2 rounded-xl border border-red-200 px-4 py-2 font-bold text-red-700" onClick={onCancel}><Ban className="h-4 w-4" />Hủy/hoàn tiền</button>}</div></div></div>; }
function CancelDialog({ refundRequired, onClose, onSubmit }: { refundRequired: boolean; onClose: () => void; onSubmit: (reason: string, method: RetailPaymentInput["method"]) => Promise<void> }) { const [reason, setReason] = React.useState(""); const [method, setMethod] = React.useState<RetailPaymentInput["method"]>("cash"); return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-md space-y-4 rounded-3xl bg-white p-5"><div className="flex justify-between"><h2 className="font-bold">Hủy đơn{refundRequired ? " và hoàn tiền" : ""}</h2><button onClick={onClose}><X /></button></div><textarea aria-label="Lý do hủy" className="w-full rounded-xl border p-3" placeholder="Lý do bắt buộc" value={reason} onChange={(e) => setReason(e.target.value)} />{refundRequired && <select aria-label="Phương thức hoàn tiền" className="w-full rounded-xl border px-3 py-2" value={method} onChange={(e) => setMethod(e.target.value as any)}><option value="cash">Tiền mặt</option><option value="card">Thẻ</option><option value="transfer">Chuyển khoản</option><option value="ewallet">Ví điện tử</option></select>}<button disabled={!reason.trim()} className="w-full rounded-xl bg-red-600 py-3 font-bold text-white disabled:opacity-40" onClick={() => void onSubmit(reason.trim(), method)}>Xác nhận hủy</button></div></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="font-bold">{money(value)}</p></div>; }
function Notice() { return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-800">Vui lòng chọn chi nhánh.</div>; }
