import React from "react";
import { Eye, RotateCcw, ShoppingBasket, X } from "lucide-react";
import { retailOrdersApi } from "../api/retailOrders.api";
import { retailAfterSalesApi } from "../api/retailAfterSales.api";
import { useRetailScope } from "../hooks/useRetailScope";
import type { RetailAfterSaleInput, RetailAfterSaleType, RetailOrder } from "../types";
import { getApiErrorMessage } from "../../../utils/errorMessage";
import { toast } from "../../../pages/Toast";
const money = (v: number) => new Intl.NumberFormat("vi-VN").format(v) + " ₫";

export default function RetailOrdersPageV2() {
  const { scope } = useRetailScope(); const [q, setQ] = React.useState(""); const [orders, setOrders] = React.useState<RetailOrder[]>([]); const [selected, setSelected] = React.useState<RetailOrder>();
  React.useEffect(() => { if (!scope) return; const t = setTimeout(() => void retailOrdersApi.list(scope, { q }).then((d) => setOrders(d.items)).catch((e) => toast.error(getApiErrorMessage(e, "Không tải được đơn hàng."))), 250); return () => clearTimeout(t); }, [scope?.companyCode, scope?.branchId, q]);
  if (!scope) return <p>Vui lòng chọn chi nhánh.</p>;
  return <section className="space-y-4"><header><h1 className="text-xl font-bold">Đơn hàng</h1><p className="text-sm text-slate-500">Tra cứu, trả hàng và thu mua lại sản phẩm đã bán.</p></header><input className="w-full rounded-xl border p-3" placeholder="Tìm mã đơn, khách hàng, số điện thoại" value={q} onChange={(e) => setQ(e.target.value)}/><div className="space-y-3">{orders.map((o) => <article key={o._id} className="flex justify-between rounded-2xl border bg-white p-4"><div><b>{o.orderCode || `Đơn #${o._id.slice(-6)}`}</b><p className="text-sm text-slate-500">{o.customerName || "Khách lẻ"} · {o.items.map((i) => `${i.sku} × ${i.quantity}`).join("; ")}</p></div><div className="text-right"><b className="text-cyan-700">{money(o.grandTotal)}</b><button className="ml-3 rounded-xl border p-2" onClick={() => void retailOrdersApi.detail(scope, o._id).then(setSelected)}><Eye className="h-4 w-4"/></button></div></article>)}</div>{selected && <Detail order={selected} close={() => setSelected(undefined)}/>}</section>;
}

function Detail({ order, close }: { order: RetailOrder; close: () => void }) {
  const [mode, setMode] = React.useState<RetailAfterSaleType>();
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white p-5"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{order.orderCode}</h2><p className="text-sm text-slate-500">{order.customerName || "Khách lẻ"} · {order.customerPhone || "Không có SĐT"}</p></div><button onClick={close}><X/></button></div><div className="mt-4 divide-y rounded-xl border">{order.items.map((i) => <div key={i.sku} className="flex justify-between p-3"><div><b>{i.productName}</b><p className="text-xs text-slate-500">{i.sku}{i.serialNumbers?.length ? ` · ${i.serialNumbers.join(", ")}` : ""}</p></div><span>{i.quantity} × {money(i.lineTotal / i.quantity)}</span></div>)}</div>{order.status === "completed" && <div className="mt-4 flex gap-2"><button className="flex gap-2 rounded-xl border px-4 py-2 text-orange-700" onClick={() => setMode("return")}><RotateCcw/>Trả hàng</button><button className="flex gap-2 rounded-xl bg-cyan-600 px-4 py-2 text-white" onClick={() => setMode("buyback")}><ShoppingBasket/>Thu mua lại</button></div>}{mode && <Form order={order} type={mode} close={() => setMode(undefined)} done={close}/>}</div></div>;
}

function Form({ order, type, close, done }: { order: RetailOrder; type: RetailAfterSaleType; close: () => void; done: () => void }) {
  const { scope } = useRetailScope(); const [reason, setReason] = React.useState(""); const [method, setMethod] = React.useState<RetailAfterSaleInput["paymentMethod"]>("cash"); const [busy, setBusy] = React.useState(false);
  const [rows, setRows] = React.useState(() => order.items.map((i) => ({ selected: false, quantity: 1, unitAmount: Math.round(i.lineTotal / i.quantity), condition: "good" as const, serialNumbers: [] as string[], internalBarcodes: [] as string[] })));
  const update = (n: number, patch: Partial<(typeof rows)[number]>) => setRows((a) => a.map((r, i) => i === n ? { ...r, ...patch } : r));
  const items = rows.flatMap((r, i) => r.selected ? [{ orderLineIndex: i, quantity: r.quantity, unitAmount: r.unitAmount, condition: r.condition, serialNumbers: r.serialNumbers, internalBarcodes: r.internalBarcodes }] : []);
  const refundRatio = order.subtotal > 0 ? Math.min(order.subtotal, Math.max(0, order.grandTotal - (order.shippingFee || 0))) / order.subtotal : 0;
  const total = items.reduce((s, r) => s + (type === "return" ? Math.floor(order.items[r.orderLineIndex].lineTotal / order.items[r.orderLineIndex].quantity * refundRatio) : r.unitAmount) * r.quantity, 0);
  const submit = async () => { if (!scope) return; setBusy(true); try { const d = await retailAfterSalesApi.create(scope, { type, orderId: order._id, items, paymentMethod: method, reason: reason.trim(), idempotencyKey: crypto.randomUUID() }); toast.success(`Đã tạo ${d.code}`); done(); } catch (e) { toast.error(getApiErrorMessage(e, "Không tạo được chứng từ.")); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/60 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-5"><div className="flex justify-between"><h3 className="text-lg font-bold">{type === "return" ? "Trả hàng / hoàn tiền" : "Thu mua hàng cũ"}</h3><button onClick={close}><X/></button></div><div className="mt-4 space-y-3">{order.items.map((item, i) => { const r = rows[i]; const codes = item.trackingMode === "serial" ? item.serialNumbers : item.trackingMode === "unit_barcode" ? item.internalBarcodes : undefined; const key = item.trackingMode === "serial" ? "serialNumbers" : "internalBarcodes"; return <div key={i} className="rounded-xl border p-3"><label className="font-semibold"><input className="mr-2" type="checkbox" checked={r.selected} onChange={(e) => update(i, { selected: e.target.checked })}/>{item.productName} ({item.sku})</label>{r.selected && <div className="mt-2 grid gap-2 sm:grid-cols-2"><label className="text-xs">Số lượng<input className="mt-1 w-full rounded-lg border p-2" type="number" min={1} max={item.quantity} disabled={Boolean(codes?.length)} value={r.quantity} onChange={(e) => update(i, { quantity: Number(e.target.value) })}/></label>{type === "buyback" && <label className="text-xs">Giá thu mua / đơn vị<input className="mt-1 w-full rounded-lg border p-2" type="number" min={0} value={r.unitAmount} onChange={(e) => update(i, { unitAmount: Number(e.target.value) })}/></label>}{codes?.length ? <div className="sm:col-span-2">{codes.map((code) => { const values = r[key]; return <label key={code} className="mr-2 inline-block rounded-lg border p-2 text-xs"><input className="mr-1" type="checkbox" checked={values.includes(code)} onChange={(e) => { const next = e.target.checked ? [...values, code] : values.filter((v) => v !== code); update(i, { [key]: next, quantity: Math.max(1, next.length) }); }}/>{code}</label>; })}</div> : null}</div>}</div>; })}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><select className="rounded-xl border p-2" value={method} onChange={(e) => setMethod(e.target.value as any)}><option value="cash">Tiền mặt</option><option value="transfer">Chuyển khoản</option><option value="card">Thẻ</option><option value="ewallet">Ví điện tử</option></select><input className="rounded-xl border p-2" placeholder="Lý do bắt buộc" value={reason} onChange={(e) => setReason(e.target.value)}/></div><div className="mt-4 flex justify-between"><b>Tổng chi: {money(total)}</b><button disabled={busy || !items.length || !reason.trim()} className="rounded-xl bg-cyan-600 px-5 py-2 font-bold text-white disabled:opacity-40" onClick={() => void submit()}>Xác nhận</button></div></div></div>;
}
