import React from "react";
import { retailShiftsApi } from "../api/retailShifts.api";
import { useRetailScope } from "../hooks/useRetailScope";
import type { RetailShift } from "../types";
import CurrencyInput from "../components/pos/CurrencyInput";
export default function RetailShiftsPage() {
  const { scope } = useRetailScope();
  const [shift, setShift] = React.useState<RetailShift | null>(null); const [openingFloat, setOpeningFloat] = React.useState(0); const [terminalId, setTerminalId] = React.useState(""); const [countedCash, setCountedCash] = React.useState(0); const [varianceReason, setVarianceReason] = React.useState(""); const [error, setError] = React.useState("");
  const refresh = React.useCallback(() => { if (!scope) return; void retailShiftsApi.current(scope).then(setShift).catch(showError); }, [scope?.companyCode, scope?.branchId]); React.useEffect(refresh, [refresh]);
  const showError = (cause: unknown) => setError(cause instanceof Error ? cause.message : "Không xử lý được ca bán hàng.");
  if (!scope) return <Notice />;
  const open = async () => { try { setShift(await retailShiftsApi.open(scope, { openingFloat, terminalId: terminalId || undefined })); setError(""); refresh(); } catch (e) { showError(e); } };
  const close = async () => { if (!shift) return; try { setShift(await retailShiftsApi.close(scope, shift._id, { countedCash, varianceReason: varianceReason || undefined })); setError(""); refresh(); } catch (e) { showError(e); } };
  return <section className="mx-auto max-w-5xl space-y-5"><header><h1 className="text-xl font-bold">Ca bán hàng</h1><p className="text-sm text-slate-500">Ghi nhận tiền đầu ca, kiểm đếm mù và đóng ca.</p></header>{error && <p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{!shift ? <div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Mở ca mới</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><CurrencyInput label="Tiền đầu ca" value={openingFloat} onChange={setOpeningFloat} /><Field label="Mã quầy (không bắt buộc)" value={terminalId} onChange={setTerminalId} /></div><button disabled={!Number.isSafeInteger(openingFloat) || openingFloat <= 0} className="mt-4 rounded-xl bg-cyan-600 px-5 py-2.5 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50" onClick={() => void open()}>Mở ca</button></div> : <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><div><h2 className="font-bold">{shift.shiftCode}</h2><p className="text-sm text-slate-500">{shift.businessDate} · {shift.cashierName}</p></div><Status value={shift.status} /></div></div><div className="rounded-2xl border bg-white p-5"><h3 className="font-bold">Đóng ca — kiểm đếm mù</h3><p className="mt-1 text-sm text-slate-500">Số kỳ vọng chỉ hiện sau khi gửi kiểm đếm.</p><CurrencyInput label="Tiền thực đếm" value={countedCash} onChange={setCountedCash} /><Field label="Lý do chênh lệch (nếu có)" value={varianceReason} onChange={setVarianceReason} /><button className="mt-3 rounded-xl bg-slate-900 px-5 py-2.5 font-bold text-white" onClick={() => void close()}>Gửi kiểm đếm và đóng ca</button></div></div>}</section>;
}
function Field({ label, value, onChange, type = "text" }: { label: string; value: string | number; onChange: (value: string) => void; type?: string }) { return <label className="mt-3 block text-sm font-medium">{label}<input aria-label={label} type={type} min={type === "number" ? 0 : undefined} className="mt-1 w-full rounded-xl border px-3 py-2" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function Status({ value }: { value: string }) { return <span className="rounded-full bg-cyan-100 px-3 py-1 text-xs font-bold uppercase text-cyan-700">{value}</span>; }
function Notice() { return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-800">Vui lòng chọn chi nhánh.</div>; }
