import React from "react";
import { Eye, X } from "lucide-react";
import { retailOrdersApi } from "../api/retailOrders.api";
import { useRetailScope } from "../hooks/useRetailScope";
import type { RetailOrder } from "../types";
import { getApiErrorMessage } from "../../../utils/errorMessage";

const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value) + " ₫";
const date = (value?: string) => value ? new Date(value).toLocaleDateString("vi-VN") : "—";

export default function RetailOrdersPageV2() {
  const { scope } = useRetailScope(); const [q, setQ] = React.useState(""); const [status, setStatus] = React.useState(""); const [items, setItems] = React.useState<RetailOrder[]>([]); const [selected, setSelected] = React.useState<RetailOrder | null>(null); const [error, setError] = React.useState("");
  React.useEffect(() => { if (!scope) return; const timer = setTimeout(() => void retailOrdersApi.list(scope, { q, status: status || undefined }).then((data) => setItems(data.items)).catch((e) => setError(getApiErrorMessage(e, "Không tải được danh sách đơn hàng."))), 250); return () => clearTimeout(timer); }, [scope?.companyCode, scope?.branchId, q, status]);
  if (!scope) return <div className="rounded-xl bg-amber-50 p-4 text-amber-800">Vui lòng chọn chi nhánh.</div>;
  return <section className="space-y-4"><header><h1 className="text-xl font-bold">Đơn hàng</h1><p className="text-sm text-slate-500">Danh sách sản phẩm, IMEI/Serial và thời hạn bảo hành.</p></header><div className="grid gap-3 sm:grid-cols-[1fr_220px]"><input aria-label="Tìm đơn hàng" className="rounded-xl border px-3 py-2" placeholder="Mã đơn, khách hàng, số điện thoại" value={q} onChange={(e) => setQ(e.target.value)} /><select aria-label="Trạng thái đơn" className="rounded-xl border px-3 py-2" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option value="draft">Đơn treo</option><option value="confirmed">Còn xử lý</option><option value="completed">Hoàn tất</option><option value="cancelled">Đã hủy</option></select></div>{error && <p className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="grid gap-3">{items.map((order) => <article key={order._id} className="rounded-2xl border bg-white p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="font-bold">{order.orderCode || `Đơn treo #${order._id.slice(-6)}`}</p><p className="text-sm text-slate-600">{order.customerName || "Khách lẻ"}{order.customerPhone ? ` · ${order.customerPhone}` : ""} · {date(order.businessDate)}</p><p className="mt-2 line-clamp-2 text-sm text-slate-700">{order.items.map((item) => `${item.sku} × ${item.quantity}${item.serialNumbers?.length ? ` · IMEI ${item.serialNumbers.join(", ")}` : ""}`).join("; ")}</p></div><div className="text-right"><p className="font-bold text-cyan-700">{money(order.grandTotal)}</p><p className="text-xs text-slate-500">Đã thu {money(order.paidAmount)} · Nợ {money(order.dueAmount)}</p><button aria-label="Xem chi tiết đơn hàng" className="mt-2 rounded-xl border p-2" onClick={() => void retailOrdersApi.detail(scope, order._id).then(setSelected).catch((e) => setError(getApiErrorMessage(e, "Không tải được chi tiết đơn hàng.")))}><Eye className="h-4 w-4" /></button></div></div></article>)}</div>{selected && <OrderDetail order={selected} onClose={() => setSelected(null)} />}</section>;
}

function OrderDetail({ order, onClose }: { order: RetailOrder; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-5"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">{order.orderCode || `Đơn treo #${order._id.slice(-6)}`}</h2><p className="text-sm text-slate-500">{order.customerName || "Khách lẻ"} · {order.customerPhone || "Không có SĐT"} · Ngày bán {date(order.businessDate)}</p></div><button onClick={onClose}><X /></button></div><div className="mt-5 overflow-x-auto rounded-xl border"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="px-3 py-2">Sản phẩm / SKU</th><th className="px-3 py-2">IMEI / Serial</th><th className="px-3 py-2">Mã nội bộ</th><th className="px-3 py-2">Bảo hành khách hàng</th><th className="px-3 py-2 text-right">SL</th><th className="px-3 py-2 text-right">Thành tiền</th></tr></thead><tbody className="divide-y">{order.items.map((item) => <tr key={`${item.productId}-${item.sku}`}><td className="px-3 py-3"><p className="font-medium">{item.productName}</p><p className="text-xs text-slate-500">{item.sku}</p></td><td className="px-3 py-3 text-xs">{item.serialNumbers?.join(", ") || "—"}</td><td className="px-3 py-3 text-xs">{item.internalBarcodes?.join(", ") || "—"}</td><td className="px-3 py-3 text-xs text-emerald-700">{item.customerWarrantyEndAt ? `${date(item.customerWarrantyStartAt)} - ${date(item.customerWarrantyEndAt)}` : "Không có"}</td><td className="px-3 py-3 text-right">{item.quantity}</td><td className="px-3 py-3 text-right font-semibold">{money(item.lineTotal)}</td></tr>)}</tbody></table></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Tổng cộng" value={order.grandTotal} /><Metric label="Đã thu" value={order.paidAmount} /><Metric label="Còn nợ" value={order.dueAmount} /></div></div></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="font-bold">{money(value)}</p></div>; }
