import { FormEvent, useState } from "react";
import { Search, ShieldCheck } from "lucide-react";
import { retailWarrantyService, type WarrantyLookupResult } from "../../../services/retailWarrantyService";

function Coverage({ label, value, color }: { label: string; value?: WarrantyLookupResult["customerWarranty"]; color: string }) {
  const days = value?.daysLeft ?? 0;
  return <div className="rounded-xl border p-4"><div className="flex justify-between text-sm font-semibold"><span>{label}</span><span className={color}>{value?.covered ? `Còn ${days} ngày` : "Đã hết hạn"}</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${value?.covered ? color.replace("text-", "bg-") : "bg-slate-300"}`} style={{ width: `${Math.max(0, Math.min(100, days / 3.65))}%` }} /></div>{value?.endAt && <p className="mt-2 text-xs text-slate-500">Hết hạn: {new Date(value.endAt).toLocaleDateString("vi-VN")}</p>}</div>;
}

function WarrantyLookupPageContent() {
  const [code, setCode] = useState(""); const [result, setResult] = useState<WarrantyLookupResult | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (!code.trim()) return; setBusy(true); setError(""); try { setResult(await retailWarrantyService.lookup(code.trim())); } catch (e) { setError(e instanceof Error ? e.message : "Không thể tra cứu bảo hành"); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-4xl space-y-5"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ShieldCheck className="h-6 w-6 text-cyan-600" />Tra cứu bảo hành</h1><p className="mt-1 text-sm text-slate-500">Nhập IMEI, serial hoặc mã vạch nội bộ.</p></div><form onSubmit={submit} className="flex gap-2 rounded-2xl border bg-white p-4"><input autoFocus value={code} onChange={(e) => setCode(e.target.value)} placeholder="IMEI / Serial / mã vạch" className="min-w-0 flex-1 rounded-xl border px-4 py-3" /><button disabled={busy} className="flex items-center gap-2 rounded-xl bg-cyan-600 px-5 py-3 font-semibold text-white"><Search className="h-4 w-4" />{busy ? "Đang tra..." : "Tra cứu"}</button></form>{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{result && !result.found && <div className="rounded-2xl border bg-amber-50 p-5 text-amber-800">Không tìm thấy máy trong hệ thống. Có thể tiếp nhận bảo hành thủ công.</div>}{result?.found && <div className="space-y-4"><div className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">{result.product?.name}</h2><p className="text-sm text-slate-500">{result.serialNumber} · {result.product?.sku}</p><p className="mt-3 text-sm font-semibold">Bên chịu chi phí: <span className="uppercase text-cyan-700">{result.costBearer}</span></p></div><div className="grid gap-4 md:grid-cols-2"><Coverage label="Bảo hành khách hàng" value={result.customerWarranty} color="text-emerald-600" /><Coverage label={`Bảo hành nhà cung cấp${result.supplierWarranty?.supplierName ? ` · ${result.supplierWarranty.supplierName}` : ""}`} value={result.supplierWarranty} color="text-blue-600" /></div></div>}</div>;
}

function WarrantyReportPanel() {
  const [kind, setKind] = useState<"supplier" | "customer">("customer"); const [items, setItems] = useState<WarrantyLookupResult[]>([]); const [gap, setGap] = useState<WarrantyLookupResult[]>([]); const [loading, setLoading] = useState(false);
  async function load() { setLoading(true); try { setItems(await retailWarrantyService.expiring(kind, 30)); setGap(await retailWarrantyService.gapRisk()); } finally { setLoading(false); } }
  return <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">Theo dõi sắp hết hạn</h2><div className="flex gap-2"><select value={kind} onChange={(e) => setKind(e.target.value as typeof kind)} className="rounded-lg border px-2 py-1 text-sm"><option value="customer">Bảo hành khách</option><option value="supplier">Bảo hành NCC</option></select><button type="button" onClick={() => void load()} className="rounded-lg bg-slate-800 px-3 py-1 text-sm font-semibold text-white">{loading ? "Đang tải..." : "Tải báo cáo"}</button></div></div><p className="mt-3 text-sm text-slate-500">{items.length} máy sắp hết hạn trong 30 ngày · {gap.length} máy có khe hở bảo hành</p>{gap.length > 0 && <div className="mt-3 space-y-2">{gap.slice(0, 10).map((item: any) => <div key={item._id} className="flex justify-between rounded-lg bg-amber-50 px-3 py-2 text-sm"><span>{item.serialNumber || item.internalBarcode}</span><span className="font-semibold text-amber-700">Khe hở {item.gapMonths} tháng</span></div>)}</div>}</section>;
}

export default function WarrantyLookupPage() { return <div className="space-y-5"><WarrantyLookupPageContent /><WarrantyReportPanel /></div>; }
