import { FormEvent, useMemo, useState } from "react";
import { Search, ShieldCheck } from "lucide-react";
import { retailWarrantyService, type WarrantyLookupResult } from "../../../services/retailWarrantyService";

const date = (value?: string) => value ? new Date(value).toLocaleDateString("vi-VN") : "—";
const statusLabel: Record<string, string> = { in_stock: "Còn tồn", sold: "Đã bán", reserved: "Đã giữ hàng", scrapped: "Đã loại bỏ" };

function Coverage({ label, value, color }: { label: string; value?: WarrantyLookupResult["customerWarranty"]; color: string }) {
  const days = value?.daysLeft ?? 0;
  return <div className="rounded-xl border p-4"><div className="flex justify-between text-sm font-semibold"><span>{label}</span><span className={value?.covered ? color : "text-rose-600"}>{value?.covered ? `Còn ${days} ngày` : "Đã hết hạn"}</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${value?.covered ? color.replace("text-", "bg-") : "bg-slate-300"}`} style={{ width: `${Math.max(0, Math.min(100, days / 3.65))}%` }} /></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>Bắt đầu: {date(value?.startAt)}</span><span>Kết thúc: {date(value?.endAt)}</span></div></div>;
}

function RepairLink({ result }: { result: WarrantyLookupResult }) {
  if (!result.found) return null;
  const open = () => window.dispatchEvent(new CustomEvent("inventory:open-repair", { detail: { productId: result.product?.productId, serialNumber: result.serialNumber, productName: result.product?.name || "Sản phẩm", customerId: result.sold?.customerId, coverage: { customer: result.customerWarranty || { covered: false }, supplier: result.supplierWarranty || { covered: false }, costBearer: result.costBearer || "customer", checkedAt: new Date().toISOString() } } }));
  return <button type="button" onClick={open} className="rounded-xl bg-cyan-600 px-4 py-2 text-sm font-semibold text-white">Tạo phiếu sửa chữa/bảo hành</button>;
}

function WarrantyLookupPageContent() {
  const [code, setCode] = useState(""); const [result, setResult] = useState<WarrantyLookupResult | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (!code.trim()) return; setBusy(true); setError(""); try { setResult(await retailWarrantyService.lookup(code.trim())); } catch (e) { setError(e instanceof Error ? e.message : "Không thể tra cứu bảo hành"); } finally { setBusy(false); } }
  return <div className="space-y-4"><form onSubmit={submit} className="flex gap-2 rounded-2xl border bg-white p-4"><input autoFocus value={code} onChange={(e) => setCode(e.target.value)} placeholder="IMEI / Serial / mã vạch nội bộ" className="min-w-0 flex-1 rounded-xl border px-4 py-3" /><button disabled={busy} className="flex items-center gap-2 rounded-xl bg-cyan-600 px-5 py-3 font-semibold text-white"><Search className="h-4 w-4" />{busy ? "Đang tra..." : "Tra cứu"}</button></form>{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{result && !result.found && <div className="rounded-2xl border bg-amber-50 p-5 text-amber-800">Không tìm thấy thiết bị trong hệ thống.</div>}{result?.found && <div className="space-y-4"><div className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{result.product?.name || "Sản phẩm"}</h2><p className="mt-1 text-sm text-slate-500">SKU: {result.product?.sku || "—"} · Trạng thái: {statusLabel[result.status || ""] || result.status || "—"}</p></div><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs font-semibold text-cyan-700">Bên chịu phí: {result.costBearer || "—"}</span></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-slate-500">IMEI / Serial</p><p className="font-mono font-semibold">{result.serialNumber || "—"}</p></div><div><p className="text-xs text-slate-500">Mã vạch nội bộ</p><p className="font-mono font-semibold">{result.internalBarcode || "—"}</p></div><div><p className="text-xs text-slate-500">Ngày bán</p><p className="font-semibold">{date(result.sold?.at)}</p></div><div><p className="text-xs text-slate-500">Mã đơn hàng</p><p className="font-semibold">{result.sold?.orderCode || "—"}</p></div></div><div className="mt-4"><RepairLink result={result} /></div></div><div className="grid gap-4 md:grid-cols-2"><Coverage label="Bảo hành khách hàng" value={result.customerWarranty} color="text-emerald-600" /><Coverage label={`Bảo hành nhà cung cấp${result.supplierWarranty?.supplierName ? ` · ${result.supplierWarranty.supplierName}` : ""}`} value={result.supplierWarranty} color="text-blue-600" /></div></div>}</div>;
}

function WarrantyReportPanel() {
  const [kind, setKind] = useState<"supplier" | "customer">("customer"); const [days, setDays] = useState(30); const [status, setStatus] = useState(""); const [bearer, setBearer] = useState(""); const [query, setQuery] = useState(""); const [items, setItems] = useState<WarrantyLookupResult[]>([]); const [gap, setGap] = useState<WarrantyLookupResult[]>([]); const [loading, setLoading] = useState(false);
  async function load() { setLoading(true); try { setItems(await retailWarrantyService.expiring(kind, days)); setGap(await retailWarrantyService.gapRisk()); } finally { setLoading(false); } }
  const filtered = useMemo(() => items.filter((item: any) => (!status || item.status === status) && (!bearer || item.costBearer === bearer) && (!query || [item.serialNumber, item.internalBarcode, item.sku, item.productName].some((value) => String(value || "").toLowerCase().includes(query.toLowerCase())))), [items, status, bearer, query]);
  return <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">Danh sách sắp hết hạn</h2><button type="button" onClick={() => void load()} className="rounded-lg bg-slate-800 px-3 py-2 text-sm font-semibold text-white">{loading ? "Đang tải..." : "Tải báo cáo"}</button></div><div className="mt-3 grid gap-2 md:grid-cols-5"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm IMEI, SKU, sản phẩm" className="rounded-lg border px-3 py-2 text-sm md:col-span-2" /><select value={kind} onChange={(e) => setKind(e.target.value as typeof kind)} className="rounded-lg border px-2 py-2 text-sm"><option value="customer">BH khách hàng</option><option value="supplier">BH nhà cung cấp</option></select><input type="number" min="1" max="1200" value={days} onChange={(e) => setDays(Number(e.target.value) || 30)} className="rounded-lg border px-3 py-2 text-sm" aria-label="Số ngày sắp hết hạn" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-lg border px-2 py-2 text-sm"><option value="">Mọi trạng thái</option><option value="in_stock">Còn tồn</option><option value="sold">Đã bán</option><option value="reserved">Đã giữ hàng</option></select><select value={bearer} onChange={(e) => setBearer(e.target.value)} className="rounded-lg border px-2 py-2 text-sm"><option value="">Mọi bên chịu phí</option><option value="supplier">Nhà cung cấp</option><option value="shop">Cửa hàng</option><option value="customer">Khách hàng</option></select></div><p className="mt-3 text-sm text-slate-500">{filtered.length} thiết bị phù hợp · {gap.length} thiết bị có khe hở bảo hành</p>{filtered.length > 0 && <div className="mt-3 overflow-x-auto rounded-lg border"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">Sản phẩm / SKU</th><th className="p-3">IMEI / Serial</th><th className="p-3">Mã nội bộ</th><th className="p-3">Trạng thái</th><th className="p-3">Hết hạn</th><th className="p-3">Bên chịu phí</th></tr></thead><tbody className="divide-y">{filtered.map((item: any) => <tr key={item._id}><td className="p-3"><p className="font-medium">{item.productName || "—"}</p><p className="font-mono text-xs text-slate-500">{item.sku || "—"}</p></td><td className="p-3 font-mono text-xs">{item.serialNumber || "—"}</td><td className="p-3 font-mono text-xs">{item.internalBarcode || "—"}</td><td className="p-3">{statusLabel[item.status] || item.status || "—"}</td><td className="p-3">{date(kind === "supplier" ? item.supplierWarranty?.endAt : item.customerWarranty?.endAt)}</td><td className="p-3">{item.costBearer || "—"}</td></tr>)}</tbody></table></div>}</section>;
}

export default function WarrantyLookupPage() { return <div className="space-y-5"><header><h1 className="flex items-center gap-2 text-2xl font-bold"><ShieldCheck className="h-6 w-6 text-cyan-600" />Tra cứu bảo hành</h1><p className="mt-1 text-sm text-slate-500">Tra cứu và theo dõi đầy đủ thông tin bảo hành theo IMEI, Serial hoặc mã vạch nội bộ.</p></header><WarrantyLookupPageContent /><WarrantyReportPanel /></div>; }
