import Joi from "joi";

const policySchema = Joi.object({ matchMode: Joi.string().valid("all", "any").default("all"), minAttendanceRate: Joi.number().min(0).max(100).allow(null), minAssignmentRate: Joi.number().min(0).max(100).allow(null), minMiniTestRate: Joi.number().min(0).max(100).allow(null), minExamRate: Joi.number().min(0).max(100).allow(null) });
const stepSchema = Joi.object({ id: Joi.string().trim().max(100).required(), courseId: Joi.string().required(), order: Joi.number().integer().min(1).required(), minClassSize: Joi.number().integer().min(0).default(0), maxClassSize: Joi.number().integer().min(0).default(0), eligibilityPolicy: policySchema.default() });
export const createLearningRoadmapSchema = Joi.object({ companyCode: Joi.string().trim().optional(), code: Joi.string().trim().max(50).required(), name: Joi.string().trim().max(200).required(), description: Joi.string().allow("").max(2000).default(""), status: Joi.string().valid("active", "inactive").default("active"), steps: Joi.array().items(stepSchema).min(1).required() });
export const updateLearningRoadmapSchema = Joi.object({ code: Joi.string().trim().max(50), name: Joi.string().trim().max(200), description: Joi.string().allow("").max(2000), status: Joi.string().valid("active", "inactive"), steps: Joi.array().items(stepSchema).min(1) });
export const batchProgressionQuerySchema = Joi.object({ roadmapId: Joi.string().optional() });
export const progressionDecisionSchema = Joi.object({ roadmapId: Joi.string().required(), intent: Joi.string().valid("continue", "pending", "stop", "preserve", "repeat").required(), teacherNote: Joi.string().allow("").max(4000).default(""), overrideEligible: Joi.boolean().allow(null).default(null), overrideReason: Joi.string().allow("").max(2000).default(""), learningFormat: Joi.string().allow("").max(100).default(""), preferredTimeSlot: Joi.string().allow("").max(100).default("") });
export const waitlistQuerySchema = Joi.object({ roadmapId: Joi.string().optional(), targetStepId: Joi.string().optional(), batchId: Joi.string().optional(), search: Joi.string().allow("").optional(), page: Joi.number().integer().min(1).optional(), limit: Joi.number().integer().min(1).max(100).optional() });
export const placeWaitlistSchema = Joi.object({ batchId: Joi.string().required(), entryIds: Joi.array().items(Joi.string()).min(1).required() });
