import React, { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { recruitmentApi } from "../../../services/recruitmentService";
import type { RecruitmentPipeline, RecruitmentStage } from "../../../types/recruitment";
import { fieldClass, primaryButton, secondaryButton, ViewState } from "./RecruitmentForms";

export default function RecruitmentPipelineView() {
  const [pipeline, setPipeline] = useState<RecruitmentPipeline | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { setPipeline(await recruitmentApi.getPipeline()); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const change = (index: number, values: Partial<RecruitmentStage>) => setPipeline((old) => old ? ({ ...old, stages: old.stages.map((s, i) => i === index ? { ...s, ...values } : s) }) : old);
  const move = (index: number, offset: number) => setPipeline((old) => { if (!old) return old; const next = [...old.stages]; const target = index + offset; if (target < 0 || target >= next.length) return old; [next[index], next[target]] = [next[target], next[index]]; return { ...old, stages: next.map((s, position) => ({ ...s, position })) }; });
  const save = async () => { if (!pipeline) return; setSaving(true); setError(""); try { setPipeline(await recruitmentApi.savePipeline(pipeline.version, pipeline.stages)); } catch (e: any) { setError(e.status === 409 ? "Quy trình đã thay đổi. Hãy tải lại trước khi lưu." : e.message); } finally { setSaving(false); } };
  return <div className="p-4 sm:p-5"><div className="mb-4 flex items-center"><div><h2 className="text-base font-bold text-slate-900">Quy trình theo chi nhánh</h2><p className="text-xs text-slate-500">Thứ tự và kết quả cuối áp dụng riêng cho chi nhánh đang chọn.</p></div><button className={`${primaryButton} ml-auto`} onClick={save} disabled={saving || !pipeline}>{saving ? "Đang lưu..." : "Lưu quy trình"}</button></div><ViewState loading={loading} error={error} />
    {pipeline && <div className="divide-y divide-slate-200 border-y border-slate-200 bg-white">{pipeline.stages.map((stage, index) => <div key={stage.id} className="grid items-center gap-3 p-3 sm:grid-cols-[44px_1fr_130px_130px_auto]"><input type="color" title="Màu giai đoạn" className="h-9 w-10 cursor-pointer rounded border border-slate-300 p-1" value={stage.color} onChange={(e) => change(index, { color: e.target.value })} /><input aria-label={`Tên giai đoạn ${index + 1}`} className={fieldClass} value={stage.name} onChange={(e) => change(index, { name: e.target.value })} /><select aria-label="Kết quả cuối" className={fieldClass} value={stage.terminalOutcome || ""} onChange={(e) => change(index, { terminalOutcome: (e.target.value || null) as any })}><option value="">Đang xử lý</option><option value="hired">Đã tuyển</option><option value="rejected">Từ chối</option><option value="withdrawn">Rút hồ sơ</option></select><label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={stage.isActive} onChange={(e) => change(index, { isActive: e.target.checked })} />Hoạt động</label><div className="flex justify-end gap-1"><button className={secondaryButton} title="Đưa lên" onClick={() => move(index, -1)}><ArrowUp className="h-4 w-4" /></button><button className={secondaryButton} title="Đưa xuống" onClick={() => move(index, 1)}><ArrowDown className="h-4 w-4" /></button><button className={secondaryButton} title="Xóa giai đoạn" onClick={() => setPipeline({ ...pipeline, stages: pipeline.stages.filter((_, i) => i !== index) })}><Trash2 className="h-4 w-4" /></button></div></div>)}<button className="m-3 inline-flex items-center gap-2 text-sm font-semibold text-cyan-800" onClick={() => setPipeline({ ...pipeline, stages: [...pipeline.stages, { id: crypto.randomUUID(), name: "Giai đoạn mới", color: "#64748b", position: pipeline.stages.length, isActive: true, terminalOutcome: null }] })}><Plus className="h-4 w-4" />Thêm giai đoạn</button></div>}
  </div>;
}
