import React, { useCallback, useEffect, useState } from "react";
import { Plus } from "lucide-react";
import { recruitmentApi } from "../../../services/recruitmentService";
import { getApiErrorMessage } from "../../../utils/errorMessage";
import { authService } from "../../../services/authService";
import type { RecruitmentApplicant, RecruitmentInterview, RecruitmentJob } from "../../../types/recruitment";
import type { UserProfile } from "../../../types";
import { useAuth } from "../../../context/AuthContext";
import { useBranch } from "../../../context/BranchContext";
import { fieldClass, labelClass, primaryButton, RecruitmentDialog, secondaryButton, ViewState } from "./RecruitmentForms";

export default function RecruitmentInterviewsView({ canManage }: { canManage: boolean }) {
  const { userProfile } = useAuth(); const { activeBranchId } = useBranch();
  const [items, setItems] = useState<RecruitmentInterview[]>([]); const [applicants, setApplicants] = useState<RecruitmentApplicant[]>([]); const [jobs, setJobs] = useState<RecruitmentJob[]>([]); const [users, setUsers] = useState<UserProfile[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [adding, setAdding] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [i, a, j, u] = await Promise.all([recruitmentApi.listInterviews(), recruitmentApi.listApplicants(), recruitmentApi.listJobs(), authService.getUsersByCompany(userProfile?.companyCode || "", activeBranchId || undefined)]); setItems(i); setApplicants(a); setJobs(j); setUsers(u); } catch (e: any) { setError(getApiErrorMessage(e, "Không thể tải lịch phỏng vấn.")); } finally { setLoading(false); } }, [userProfile?.companyCode, activeBranchId]);
  useEffect(() => { void load(); }, [load]);
  return <div className="p-4 sm:p-5">{canManage && <div className="mb-4 flex justify-end"><button className={primaryButton} onClick={() => setAdding(true)}><Plus className="h-4 w-4" />Lên lịch phỏng vấn</button></div>}<ViewState loading={loading} error={error} empty={!loading && !items.length ? "Chưa có lịch phỏng vấn trong chi nhánh này." : undefined} />{items.length > 0 && <div className="divide-y divide-slate-200 border-y border-slate-200 bg-white">{items.map((item) => <div key={item._id} className="grid gap-2 p-4 sm:grid-cols-[180px_1fr_1fr_120px]"><div><div className="font-semibold">{new Date(item.scheduledStart).toLocaleDateString("vi-VN")}</div><div className="text-xs text-slate-500">{new Date(item.scheduledStart).toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" })} - {new Date(item.scheduledEnd).toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" })}</div></div><div><div className="font-semibold">{applicants.find((a) => a._id === item.applicantId)?.fullName || "Ứng viên"}</div><div className="text-xs text-slate-500">{jobs.find((j) => j._id === item.jobId)?.title}</div></div><div className="text-sm">{item.format === "online" ? item.meetingLink || "Trực tuyến" : item.location || "Tại văn phòng"}</div><div className="text-sm font-semibold capitalize">{item.status}</div></div>)}</div>}{canManage && adding && <InterviewForm applicants={applicants} jobs={jobs} users={users} onClose={() => setAdding(false)} onSaved={async () => { setAdding(false); await load(); }} />}</div>;
}

function InterviewForm({ applicants, jobs, users, onClose, onSaved }: { applicants: RecruitmentApplicant[]; jobs: RecruitmentJob[]; users: UserProfile[]; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ applicantId: "", jobId: "", scheduledStart: "", scheduledEnd: "", format: "onsite", location: "", meetingLink: "", interviewerIds: [] as string[], notes: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const chooseApplicant = (id: string) => { const applicant = applicants.find((a) => a._id === id); setForm({ ...form, applicantId: id, jobId: applicant?.jobId || "" }); };
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); try { await recruitmentApi.createInterview(form as any); await onSaved(); } catch (err: any) { setError(getApiErrorMessage(err, "Không thể lưu lịch phỏng vấn.")); } finally { setSaving(false); } };
  return <RecruitmentDialog title="Lên lịch phỏng vấn" onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{error && <p className="sm:col-span-2 text-sm text-red-600">{error}</p>}<label className={labelClass}>Ứng viên<select required className={fieldClass} value={form.applicantId} onChange={(e) => chooseApplicant(e.target.value)}><option value="">Chọn ứng viên</option>{applicants.map((a) => <option key={a._id} value={a._id}>{a.fullName}</option>)}</select></label><label className={labelClass}>Vị trí<input disabled className={fieldClass} value={jobs.find((j) => j._id === form.jobId)?.title || ""} /></label><label className={labelClass}>Bắt đầu<input required type="datetime-local" className={fieldClass} value={form.scheduledStart} onChange={(e) => setForm({ ...form, scheduledStart: e.target.value })} /></label><label className={labelClass}>Kết thúc<input required type="datetime-local" className={fieldClass} value={form.scheduledEnd} onChange={(e) => setForm({ ...form, scheduledEnd: e.target.value })} /></label><label className={labelClass}>Hình thức<select className={fieldClass} value={form.format} onChange={(e) => setForm({ ...form, format: e.target.value })}><option value="onsite">Tại văn phòng</option><option value="online">Trực tuyến</option><option value="phone">Điện thoại</option></select></label><label className={labelClass}>{form.format === "online" ? "Link họp" : "Địa điểm"}<input className={fieldClass} value={form.format === "online" ? form.meetingLink : form.location} onChange={(e) => setForm({ ...form, [form.format === "online" ? "meetingLink" : "location"]: e.target.value })} /></label><label className={`${labelClass} sm:col-span-2`}>Người phỏng vấn<select multiple className={`${fieldClass} min-h-24`} value={form.interviewerIds} onChange={(e) => setForm({ ...form, interviewerIds: Array.from(e.target.selectedOptions, (option) => option.value) })}>{users.map((u) => <option key={u.uid} value={u.uid}>{u.displayName}</option>)}</select></label><label className={`${labelClass} sm:col-span-2`}>Ghi chú<textarea className={fieldClass} rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" className={secondaryButton} onClick={onClose}>Hủy</button><button className={primaryButton} disabled={saving}>{saving ? "Đang lưu..." : "Tạo lịch"}</button></div></form></RecruitmentDialog>;
}
