import React, { useCallback, useEffect, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { recruitmentApi } from "../../../services/recruitmentService";
import { authService } from "../../../services/authService";
import { toast } from "../../../pages/Toast";
import { getApiErrorMessage } from "../../../utils/errorMessage";
import type { RecruitmentApplicant, RecruitmentInterview, RecruitmentJob } from "../../../types/recruitment";
import type { UserProfile } from "../../../types";
import { useAuth } from "../../../context/AuthContext";
import { useBranch } from "../../../context/BranchContext";
import { ConfirmDialog } from "../../common/ConfirmDialog";
import { fieldClass, labelClass, primaryButton, RecruitmentDialog, secondaryButton, ViewState } from "./RecruitmentForms";

const statusLabels: Record<RecruitmentInterview["status"], string> = { scheduled: "Đã lên lịch", completed: "Hoàn thành", cancelled: "Đã hủy" };
const localDateTime = (value = "") => { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); };

export default function RecruitmentInterviewsWorkspace({ canManage }: { canManage: boolean }) {
  const { userProfile } = useAuth(); const { activeBranchId } = useBranch();
  const [items, setItems] = useState<RecruitmentInterview[]>([]); const [applicants, setApplicants] = useState<RecruitmentApplicant[]>([]); const [jobs, setJobs] = useState<RecruitmentJob[]>([]); const [users, setUsers] = useState<UserProfile[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [editing, setEditing] = useState<RecruitmentInterview | null | undefined>(); const [pendingDelete, setPendingDelete] = useState<RecruitmentInterview | null>(null); const [deleting, setDeleting] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [i, a, j, u] = await Promise.all([recruitmentApi.listInterviews(), recruitmentApi.listApplicants(), recruitmentApi.listJobs(), authService.getUsersByCompany(userProfile?.companyCode || "", activeBranchId || undefined)]); setItems(i); setApplicants(a); setJobs(j); setUsers(u); } catch (e) { setError(getApiErrorMessage(e, "Không thể tải lịch phỏng vấn.")); } finally { setLoading(false); } }, [userProfile?.companyCode, activeBranchId]);
  useEffect(() => { void load(); }, [load]);
  const applicantName = (item: RecruitmentInterview) => applicants.find((a) => a._id === item.applicantId)?.fullName || "Ứng viên";
  const remove = async () => { if (!pendingDelete || deleting) return; const item = pendingDelete; const name = applicantName(item); setDeleting(true); try { await recruitmentApi.deleteInterview(item._id, item.version); setPendingDelete(null); await load(); toast.success(`Đã xóa lịch phỏng vấn của ${name}.`); } catch (e: any) { const conflict = e.status === 409; const message = conflict ? "Không thể xóa vì lịch phỏng vấn đã được thay đổi ở nơi khác. Danh sách đã được tải lại." : getApiErrorMessage(e, "Không thể xóa lịch phỏng vấn. Vui lòng thử lại."); if (conflict) { setPendingDelete(null); await load(); } toast.error(message); } finally { setDeleting(false); } };
  return <div className="p-4 sm:p-5">
    {canManage && <div className="mb-4 flex justify-end"><button className={primaryButton} onClick={() => setEditing(null)}><Plus className="h-4 w-4" />Lên lịch phỏng vấn</button></div>}
    <ViewState loading={loading} error={error} empty={!loading && !items.length ? "Chưa có lịch phỏng vấn trong chi nhánh này." : undefined} />
    {items.length > 0 && <div className="divide-y divide-slate-200 border-y border-slate-200 bg-white">{items.map((item) => { const name = applicantName(item); return <div key={item._id} className="grid gap-2 p-4 sm:grid-cols-[180px_1fr_1fr_120px_auto] sm:items-center"><div><div className="font-semibold">{new Date(item.scheduledStart).toLocaleDateString("vi-VN")}</div><div className="text-xs text-slate-500">{new Date(item.scheduledStart).toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" })} - {new Date(item.scheduledEnd).toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" })}</div></div><div><div className="font-semibold">{name}</div><div className="text-xs text-slate-500">{jobs.find((j) => j._id === item.jobId)?.title}</div></div><div className="text-sm">{item.format === "online" ? item.meetingLink || "Trực tuyến" : item.location || (item.format === "phone" ? "Điện thoại" : "Tại văn phòng")}</div><div className="text-sm font-semibold">{statusLabels[item.status]}</div>{canManage && <div className="flex gap-1 sm:justify-end"><button type="button" className={secondaryButton} aria-label={`Sửa lịch phỏng vấn ${name}`} onClick={() => setEditing(item)}><Pencil className="h-4 w-4" /></button><button type="button" className={secondaryButton} aria-label={`Xóa lịch phỏng vấn ${name}`} onClick={() => setPendingDelete(item)}><Trash2 className="h-4 w-4" /></button></div>}</div>; })}</div>}
    {editing !== undefined && <InterviewForm interview={editing} applicants={applicants} jobs={jobs} users={users} onClose={() => setEditing(undefined)} onSaved={async () => { setEditing(undefined); await load(); }} />}
    <ConfirmDialog isOpen={pendingDelete !== null} title="Xóa lịch phỏng vấn?" description={pendingDelete ? `Bạn có chắc muốn xóa lịch phỏng vấn của ${applicantName(pendingDelete)} lúc ${new Date(pendingDelete.scheduledStart).toLocaleString("vi-VN")}?` : ""} cancelLabel="Hủy" confirmLabel="Xóa lịch" tone="danger" isSubmitting={deleting} onClose={() => { if (!deleting) setPendingDelete(null); }} onConfirm={remove} />
  </div>;
}

type FormValue = { applicantId: string; jobId: string; scheduledStart: string; scheduledEnd: string; format: RecruitmentInterview["format"]; location: string; meetingLink: string; interviewerIds: string[]; status: RecruitmentInterview["status"]; result: string; notes: string };
function InterviewForm({ interview, applicants, jobs, users, onClose, onSaved }: { interview: RecruitmentInterview | null; applicants: RecruitmentApplicant[]; jobs: RecruitmentJob[]; users: UserProfile[]; onClose: () => void; onSaved: () => void | Promise<void> }) {
  const [form, setForm] = useState<FormValue>(() => interview ? { applicantId: interview.applicantId, jobId: interview.jobId, scheduledStart: localDateTime(interview.scheduledStart), scheduledEnd: localDateTime(interview.scheduledEnd), format: interview.format, location: interview.location || "", meetingLink: interview.meetingLink || "", interviewerIds: interview.interviewerIds || [], status: interview.status, result: interview.result || "", notes: interview.notes || "" } : { applicantId: "", jobId: "", scheduledStart: "", scheduledEnd: "", format: "onsite", location: "", meetingLink: "", interviewerIds: [], status: "scheduled", result: "", notes: "" });
  const [saving, setSaving] = useState(false);
  const chooseApplicant = (id: string) => { const applicant = applicants.find((a) => a._id === id); setForm({ ...form, applicantId: id, jobId: applicant?.jobId || "" }); };
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); const editable = { scheduledStart: form.scheduledStart, scheduledEnd: form.scheduledEnd, format: form.format, location: form.location, meetingLink: form.meetingLink, interviewerIds: form.interviewerIds, status: form.status, result: form.result, notes: form.notes }; try { if (interview) { await recruitmentApi.updateInterview(interview._id, { ...editable, version: interview.version }); toast.success(`Đã cập nhật lịch phỏng vấn của ${applicants.find((a) => a._id === interview.applicantId)?.fullName || "ứng viên"}.`); } else { await recruitmentApi.createInterview({ ...editable, applicantId: form.applicantId, jobId: form.jobId }); toast.success("Đã tạo lịch phỏng vấn."); } await onSaved(); } catch (err) { toast.error(getApiErrorMessage(err, interview ? "Không thể cập nhật lịch phỏng vấn." : "Không thể tạo lịch phỏng vấn.")); } finally { setSaving(false); } };
  return <RecruitmentDialog title={interview ? "Sửa lịch phỏng vấn" : "Lên lịch phỏng vấn"} onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
    <label className={labelClass}>Ứng viên<select aria-label="Ứng viên" required disabled={Boolean(interview)} className={fieldClass} value={form.applicantId} onChange={(e) => chooseApplicant(e.target.value)}><option value="">Chọn ứng viên</option>{applicants.map((a) => <option key={a._id} value={a._id}>{a.fullName}</option>)}</select></label>
    <label className={labelClass}>Vị trí<input aria-label="Vị trí" disabled className={fieldClass} value={jobs.find((j) => j._id === form.jobId)?.title || ""} /></label>
    <label className={labelClass}>Bắt đầu<input aria-label="Bắt đầu" required type="datetime-local" className={fieldClass} value={form.scheduledStart} onChange={(e) => setForm({ ...form, scheduledStart: e.target.value })} /></label><label className={labelClass}>Kết thúc<input aria-label="Kết thúc" required type="datetime-local" className={fieldClass} value={form.scheduledEnd} onChange={(e) => setForm({ ...form, scheduledEnd: e.target.value })} /></label>
    <label className={labelClass}>Hình thức<select aria-label="Hình thức" className={fieldClass} value={form.format} onChange={(e) => setForm({ ...form, format: e.target.value as RecruitmentInterview["format"] })}><option value="onsite">Tại văn phòng</option><option value="online">Trực tuyến</option><option value="phone">Điện thoại</option></select></label><label className={labelClass}>{form.format === "online" ? "Link họp" : "Địa điểm"}<input aria-label={form.format === "online" ? "Link họp" : "Địa điểm"} className={fieldClass} value={form.format === "online" ? form.meetingLink : form.location} onChange={(e) => setForm({ ...form, [form.format === "online" ? "meetingLink" : "location"]: e.target.value })} /></label>
    <label className={labelClass}>Trạng thái<select aria-label="Trạng thái" className={fieldClass} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as RecruitmentInterview["status"] })}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className={labelClass}>Kết quả<input aria-label="Kết quả" className={fieldClass} value={form.result} onChange={(e) => setForm({ ...form, result: e.target.value })} /></label>
    <label className={`${labelClass} sm:col-span-2`}>Người phỏng vấn<select aria-label="Người phỏng vấn" multiple className={`${fieldClass} min-h-24`} value={form.interviewerIds} onChange={(e) => setForm({ ...form, interviewerIds: Array.from(e.target.selectedOptions, (option) => option.value) })}>{users.map((u) => <option key={u.uid} value={u.uid}>{u.displayName}</option>)}</select></label><label className={`${labelClass} sm:col-span-2`}>Ghi chú<textarea aria-label="Ghi chú" className={fieldClass} rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label>
    <div className="flex justify-end gap-2 sm:col-span-2"><button type="button" className={secondaryButton} onClick={onClose} disabled={saving}>Hủy</button><button className={primaryButton} disabled={saving}>{saving ? "Đang lưu..." : interview ? "Lưu thay đổi" : "Tạo lịch"}</button></div>
  </form></RecruitmentDialog>;
}
