import { useEffect, useMemo, useState } from "react";
import { X } from "lucide-react";
import { createPayrollFormulaForm, payrollFormulaFormToDefinition, payrollFormulaVariables, validatePayrollFormulaForm, type PayrollFormulaForm } from "./payrollFormulaForm";
import { payrollService } from "../../../services/payrollService";
const input = "w-full rounded-lg border border-slate-300 px-3 py-2 text-sm";
export function PayrollFormulaModal({ initial, saving, onClose, onSave }: { initial?: any; saving: boolean; onClose: () => void; onSave: (value: any) => void | Promise<void> }) {
  const initialForm = useMemo(() => initial ? { ...createPayrollFormulaForm(), ...initial, conditionCombinator: initial.conditions?.combinator ?? "and", conditions: initial.conditions?.items ?? [], leftVariable: initial.expression?.left?.key ?? "monthlySalary", operator: initial.expression?.operator ?? "multiply", rightValue: initial.expression?.right?.value ?? 0, roundingMode: initial.rounding?.mode ?? "nearest", roundingUnit: initial.rounding?.unit ?? 1000, effectiveFrom: String(initial.effectiveFrom).slice(0, 10), effectiveTo: initial.effectiveTo ? String(initial.effectiveTo).slice(0, 10) : "" } : createPayrollFormulaForm(), [initial]);
  const [form, setForm] = useState<PayrollFormulaForm>(initialForm); const [errors, setErrors] = useState<Record<string, string>>({}); const [sampleValue,setSampleValue]=useState(0); const [customVariables,setCustomVariables]=useState<any[]>([]); useEffect(()=>{void payrollService.getPeriodInputVariables().then((items:any[])=>setCustomVariables(items.filter(item=>item.status==="active"))).catch(()=>{});},[]); const variables=[...payrollFormulaVariables,...customVariables.map(item=>[`custom.${item.code}`,item.name] as const)]; const set = (key: keyof PayrollFormulaForm, value: any) => setForm((current) => ({ ...current, [key]: value }));
  const rawPreview = form.operator === "add" ? sampleValue + form.rightValue : form.operator === "subtract" ? sampleValue - form.rightValue : form.operator === "multiply" ? sampleValue * form.rightValue : form.operator === "divide" ? (form.rightValue === 0 ? NaN : sampleValue / form.rightValue) : form.operator === "min" ? Math.min(sampleValue, form.rightValue) : Math.max(sampleValue, form.rightValue);
  const preview = !Number.isFinite(rawPreview) ? "Không thể tính" : (form.roundingMode === "none" ? rawPreview : (form.roundingMode === "up" ? Math.ceil(rawPreview/form.roundingUnit) : form.roundingMode === "down" ? Math.floor(rawPreview/form.roundingUnit) : Math.round(rawPreview/form.roundingUnit))*form.roundingUnit).toLocaleString("vi-VN")+" đ";
  const submit = () => { const found = validatePayrollFormulaForm(form); setErrors(found); if (!Object.keys(found).length) void onSave(payrollFormulaFormToDefinition(form)); };
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-900/60 p-4"><div role="dialog" className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><h3 className="font-bold text-slate-900">{initial ? "Sửa công thức tùy chỉnh" : "Tạo công thức tùy chỉnh"}</h3><p className="text-xs text-slate-500">Chọn biến và toán tử; không cần nhập mã kỹ thuật.</p></div><button aria-label="Đóng" onClick={onClose}><X size={18}/></button></div>
  <div className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-sm">Mã công thức<input aria-label="Mã công thức" className={input} value={form.code} onChange={(e)=>set("code",e.target.value)}/>{errors.code && <span className="text-xs text-rose-600">{errors.code}</span>}</label><label className="text-sm">Tên công thức<input aria-label="Tên công thức" className={input} value={form.name} onChange={(e)=>set("name",e.target.value)}/>{errors.name && <span className="text-xs text-rose-600">{errors.name}</span>}</label><label className="text-sm md:col-span-2">Mô tả<input className={input} value={form.description} onChange={(e)=>set("description",e.target.value)}/></label><label className="text-sm">Nhóm kết quả<select className={input} value={form.resultBucket} onChange={(e)=>set("resultBucket",e.target.value)}><option value="allowance">Phụ cấp</option><option value="bonus">Thưởng</option><option value="deduction">Khấu trừ / phạt</option><option value="adjustment">Điều chỉnh</option></select></label><label className="text-sm">Thứ tự ưu tiên<input className={input} type="number" value={form.priority} onChange={(e)=>set("priority",Number(e.target.value))}/></label><label className="text-sm">Hiệu lực từ<input className={input} type="date" value={form.effectiveFrom} onChange={(e)=>set("effectiveFrom",e.target.value)}/></label><label className="text-sm">Hiệu lực đến<input className={input} type="date" value={form.effectiveTo} onChange={(e)=>set("effectiveTo",e.target.value)}/></label></div>
  <div className="mt-5 rounded-xl border p-4"><div className="flex items-center justify-between"><h4 className="font-semibold">Điều kiện áp dụng</h4><button className="text-sm font-semibold text-indigo-600" onClick={()=>set("conditions",[...form.conditions,{left:"actualWorkDays",operator:"greaterThanOrEqual",right:0}])}>+ Thêm điều kiện</button></div>{form.conditions.length>1&&<select aria-label="Cách kết hợp điều kiện" className={`${input} mt-3`} value={form.conditionCombinator} onChange={(e)=>set("conditionCombinator",e.target.value)}><option value="and">Tất cả điều kiện (VÀ)</option><option value="or">Một trong các điều kiện (HOẶC)</option></select>}<div className="mt-3 space-y-2">{form.conditions.map((condition,index)=><div key={index} className="grid gap-2 md:grid-cols-[1fr_100px_1fr_auto]"><select className={input} value={condition.left} onChange={(e)=>set("conditions",form.conditions.map((item,i)=>i===index?{...item,left:e.target.value}:item))}>{payrollFormulaVariables.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select className={input} value={condition.operator} onChange={(e)=>set("conditions",form.conditions.map((item,i)=>i===index?{...item,operator:e.target.value}:item))}><option value="greaterThan">&gt;</option><option value="greaterThanOrEqual">≥</option><option value="lessThan">&lt;</option><option value="lessThanOrEqual">≤</option><option value="equal">=</option><option value="notEqual">≠</option></select><input className={input} type="number" value={condition.right} onChange={(e)=>set("conditions",form.conditions.map((item,i)=>i===index?{...item,right:Number(e.target.value)}:item))}/><button aria-label={`Xóa điều kiện ${index+1}`} onClick={()=>set("conditions",form.conditions.filter((_,i)=>i!==index))}>×</button></div>)}</div></div>
  <div className="mt-4 rounded-xl border p-4"><h4 className="font-semibold">Công thức tính</h4><div className="mt-3 grid gap-2 md:grid-cols-3"><select className={input} value={form.leftVariable} onChange={(e)=>set("leftVariable",e.target.value)}>{payrollFormulaVariables.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select className={input} value={form.operator} onChange={(e)=>set("operator",e.target.value)}><option value="add">+</option><option value="subtract">−</option><option value="multiply">×</option><option value="divide">÷</option><option value="min">Nhỏ nhất</option><option value="max">Lớn nhất</option></select><input aria-label="Giá trị" className={input} type="number" value={form.rightValue} onChange={(e)=>set("rightValue",Number(e.target.value))}/></div><div className="mt-3 grid gap-2 md:grid-cols-2"><select className={input} value={form.roundingMode} onChange={(e)=>set("roundingMode",e.target.value)}><option value="none">Không làm tròn</option><option value="nearest">Gần nhất</option><option value="up">Làm tròn lên</option><option value="down">Làm tròn xuống</option></select><select className={input} value={form.roundingUnit} onChange={(e)=>set("roundingUnit",Number(e.target.value))}>{[1,10,100,1000].map(value=><option key={value} value={value}>{value.toLocaleString()} đ</option>)}</select></div></div>
  <div className="mt-4 rounded-xl bg-violet-50 p-4"><h4 className="font-semibold text-violet-900">Xem trước</h4><div className="mt-2 flex items-center gap-3"><input aria-label="Giá trị biến mẫu" className={input} type="number" value={sampleValue} onChange={(e)=>setSampleValue(Number(e.target.value))}/><span className="shrink-0 text-sm font-bold text-violet-800">Kết quả: {preview}</span></div></div><div className="mt-5 flex justify-end gap-2"><button className="rounded-lg border px-4 py-2 text-sm" onClick={onClose}>Hủy</button><button disabled={saving} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" onClick={submit}>{saving ? "Đang lưu..." : "Lưu công thức"}</button></div></div></div>;
}
