export const payrollFormulaVariables = [
  ["monthlySalary", "Lương tháng"], ["attendanceSalary", "Lương theo công"], ["standardWorkDays", "Ngày công chuẩn"], ["actualWorkDays", "Ngày công thực tế"],
  ["standardWorkHours", "Giờ công chuẩn"], ["actualWorkHours", "Giờ công thực tế"], ["shortageMinutes", "Phút thiếu công"], ["lateMinutes", "Phút đi muộn"],
  ["earlyLeaveMinutes", "Phút về sớm"], ["paidLeaveDays", "Ngày nghỉ có lương"], ["weekdayOvertimeHours", "Giờ tăng ca ngày thường"], ["restDayOvertimeHours", "Giờ tăng ca ngày nghỉ"], ["holidayOvertimeHours", "Giờ tăng ca ngày lễ"], ["tenureMonths", "Thâm niên (tháng)"],
] as const;
export type FormulaConditionForm = { left: string; operator: string; right: number };
export type PayrollFormulaForm = { code: string; name: string; description: string; resultBucket: string; priority: number; effectiveFrom: string; effectiveTo: string; conditionCombinator: "and" | "or"; conditions: FormulaConditionForm[]; leftVariable: string; operator: string; rightValue: number; roundingMode: string; roundingUnit: number };
export const createPayrollFormulaForm = (): PayrollFormulaForm => ({ code: "", name: "", description: "", resultBucket: "allowance", priority: 10, effectiveFrom: new Date().toISOString().slice(0, 10), effectiveTo: "", conditionCombinator: "and", conditions: [], leftVariable: "monthlySalary", operator: "multiply", rightValue: 0, roundingMode: "nearest", roundingUnit: 1000 });
export function payrollFormulaFormToDefinition(form: PayrollFormulaForm) { return { code: form.code.trim(), name: form.name.trim(), description: form.description.trim(), resultBucket: form.resultBucket, priority: form.priority, effectiveFrom: form.effectiveFrom, ...(form.effectiveTo ? { effectiveTo: form.effectiveTo } : {}), conditions: { combinator: form.conditionCombinator, items: form.conditions }, expression: { type: "binary", operator: form.operator, left: { type: "variable", key: form.leftVariable }, right: { type: "constant", value: form.rightValue } }, rounding: { mode: form.roundingMode, unit: form.roundingUnit } }; }
export function validatePayrollFormulaForm(form: PayrollFormulaForm) { const errors: Record<string, string> = {}; if (!form.code.trim()) errors.code = "Nhập mã công thức"; if (!form.name.trim()) errors.name = "Nhập tên công thức"; if (!Number.isFinite(form.rightValue)) errors.rightValue = "Giá trị không hợp lệ"; if (!Number.isInteger(form.priority)) errors.priority = "Thứ tự phải là số nguyên"; return errors; }
