import { useEffect, useState } from "react";
import { Copy, Pencil, Plus, Power, PowerOff } from "lucide-react";
import { payrollService } from "../../../services/payrollService";
import { toast } from "../../../pages/Toast";
import { PayrollFormulaModal } from "./PayrollFormulaModal";
import { PayrollPolicyConfirmDialog } from "./PayrollPolicyConfirmDialog";
import { canRecalculateAfterPolicySave } from "./payrollPolicySaveDecision";
const buckets: Record<string,string> = { allowance: "Phụ cấp", bonus: "Thưởng", deduction: "Khấu trừ / phạt", adjustment: "Điều chỉnh" };
export function PayrollFormulaLibrary({ canManage, runStatus, onRecalculate }: { canManage: boolean; runStatus?: string; onRecalculate?: () => Promise<void> }) {
  const [items,setItems]=useState<any[]>([]), [editor,setEditor]=useState<any>(null), [saving,setSaving]=useState(false), [pending,setPending]=useState<any>(null), [error,setError]=useState("");
  const load=async()=>{try{setItems(await payrollService.getFormulas());}catch(e){toast.error(e instanceof Error?e.message:"Không thể tải thư viện công thức");}}; useEffect(()=>{void load();},[]);
  const persist=async(recalculate=false)=>{if(!pending)return;setSaving(true);setError("");try{await payrollService.updateFormula(pending.formula._id,{...pending.definition,expectedVersion:pending.formula.version});setPending(null);await load();if(recalculate&&onRecalculate){try{await onRecalculate();toast.success("Đã lưu công thức và cập nhật bảng lương");}catch{toast.error("Đã lưu công thức nhưng chưa cập nhật được bảng lương");}}else toast.success("Đã lưu công thức");}catch(e){setError(e instanceof Error?e.message:"Không thể lưu công thức");}finally{setSaving(false);}};
  const save=async(definition:any)=>{if(editor?.status==="active"){setPending({formula:editor,definition});setEditor(null);return;}setSaving(true);try{if(editor)await payrollService.updateFormula(editor._id,{...definition,expectedVersion:editor.version});else await payrollService.createFormula(definition);setEditor(null);await load();toast.success("Đã lưu công thức");}catch(e){toast.error(e instanceof Error?e.message:"Không thể lưu công thức");}finally{setSaving(false);}};
  const action=async(kind:string,item:any)=>{try{if(kind==="edit")return setEditor(item);if(kind==="clone"){const code=window.prompt("Mã công thức bản sao",`${item.code}-copy`);if(code)await payrollService.cloneFormula(item._id,code);}else if(kind==="activate")await payrollService.activateFormula(item._id);else await payrollService.retireFormula(item._id);await load();}catch(e){toast.error(e instanceof Error?e.message:"Không thể cập nhật công thức");}};
  return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-bold text-slate-800">Thư viện công thức</h3><p className="text-xs text-slate-500">Phụ cấp, thưởng, khấu trừ và điều chỉnh từ biến công lương được phép.</p></div>{canManage&&<button onClick={()=>setEditor({})} className="inline-flex items-center gap-1 rounded-lg bg-violet-600 px-3 py-2 text-xs font-bold text-white"><Plus size={14}/>Tạo công thức</button>}</div><div className="space-y-2">{items.length===0?<p className="text-sm text-slate-400">Chưa có công thức tùy chỉnh.</p>:items.map(item=><div key={item._id} data-formula-status={item.status} className={`flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3 ${item.status==="active"?"border-violet-400 bg-violet-50 shadow-sm ring-1 ring-violet-100":"border-slate-100"}`}><div><div className="flex items-center gap-2 font-semibold text-slate-800">{item.name}<span className="text-xs font-normal text-slate-400">({item.code})</span>{item.status==="active"&&<span className="rounded-full bg-violet-600 px-2 py-0.5 text-[11px] text-white">Đang áp dụng</span>}</div><p className="mt-1 text-xs text-slate-500">{buckets[item.resultBucket]} · Ưu tiên {item.priority} · v{item.version}</p></div>{canManage&&<div className="flex gap-1"><button aria-label={`Sửa ${item.name}`} onClick={()=>void action("edit",item)} className="rounded border p-1.5"><Pencil size={13}/></button><button aria-label={`Nhân bản ${item.name}`} onClick={()=>void action("clone",item)} className="rounded border p-1.5"><Copy size={13}/></button>{item.status==="active"?<button aria-label={`Ngưng ${item.name}`} onClick={()=>void action("retire",item)} className="rounded border p-1.5"><PowerOff size={13}/></button>:<button aria-label={`Áp dụng ${item.name}`} onClick={()=>void action("activate",item)} className="rounded border p-1.5"><Power size={13}/></button>}</div>}</div>)}</div>{editor&&<PayrollFormulaModal initial={editor._id?editor:undefined} saving={saving} onClose={()=>setEditor(null)} onSave={save}/>} {pending&&<PayrollPolicyConfirmDialog title="Lưu thay đổi công thức đang áp dụng?" description={pending.formula.name} impact={canRecalculateAfterPolicySave(runStatus)?"Chọn chỉ lưu hoặc cập nhật lại kỳ lương đang mở.":"Kỳ hiện tại đã qua bước Nháp nên chỉ có thể lưu cấu hình."} confirmLabel="Chỉ lưu cấu hình" secondaryLabel={canRecalculateAfterPolicySave(runStatus)&&onRecalculate?"Lưu và cập nhật bảng lương":undefined} tone="warning" pending={saving} error={error} onCancel={()=>setPending(null)} onConfirm={()=>void persist(false)} onSecondary={()=>void persist(true)}/>}</div>;
}
